### ISSUE TITLE
Support "!layout.html.twig" syntax

### ISSUE THREAD

**Issue by henrikbjorn** [twigphp/Twig#1334]
This is something i saw in Jinja's documentation and i think it could be really useful.

Lets say we have a "layout.html.twig" and somebody prepended a path to it. It would then not be possible to reference it directly. This is what "!" does `{% extends "!layout.html.twig" %} would now reference the original (or the next template found)

**Comment by fabpot** [comment]
Not easy to implement with the current template loader infrastructure.

**Comment by fabpot** [comment]
As Symfony is now using the "standard" Twig file loaders, and as Twig supports this somehow (see https://twig.symfony.com/doc/2.x/recipes.html#overriding-a-template-that-also-extends-itself), I'm going to close this feature request (also because implementing this is non-trivial with the current infrastructure).
