### ISSUE TITLE
Overriding block in included/embedded files

### ISSUE THREAD

**Issue by jpass** [twigphp/Twig#1360]
Including template should give the parent template ability to override blocks. Here comes the embedd tag. But when parent template is further included/embedded we have no ability to override those block anymore.

My problem:

```
{# _index_row.html.twig #}
<tr>
    <td>{% block actions %}{% endblock %}</td>
<tr>
```

```
{# _index.html.twig#}
<table>
    {% for entity in entities %}
        {% include _index_row | default('_index_row.html.twig') %}
    {% endfor %}
</table>
```

```
{# index.html.twig #}
{% extends layout | default( 'some_layout.html.twig') %}

{% block content %}
    <div>
        {% include _index | default('_index.html.twig') %}
        {% block foobar %}{% endblock %}
    </div>
{% endblock %}
```

Those templates come in reusable bundle, and they are cut to pieces so i can use table or table row to present data in another context or by using ajax.

When i need to override some parts of this structure i can simply use:

```
{# new_index.html.twig #}
{# here i can override included files like set _include 'overriding file' #}
{% extends 'index.html.twig' %}

{# here i can override block of parent template but not its included children #}
{% block actions %}
    add some content
{% endblock %}
```

The file "new_index.html.twig" doesn't have any ability to override blocks of included and/or embedded files down the template tree.

Shouldn't include tag work as 'copy and paste' for part of code? Or maybe embedd tag should open the block for overriding?

**Comment by naydav** [comment]
Any updates? We have problem with ini_get('soap.wsdl_cache_enabled')

**Comment by jpass** [comment]
```twig
{# parent.twig #}
{% block hello %}world{% endblock %}

{# brother.twig #}
{% block hello %}universe{% endblock %}

{# me.twig #}
{% extends 'parent.twig' %}
{% include 'brother.twig' %}

{{ block('hello') }} {# world or universe? #}

{% block hello %}
  {{ parent() }} {# world or universe? #}
{% endblock }
```

For me this should end up as:
``` twig
{# me.twig #}
{% extends 'parent.twig' %}
{% block hello %}universe{% endblock %} {# because included #}

{{ block('hello') }}  {# universe because above block #}

{% block hello %} {# second hello block, error? #}
  {{ parent() }} {# world becase parent #}
{% endblock }
```

------------
This is how we worked it out:
``` twig
{# _index_row.html.twig #}
<tr>
    <td>{% block actions %}{% endblock %}</td>
<tr>

{# _index.html.twig#}
<table>
    {% for entity in entities %}
        {% include _index_row | default('_index_row.html.twig') %}
    {% endfor %}
</table>

{# index.html.twig #}
{% extends layout | default( 'some_layout.html.twig') %}

{% block content %}
    <div>
        {% render listAction with template =  _index | default('_index.html.twig') %}
        {% block foobar %}{% endblock %}
    </div>
{% endblock %}
```

so if we need to override actions block we can use:
``` twig
{# _other_index.html.twig #}
{% set _index_row = '_other_index_row.html.twig' %}
{% extends '_index.html.twig' %}

{# _other_index_row.html.twig #}
{% extends '_index_row.html.twig' %}

{% block actions %}{% endblock %}
```

It's possible by using bundle/extension that allows us to override templates in route definitions. We end up with more files but they're very short and clean.

**Comment by LionsAd** [comment]
Why don't we create a twig preprocessor that literally includes the source instead of including the template as something that is called? Would that not solve this problem automatically?

PS:

Hi from DrupalCon

**Comment by hecht-software** [comment]
I think there should be two different keywords for

1. render another template and include the output (this what `include` currently does)
2. include the source of another twig file

The second case is often needed when the base layout is split into multiple fragments, e.g. separate twig files for header, sidebar, footer and body.

**Comment by stof** [comment]
if you want to import block definitions from another template, there is ``{% use %}`` for that.

Importing arbitrary source would not be possible, as Twig would not know what it should do with them (where should it display it ?)

**Comment by hecht-software** [comment]
The second include can be substituted / replaced by the content of the included file internally.

So if I have one file:
`some html content {% include2 'other-twig-file.html.twig' %} some other html content`

And 'other-twig-file.html.twig' with content:
`content of other file {% someblock %}block content{% endblock %}`

Then twig should act as if the content of the first file was:
`some html content content of other file {% someblock %}block content{% endblock %} some other html content`

This would be some kind of a preprocessor-include.

No, `{% use %}` doesn't help here. I'm not talking about importing block definitions, but about separating the base layout into multiple files, because it can get very big and confusing for complex layouts.

**Comment by Shade634** [comment]
Hey im quite new to using twig, working with it for a few weeks now and i ran stuck as well as i tried to split my base layout in multiple fragments. As described above:

> The second case is often needed when the base layout is split into multiple fragments, e.g. separate twig files for header, sidebar, footer and body.

For this same simple reason:
> separating the base layout into multiple files, because it can get very big and confusing for complex layouts.

Since i am new to twig, i am a bit clueless how to achieve this now...

**Comment by stof** [comment]
@hecht-software importing some source code when find the tag is quite hard to do, because it requires changing the source and restarting the parsing (as tokens have to change due to that, and the list of blocks as well, etc...). Twig does not have a pre-processor.

If you want to build a pre-processor, you could write a custom loader (wrapping existing loaders), which would preprocess the source code before giving it to the Twig engine (be careful with the handling of cache keys then, if multiple sources are involved in the building of a single template. And give up about line numbers in error messages for templates using the preprocessor, as they would report line numbers in the output of the preprocessing). However, such kind of preprocessor was already requested in the past (I don't remember what was the exact use case), and this was rejected from the core. People wanting to write such loader can do it outside the core (and assume the drawbacks of preprocessing)
