### ISSUE TITLE
label variable not available in widget block

### ISSUE THREAD

**Issue by james-bw** [twigphp/Twig#1373]
I have tried to override the twig templates for the block so that I can use the Bootstrap 3 inline-checkbox style. However I can't get access to the 'label' variable within the block - it outputs nothing.

In my index.html/twig function I have:
```
{% form_theme form 'MyBundle:Form:fields.html.twig' %}

{{ form_row(form.my_checkbox_field) }}
```

and then in fields.html.twig I have:

```
{% block form_label %}
{% spaceless %}
    {% if label is not sameas(false) %}
        {% if not compound %}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {% endif %}
        {% if required %}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
        {% endif %}
        {% if label is empty %}
            {% set label = name|humanize %}
        {% endif %}
        {% if 'checkbox' not in block_prefixes %}
        <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>{{ label|trans({}, translation_domain) }}</label>
        {% endif %}
    {% endif %}
{% endspaceless %}
{% endblock form_label %}

{% block checkbox_widget %}
{% spaceless %}
<label for="{{ id }}">
<input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{{ label|trans({}, translation_domain) }}</label>
{% endspaceless %}
{% endblock checkbox_widget %}
```
However the HTML it outputs (sanitised slightly) is:

```
...
<label for="my_field_id">
<input type="checkbox" id="my_field_id" name="x[y]" value="1">
</label>
...
```

So as far as I can tell, you can't get access to {{ label|trans({}, translation_domain) }} from within the checkbox_widget. 

To fix this you have to include :
```
{% if label is empty %}
  {% set label = name|humanize %}
{% endif %}
```
...within the checkbox_widget.

**Comment by camburns** [comment]
I'm having the same issue, the checkbox label seems to be output between twig blocks form_rows and form_row however the label only prints when it arrives at the form_row block. It doesn't look like the checkbox label block is even held in twig blocks - I'm assuming there's some sort of hook that's preventing overidding the twig checkbox label block.

Whatever the issue is, it's incredibly annoying and I haven't been able to override the checkbox label. Any suggestions would be welcome.

P.S. my guess is that PHP hooked into twig somehow and at somepoint to override the functionality of form_row twig block in order to display the checkbox label before the input / widget label.

cheers,
Cam

**Comment by xabbuh** [comment]
@camburns The form themes are not part of the Twig core but are provided by the TwigBridge from the Symfony core. I suggest to ask your question on [StackOverflow or on IRC](https://symfony.com/support).
