### ISSUE TITLE
Case insensitive replace

### ISSUE THREAD

**Issue by smilesrg** [twigphp/Twig#1407]
There is no possibility to perform case insensitive replace in Twig using "replace" filter.

**Comment by Friksel** [comment]
This issue is 6 years old and as far as I can see there's still no way to replace case insensitive without adding own logic. Which surprises me a lot, as this is such a basic feature and IMHO we use case INsensitive replacements more than case sensitive ones.

Could there be a new filter which replaces case insensitive, or added some boolean to replace case insensitive? That wouldn't be the hardest thing to add to the filters (it's just using another PHP-function to replace), but would help a lot of people and preventing us to write own custom filters for this basic feature.

Thanks in advance!
