### ISSUE TITLE
Can't override extended twig template block to empty

### ISSUE THREAD

**Issue by chrisyue** [twigphp/Twig#1568]
http://stackoverflow.com/questions/13233476/cant-override-extended-twig-template-block-to-empty

Although the child template override some block of parent completely (without calling `parent()`), the code in parent block still get run.

**Comment by stof** [comment]
The issue here is that Assetic is building assets during the compilation of templates. and even if the parent block is overwritten, it still gets compiled. The error message even tells explicitly that the exception happens at compilation time, not when running the template:

> An exception has been thrown during the compilation of a template

@fabpot this issue should be closed
