### ISSUE TITLE
Impossible to invoke a method on a global class when the same name exists as a context variable

### ISSUE THREAD

**Issue by mfrenzel** [twigphp/Twig#1593]
### Question
What is the best way to define function within a context variable?
I tried to define global class with the same name as the context variable.
But because the global variables and the context-variables are getting merged and the context-variables are preferred, it is not possible to invoke a method on the global variable if the name of the global variable is already defined as a context-variable.

### Example
        class TwigGlobalClass {
            public function someMethod() {
                return "CALL someMethod";
            }
        }
        //---------------------------------------------------
        $context = ['user' => ["age" => "27"]];

        $twig = new TwigEnvironment();
        $twig->addGlobal('user', new TwigGlobalClass());
        $twig->addGlobal('user_global', new TwigGlobalClass());

        $twigContent = <<<EOF
        Age: {{ user.age }}
        Call user.someMethod():{{user.someMethod()}}
        Call user_global.someMethod():{{user_global.someMethod()}}
        EOF;
        echo $twig->render($twigContent, $context);
### Output
        Age: 27
        Call user.someMethod():
        Call user_global.someMethod():CALL

**Comment by stof** [comment]
There is no concept of global class in Twig, so your issue title is asking about a non-existent context. and global variables and context variables are indeed sharing the same space. The difference between them is for the code rendering the template (whether it needs to pass the variable each time or no). But inside the template, there is no difference. they are variables. There is no difference between them.
So in your case, ``user`` is an array, and there is no way to call ``someMethod`` on it. If you turn on strict variables in your Twig_Environment (and during development, you should), you will get an exception telling you there is a mistake here.

If you want to have methods on a context variable, the answer is easy, and is the same than in PHP: use an object for your variable instead of using an array

**Comment by mfrenzel** [comment]
Ahh, didn't knew that it is possible to pass objects as context-variables as well. Thanks a lot, that solved my problem!

**Comment by stof** [comment]
Well, this is exactly what you are doing for the TwigGlobalClass instance when setting the variable locally rather than in the context. As I said, all variables are the same in templates
