### ISSUE TITLE
Should improve Twig_Environment::mergeGlobals() ?

### ISSUE THREAD

**Issue by ptcong** [twigphp/Twig#1607]
Hi @fabpot 
I'm using Laravel 4 with Twigbride in a big project that get high traffics, so i'm trying to optimize it.
In my case, the method run ~60 times, and takes 5.4ms by itself (profile with xdebug)
```php
    public function mergeGlobals(array $context)
    {
        // we don't use array_merge as the context being generally
        // bigger than globals, this code is faster.
        foreach ($this->getGlobals() as $key => $value) {
            if (!array_key_exists($key, $context)) {
                $context[$key] = $value;
            }
        }

        return $context;
    }
```
Why don't you use a simpler code for this ?
```php
    public function mergeGlobals(array $context)
    {
        return $context + $this->getGlobals();
    }
```

I have try with the code, and it run with 0.7ms,
if with array_merge, it takes 0.9ms.
I'm running on PHP 5.4.34

Please correct me if i'm wrong

**Comment by barryvdh** [comment]
Looks like a good use-case for https://blackfire.io/ ;)

**Comment by SpacePossum** [comment]
@ptcong Why did you close this issue?
I threw a little script together and it seems you have point.

```php

<?php
function mergeGlobals_current(array $context, array $globals)
{
	// we don't use array_merge as the context being generally
	// bigger than globals, this code is faster.
	foreach ($globals as $key => $value) {
		if (!array_key_exists($key, $context)) {
			$context[$key] = $value;
		}
	}

	return $context;
}

function mergeGlobals_new(array $context, array $globals)
{
	return $context + $globals;
}

for($j = 0; $j <100; $j++) {

	$globals = array();
	$itemCount = rand(10, 50);
	for($i = 0; $i < $itemCount; $i++) {
		$globals[sprintf('test %d', $i)] = rand(10, 20);
	}

	$context = array();
	$itemCount = rand(100, 250);
	for($i = 0; $i < $itemCount; $i++) {
		$context[sprintf('test_%d', $i)] = rand(10, 20);
	}

	$start = microtime(true);
	$r_old = mergeGlobals_current($context, $globals);
	$end = microtime(true);
	$diff_time_1 = $end - $start;

	$start = microtime(true);
	$r_new = mergeGlobals_new($context, $globals);
	$end = microtime(true);
	$diff_time_2 = $end - $start;

	$array_diff = array_diff($r_old, $r_new);
	if (!empty($array_diff)) {
		echo "\nArray mismatch";
		die;
	}

	if ($diff_time_1 < $diff_time_2) {
		echo "new slower\n";
	} else {
		echo sprintf("new faster %f vs. %f, diff: %f\n", $diff_time_2, $diff_time_1, $diff_time_1-$diff_time_2);
	}
}

```

**Comment by ptcong** [comment]
@SpacePossum 
Because for with small project, my code is faster. 
But for bigger data, maybe @barryvdh  is right (i have not tested).
But fabpot  have comment on the code
```
// we don't use array_merge as the context being generally
// bigger than globals, this code is faster.
```
Maybe, he and others have tested more case.

**Comment by barryvdh** [comment]
So, here is a related issue: https://github.com/zendframework/zf2/issues/5716

Based on the gist Ocramius made, I re-created the testcase for this usecase. You can clone it and run it yourself: https://gist.github.com/barryvdh/0867ee38e20f82ef443a

I ran it with 4 cases, with context and globals either 10 or 100. You can see in my output that the forEach (current) is slightly faster for few globals, many context vars. For the other cases, the sum method is the fastest.

But that is just my setup. it might be different in old/newer php versions (in php 5.5 the array_merge is improved)

So the question here is, what is a common use case? And how 'common' is it, because if it changes a lot, the sum method might be better. And to note: if it's just a few variables, the speed is perhaps a bit less important because it's fast anyways.

**Comment by ptcong** [comment]
Ok, got it, thanks @barryvdh

**Comment by barryvdh** [comment]
@ptcong Stop closing this issue, I never said I didn't agree with what you say, I only said that it depends on the use case and that we should look into the different cases of the problem.

How many context vars / globals do you have? You could try the benchmark I posted also.

**Comment by ptcong** [comment]
In my case, i have 9 globals var, and 3-6 context vars, so `array plus` is faster.
But for people and big project, `foreach` is faster. 
Fabpot know it and use `foreach` to supports more people and big project.
I think he will not consider to change the old thing that he have decided.

In my use case, i extended twig and overrides some methods to improve it my myself then close the issue.

Tell me if if i'm doing a wrong.

**Comment by barryvdh** [comment]
But according to the tests, array plus isn't slower in most cases.

I've updated the tests to include some overlap, because most of the time, the context vars are different then the global vars. Unless the overlap is 100%, the array sum method is faster (probably some optimization somewhere?)

    10 globals, 10 context, 20% overlap
    Method Name                                 Iterations    Average Time      Ops/s    Relative
    ------------------------------  ----------  ------------ --------------   ---------  ---------
    arrayForeach                  : [Baseline] [1,000     ] [0.0000050101280] [199,595.69811]
    arraySum                      :            [1,000     ] [0.0000013055801] [765,943.02411] [26.06%]

    10 globals, 100 context, 20% overlap
    Method Name                                 Iterations    Average Time      Ops/s    Relative
    ------------------------------  ----------  ------------ --------------   ---------  ---------
    arrayForeach                  : [Baseline] [1,000     ] [0.0000082199574] [121,655.13241]
    arraySum                      :            [1,000     ] [0.0000047950745] [208,547.33492] [58.33%]

    100 globals, 100 context, 20% overlap
    ------------------------------  ----------  ------------ --------------   ---------  ---------
    arrayForeach                  : [Baseline] [1,000     ] [0.0000376286507] [26,575.49453]
    arraySum                      :            [1,000     ] [0.0000086789131] [115,221.80100] [23.06%]
    
    20 globals, 1000 context, 90% overlap
    Method Name                                 Iterations    Average Time      Ops/s    Relative
    ------------------------------  ----------  ------------ --------------   ---------  ---------
    arrayForeach                  : [Baseline] [1,000     ] [0.0000527508259] [18,957.04917]
    arraySum                      :            [1,000     ] [0.0000468513966] [21,344.08093] [88.82%]

See the gist for more results.

Depending on the use case, it seems that an improvement of 4x is possible..

@fabpot what do you think? Or am I making a mistake in my benchmarks/assumptions?

**Comment by fabpot** [comment]
Looks interesting, can you include in your test `array_merge` as well? I think this is what we used before (that would confirm the cause of the change back then). Thanks.

**Comment by barryvdh** [comment]
I had that first, but array_merge was almost always slower then sum. Added it back:
https://gist.github.com/barryvdh/0867ee38e20f82ef443a#file-output-txt

For few globals, many context, the `array_merge` is indeed slower then foreach.

    10 globals, 100 context, 20% overlap
    Method Name                                 Iterations    Average Time      Ops/s    Relative
    ------------------------------  ----------  ------------ --------------   ---------  ---------
    arrayForeach                  : [Baseline] [1,000     ] [0.0000083165169] [120,242.64664]
    arraySum                      :            [1,000     ] [0.0000047922134] [208,671.84080] [57.62%]
    arrayMerge                    :            [1,000     ] [0.0000110158920] [90,777.94130] [132.46%]

    20 globals, 1000 context, 90% overlap
    Method Name                                 Iterations    Average Time      Ops/s    Relative
    ------------------------------  ----------  ------------ --------------   ---------  ---------
    arrayForeach                  : [Baseline] [1,000     ] [0.0000520675182] [19,205.83185]
    arraySum                      :            [1,000     ] [0.0000454032421] [22,024.85888] [87.20%]
    arrayMerge                    :            [1,000     ] [0.0001165008545] [8,583.62803] [223.75%]

But note that this is 5.4. In 5.5.6 the performance is improved:
> Improved performance of array_merge() and func_get_args() by eliminating useless copying. (http://php.net/ChangeLog-5.php)

**Comment by SpacePossum** [comment]
@ptcong thanks for the additional info and thanks @barryvdh for the benchmark!

Looking at Twig code I think the use case differs through out, since the merge is not only done at template rendering (where I would expected more context then globals), but also for macros (where I would expected less difference in amount of variables in the arrays, but then again macros are used less often the templates (I think)).
I run the tests and the results are about the same as @barryvdh (Debian 6.0.10 and Ubuntu 12.04)

For what is worth I took two same samples form a project:
called 174 times
globals > context  68
context > globals 106
diff between 4 and 12

called 132 times
globals > context 88
context > globals 44
diff between 0 7

Would using templates `includes` `with {} only` decrease the number of context variables making it more likely for the `globals` to outnumber the `context`?

**Comment by barryvdh** [comment]
I tried this using the twig-perf repository, but I can't really get clear results. They are almost the same for both cases (some a fraction faster, some slower, but on another run it could be switched). So hard to tell what the 'real life' improvement would be.

There are also some array_merge() uses for blocks in the template, might also be benefitial to improve.

**Comment by acasademont** [comment]
This is interesting, could it be reopened? Right now Twig's mergeGlobals is one of the most time  consuming methods according to Blackfire
