### ISSUE TITLE
[DX] Throw exception when using conditionals outside of blocks in a template extending another

### ISSUE THREAD

**Issue by SpacePossum** [twigphp/Twig#1639]
When using a setup like:

```twig
{# main.twig #}
{% set test = false %}

<h1>Hello</h1>

{% block dialog %}
    dialog base
{% endblock %}
```
```twig
{# test.twig #}

{% extends 'main.twig' %}

{% if false and test %}

    {% block dialog %}
    
        dialog override
        
        {% if test == true %}
            test is true
        {% else %}
            test is false
        {% endif %}
        
    {% endblock %}

{% endif %}
```

The output is:

```twig


<h1>Hello</h1>

    dialog override

        test is false
```

This is confusing. When printing anything in the extending template outside of the `block` a syntax exception is thrown like: `A template that extends another one cannot have a body in "test.twig" at line 19.`. I think an exception should be thrown as well when using conditionals outside of `blocks`.
Fiddle @ http://twigfiddle.com/818v58

**Comment by ninsuo** [comment]
Hello,

In some cases, that's useful to put conditions outside blocks, for example, to import macros conditionally:

```jinja
{% if isMobile %}
    {% import 'mobileMacros.twig' as macros %}
{% else %}
    {% import 'desktopMacros.twig' as macros %}
{% endif %}
```

This will compile as:

```php
if ((isset($context["isMobile"]) ? $context["isMobile"] : null)) {
    // line 5
    $context["macros"] = $this->env->loadTemplate("mobileMacros.twig");
} else {
    // line 7
    $context["macros"] = $this->env->loadTemplate("desktopMacros.twig");
}
```

Then, you can use your `macros` in all blocks without importing macros in each blocks.

**Comment by SpacePossum** [comment]
Hello @ninsuo,

Thank you for making TwigFiddle! It is really a great tool and helped me a lot :+1:
And thank you for you reply. Your example shows a valid case against my suggestion to always throw an exception. I didn't consider all options and jumped to conlusions,
Looking at the compiled source you added I wonder why a similar setup doesn't work for `blocks` as it does for `macros`. I'm puzzled about the way and when conditionals are checked in Twig. For example this doesn't run as well:

```twig
{% set test = false %}
{% if test %}
    {{ 'test'|myDebugFunction }}
{% else %}
    no test
{% endif %}
```

I'll try if I can find more and get back to this issue

**Comment by ninsuo** [comment]
Thank you, I did twigfiddle as a twig enthusiast, stackoverflow addict and passionate developer. I'm always happy to learn that my work helps the community.

About your first question, both `blocks` and `macros` tags are compiled as methods of the template class, not as body of the `doDisplay`'s method. The `import` tag just imports a template object and put it in the context.

About your second question, templates that extends others can only overwrite blocks from the parent template, and your `{{ 'test'|... }}` as well as `no test` are bodies (understand: `echo`ed by the compiled template) outside blocks.
It makes no sense to display text outside blocks because Twig takes your base layout and overwrites existing blocks using children blocks with the same name. Where would the children's outside-block text be rendered?

**Comment by SpacePossum** [comment]
Hi, thanks again. I agree about not rendering outside blocks of childeren. I do find it confusing that block overrides in childeren cannot be done within if statements and don't cause syntax errors when trying to.

Another example: http://twigfiddle.com/clwgps
This one doesn't work, but changing the first check to true does. This is because the block dialog gets  overriden no matter what the if statement is, but the import is only done with the statement is true.

```twig
{# test.twig #}

{% extends 'main.twig' %}

{% if false %} {# Toggle to true will work #}
    {% import 'mobile.twig' as macros %}    
    {% block dialog %}
        {{ macros.input() }}
    {% endblock %}
{% endif %}
```

```twig
{# main.twig #}
{% set isMobile = false %}

<h1>Hello</h1>

{% block dialog %}
    dialog base
{% endblock %}
```

```twig
{# mobile.twig #}
{% macro input() %}
    mobile
{% endmacro %}
```

The second example I provided about conditions doesn't have to do with childeren at all;
http://twigfiddle.com/bwxkx8
Twig seems to look for the debugFilter even if it isn't called.

**Comment by ninsuo** [comment]
About the 1st example, I understand that this is a bit confusing. By default, compiler writes any instructions in the `doDisplay` method (`if`, `import`), except for `macro` and `block` because macros and blocks are written as class methods. So the behaviour you're not expectig is that your child blocks will overwrite your parent blocks, even if they are located inside a `false` condition.

In this case, you are compiling:

```php
    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 5
        if (true) {
            // line 6
            $context["macros"] = $this->env->loadTemplate("mobile.twig");
        }
        // line 3
        $this->parent->display($context, array_merge($this->blocks, $blocks));
    }

    // line 7
    public function block_dialog($context, array $blocks = array())
    {
        // line 8
        echo "        ";
        echo $context["macros"]->getinput();
        echo "
    ";
    }
```

As you can see, your `block` is still overwriting your parent block, where your `import` is written in the `doDisplay` method.

About the 2nd example, you can see that this is a `Twig _Error_Syntax` exception, not a `Twig_Error_Runtime`. This means your filter is resolved at parsing time, and `if` statements are not yet interpreted.

**Comment by SpacePossum** [comment]
Thank you for the inside information :)

Do you think it possible to change the block overload mechanics?
For example about the first case; now I do something like this:

```twig
{# child.twig #}
{% block dialog %}
     {% if some_check %}
          import needed macro
          Child override content including macro call
     {% else %}
          parent()
     {% endif %}
{% endblock %}
```
Would this the best solution?

You made the second example clear, I just have to  always load the filter even if it is not used at runtime.

**Comment by ninsuo** [comment]
I do not know what you're exaclty trying to achieve exactly but this code makes sense to me.

**Comment by SpacePossum** [comment]
https://github.com/twigphp/Twig/issues/1685#issuecomment-102837802
