### ISSUE TITLE
Trying to access global variable

### ISSUE THREAD

**Issue by misilot** [twigphp/Twig#1643]
In my twig template I have the following:

```twig
{% extends "base.html.twig" %}

{% set departmental_charge_id = '-1' %}

{% block content %}
    {% set departmental_charge_id = '4' %}
{% endblock %}

{% block javascript %}
    {{departmental_charge_id}}
{% endblock %}
```

The output is -1 and not 4 which is what I would expect.

Thanks!

**Comment by ninsuo** [comment]
Hello,

Twig variables are not passed by reference to block methods, so basically this is by design not possible to do what you want.

But in your context, you can create a `\stdClass` and put your data inside, such as:

```php
   // someController.php
   $globals = new \stdClass();
   $globals->departmental_charge_id = -1;
   $twig->render("someView.html.twig", array('globals' => $globals);
```

And later in your Twig code:

```jinja
{% extends "base.html.twig" %}
{% block content %}
    {% set globals = globals|merge({departmental_charge_id: 4}) %}
{% endblock %}

{% block javascript %}
    {{globals.departmental_charge_id}}
{% endblock %}
```

BTW, consider not implementing business logic in your view. Your design will not follow MVC if you begin to update twig variables this way.

**Comment by ninsuo** [comment]
Hmm, in fact, i'm not even sure this will work as `globals` will be casted to an array.
