### ISSUE TITLE
CSS escaping does not work in Firefox

### ISSUE THREAD

**Issue by mnpenner** [twigphp/Twig#1649]
This Twig:

```twig
<label class="client-list-filter label-color-box" style="color:{{ label.text_color|e('css') }};background-color:{{ label.bg_color|e('css') }}">
```

Generates HTML like:

```html
<label class="client-list-filter label-color-box" style="color:\23 FAE0FD;background-color:\23 871991">
```

This renders fine in all browsers except Firefox.

I'm not entirely sure of how CSS escaping is intended to behave (couldn't find any examples in the docs), but I assume it should work for property values?

~~Is it necessary to escape so many characters? Perhaps it can be relaxed a little to only escape semi-colons, and perhaps ensure strings and comments are terminated correctly?~~

**Comment by SpacePossum** [comment]
Hi,
Espacing with one option, like `label.text_color|e('css')` won't stop the auto escaping (`html` in this case). Maybe this is what is happening here? Please try `text_color|e('css')|raw` (but be careful with security etc.).
More information can be found here:
http://twig.sensiolabs.org/doc/filters/escape.html
Somewhere around the line `When using automatic escaping,` 

(to bad there are no id's set in the doc's so linking to this paragraph cannot be done)

**Comment by mnpenner** [comment]
@SpacePossum Running it through `|raw` after didn't change the output. Also, it *is* still within an HTML context, so it *should* be both CSS and HTML-escaped, no?

Not that it should matter here. `#` is both CSS and HTML safe as far as I'm aware.

**Comment by ninsuo** [comment]
Hello, 

`#` is a special char in CSS, used when applying styles on ids. So it should be escaped to prevent at least syntax errors, and of course potential unwanted changes. This is the same thing for `.`, `[`, `]`, `:`, `>` and all CSS selectors symbol.

For example:

```html
<style>
#{{ user.given.id}} {
  /* ... syntax error if user.given.id contains a "#" */
}
</style>
```

And as soon as you are in an attribute (`style="(...)"`, it is of course important to also escape quotes (`'`) and double quotes (`"`) in order to prevent html injections, and we also need to escape `(` and `)` to avoid using css's `url()` and calling a malicious url...

So **yes**, it is necessary to escape so much characters, in order to prevent anything that could exploit the CSS syntax. And unfortunately, `#` is safe for colors, but can be exploited otherwise.

But to fix your issue, you can apply some Twig logic: 

Replace: `{{ label.text_color|e('css') }}` by:

```jinja
{% if label.text_color|slice(0, 1) == '#' %}#{{ label.text_color|slice(1)|e('css') }}{% else %}{{ label.text_color }}{% endif %}
```

Or for cleanness, use a macro:

```jinja
{% macro cssColor(color) %}
{% spaceless %}
    {% if color|slice(0, 1) == '#' %}
        #{{ color|slice(1)|e('css') }}
    {% else %}
        {{ color }}
    {% endif %}
{% endspaceless %}
{% endmacro %}
```

```html
<label class="client-list-filter label-color-box" style="color:{{ _self.cssColor(label.text_color) }};background-color:{{ _self.cssColor(label.bg_color) }};">
```

Demo: http://twigfiddle.com/wvkr2m

**Comment by mnpenner** [comment]
@ninsuo I didn't think about using it in the selector; that makes sense then. Thank you for the example code.

However, now I'm wondering if there should be different escapers for CSS selectors vs CSS property values?

**Comment by stof** [comment]
@mnpenner we would indeed need a different escaping strategy for this case

**Comment by Tobion** [comment]
This bug ticket can be closed then. Feel free to make a new feature request with different escaping strategies.
