### ISSUE TITLE
Great demand for ucfirst.

### ISSUE THREAD

**Issue by Boycce** [twigphp/Twig#1652]
There has been a great demand for `ucfirst` which has been ignored several times in partial support to the filters `capitalize`, `title`, etc. #764 #1576

The fact that it changes every character instead of just the expected character causes misleading ideas from devs coming from JS and PHP at least.
Asked to formulate our own custom twig extension does not help this project evolve.

I commend these filters
---
```
{{ 'HelloWorld'|lcfirst }}
{# outputs 'helloWorld' #}

{{ 'hello world!'|ucfirst }}
{# outputs 'Hello world!' #}

{{ 'hello world!'|ucwords }}
{# outputs 'Hello World!' #}
```

**Comment by reFX-Mike** [comment]
lcfirst = never heard about any demand for that. Ever.
ucfirst = capitalize
ucwords = title

There is no "demand" you speak of. You're unhappy or see demand for a version that doesn't use PHP internal functions, to basically avoid the bugs of the PHP implementation, but it's super easy to write your own filters if you really need it, so I really fail to see the "demand" here.

**Comment by jvasseur** [comment]
The capitalize and title filters are useless in situations were acronyms can be used because they lower all characters except the first.

A filter that have the same behavior of php functions would be really helpful for those situations.

**Comment by reFX-Mike** [comment]
1) ucwords. lcfirst and ucfirst DO NOT work with strings that contain non-ansi characters. So unless you can guarantee that the content of whatever you're rendering is strictly only ansi, using ucwords, lcfirst and ucfirst won't help you. At all.

2) For the case were you really want it and don't care about compatibility with the rest of the world, simple add __ONE LINE OF PHP-CODE__ for each of the filters and you're done.

$twig->addFilter(new \Twig_SimpleFilter('ucfirst', 'ucfirst'));
$twig->addFilter(new \Twig_SimpleFilter('lcfirst', 'lcfirst'));
$twig->addFilter(new \Twig_SimpleFilter('ucwords', 'ucwords'));

**Comment by jvasseur** [comment]
Except twig could provide a filter with the same behavior as ucfirst but without the problems of the PHP implementation.

**Comment by reFX-Mike** [comment]
This is out of Twig's scope. I think you underestimate the complexity of the problem. You are only interested in a solution to your specific problem (English text), but the real problem is that every language has it's own delimiters, it's own exceptions and edge-cases.

Think of e.g. names like "King Henry the VIII". You surely want the "VIII" to be left alone, right?
What about "Ronald McDonald"? You surely don't want it converted to "Ronald Mcdonald".
Or "Scarlett O'Hara"?

Now these are just a few examples (there are __many__ more cases that I haven't even touched upon) and you can see that it's more complicated than you think.

Now imagine this for other languages. Every single one of them has other rules, other exceptions and not all of them are compatible with each other. You capitalize something that shouldn't and we're back to square one.

There is a very good reason that the PHP-coders haven't "fixed" their functions, yet. It's too complex and impossible to get it right. So they left it alone because it's good enough for 90% of the cases.

**Comment by jvasseur** [comment]
>Think of e.g. names like "King Henry the VIII". You surely want the "VIII" to be left alone, right?
>What about "Ronald McDonald"? You surely don't want it converted to "Ronald Mcdonald".

And the problem is that's what twig is currently doing making twig filters unusable in a lot of cases.

What i think would be more useful is a filter that capitalize the first letter of a string and left everything else untouched. Something with no "magic" involved will be more reliable that something that try to fix things that are fine.

**Comment by reFX-Mike** [comment]
{{ foo[0:1]|upper ~ foo[1:] }}

Does exactly what you describe. Only "upper" the first character, leave the rest as is. No need for an extra filter.

**Comment by ninsuo** [comment]
With a runnable demo: http://twigfiddle.com/rsl89m

**Comment by reFX-Mike** [comment]
You can even save one more character ;)

{{ foo[:1]|upper ~ foo[1:] }}
