### ISSUE TITLE
The strategy of checking template cache may not work

### ISSUE THREAD

**Issue by ouyangde** [twigphp/Twig#1674]
In practice, we can't make sure every templates be cached before we starting change any of them.

For example:
0. We have a page, called A, which used a template, called B.
1. Modify B and publish it.(Note that we publish a file with it's timestamp preserved)
2. Modify B again, but do not publish.
3. Access A.
4. Publish B.
5. Access A again, now it still renders old content of B.

**Comment by stof** [comment]
Well, if you have a template loader allowing to publish templates only later than modifications, you should make ``isFresh`` of the loader take the publication date into account, not the modification date.

And note that if you don't set the ``auto_reload`` option to ``true``, Twig will never check whether the cache is outdated. It will use the cache when it exists (this improves performances when you can afford clearing your cache after changing templates, for instance because templates never change between deployments)

**Comment by ouyangde** [comment]
But our codes should not care about there publication date, and filesystem doesn't have publication date  stored in each file.

Smaty stored modification date when generate each cache file,  I know its poor performance. Is there any solution other than clearing cache after deployment?

**Comment by stof** [comment]
@ouyangde wait, what does ``publish`` mean ? Is it a deployment of the modified code, or an action in the application to tell it to use the new version of the template ?

**Comment by stof** [comment]
and IMO, clearing cache when deploying is a good idea, as a deployment might also change other things impacting the cache anyway.

**Comment by ouyangde** [comment]
@stof  It takes the former meaning. 

And thank you for your advices, I have used clearing method for over 2 months, and everything is OK. But only worry that I may forgot to apply this strategy on new projects.

**Comment by stof** [comment]
@ouyangde just make cache clearing part of your deployment process :smile:
