### ISSUE TITLE
Double escaping when using custom esaper

### ISSUE THREAD

**Issue by Koc** [twigphp/Twig#1689]
I need create custom escaper which would replace `'` with `\'` and call `html_attr` escaping for processed string.

``` php
<?php

namespace Metal\ProjectBundle\Twig;

class AngularEscaping extends \Twig_Extension
{
    public function initRuntime(\Twig_Environment $environment)
    {
        $environment->getExtension('core')->setEscaper('angular', array($this, 'angularEscaping'));
    }

    public function angularEscaping(\Twig_Environment $environment, $string, $charset)
    {
        $string = str_replace("'", "\\'", $string);

        return twig_escape_filter($environment, $string, 'html_attr', $charset);
    }

    public function getName()
    {
        return 'angular_escaping';
    }
}
```

``` php
`$a = "'4"`
```

``` twig
{{ a|replace({"'": "\\'"})|escape('html_attr') }}
{# &#x5C;&#x27;4 - as expected #}

{{ a|escape('angular') }}
{# &amp;#x5C;&amp;#x27;4 - automatic html escaping goes after my custom escaper #}
```

**Comment by Koc** [comment]
As workaround I can replace escaping callable with
```php
    public function angularEscaping(\Twig_Environment $environment, $string, $charset)
    {
        $string = str_replace("'", "\\'", $string);

        return new \Twig_Markup(twig_escape_filter($environment, $string, 'html_attr', $charset), $charset);
    }
```
buy it looks buggy. As I see we have similar problem some time ago https://github.com/twigphp/Twig/pull/1211

**Comment by stof** [comment]
@Koc this is because the code escaped as ``angular`` is not considered as safe for the ``html`` context, while the ``html_attr`` escaping is (as we know it is a stricter escaping than ``html``).

A simple solution for your case would be to use a dedicated filter instead:

```php
<?php

namespace Metal\ProjectBundle\Twig;

class AngularEscaping extends \Twig_Extension
{
    public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter('escape_angular', array($this, 'angularEscaping'), array('is_safe' => array('html_attr'), 'needs_environment' => true)),
        );
    }

    public function angularEscaping(\Twig_Environment $environment, $string)
    {
        $string = str_replace("'", "\\'", $string);

        return twig_escape_filter($environment, $string, 'html_attr');
    }

    public function getName()
    {
        return 'angular_escaping';
    }
}
```

```jinja
{{ a|escape_angular }}
{# &#x5C;&#x27;4 - as expected #}
```

Making Twig aware that the ``angular`` context is already escaping as ``html_attr`` (and so as ``html``) would be much more complex (Twig does not have such extension point)

**Comment by Koc** [comment]
Of course, I have created custom filter first. But if Twig has possibility to create custom escapers - code was rewrited to using it ;). Imho we can add third argument `$isSafe` to `Twig_Extension_Core::setEscaper`.

**Comment by stof** [comment]
@Koc creating custom escaper is indeed supported. But Twig does not fully support registering a context as being safe for another context (currently, there is an hardcoded support for ``html_attr``).

Doing it in ``Twig_Extension_Core::setEscaper()`` may not be the right place to register that, because this inheritance info is about the autoescaping, which is implemented in a different layer in Twig.

**Comment by fabpot** [comment]
As there is a "workaround", I propose to close this as the use case is quite rare.
