### ISSUE TITLE
registerUndefinedVariableCallback for lazy loading stuff

### ISSUE THREAD

**Issue by bestis** [twigphp/Twig#1692]
Hi,

Imagine situation that we have object, that has magic __get that will load stuff when requested and that takes time. We give that object to twig's variables, let's call it "document". Now using those in templates would be:
{{ document.otherdocumens }}
But that's not so nice versus:
{{ otherdocuments }}
We have populated those document's attributes to twig so we can use the shorter version, but now noticed that we load a lot of stuff we don't need to. So using those on demand as lazy loading would be nice.

Twig seems to have registerUndefined for filters and functions, but no for variables, which is shame, that it would solve my problem. The example is much simplified, but it should demonstrate the idea.

I found following: https://github.com/wgm/cerb6/commit/414f7dc0c62abbe2280d4c75185b14386482fe1d#diff-d16c52b8021897dcac3f313322fb4a0e

But it would be much better if this function would be on twig itself. So in what version I can expect this feature to be included? :)

And I haven't tested that cerb6 implementation, but it would be important to be able to access context in that function which get called, so that the function could use context to figure out what to give or is it really undefined.

**Comment by bestis** [comment]
Other idea I had, was to make own template class and then use strict_variables, to getContext called, but then getContext is final and "This is not a way to override the way to get a variable value.". What is then?

**Comment by bestis** [comment]
Ah. Wasn't able to archive what I was trying without patching twig :( Maybe best one was doing own Template class that had getVariable method and following patch:
```
--- twig/twig/lib/Twig/Node/Expression/Name.php 2015-04-19 11:30:27.000000000 +0300
+++ twig.patched/twig/lib/Twig/Node/Expression/Name.php 2015-05-19 15:18:05.122928136 +0300
@@ -57,7 +57,7 @@
                 ;

                 if ($this->getAttribute('ignore_strict_check') || !$compiler->getEnvironment()->isStrictVariables()) {
-                    $compiler->raw('null)');
+                    $compiler->raw('$this->getVariable($context, ')->string($name)->raw('))');
                 } else {
                     $compiler->raw('$this->getContext($context, ')->string($name)->raw('))');
                 }
```

But I think that there is use cases for this and it would be nice to see if Twig would support it, in someway.

**Comment by Tobion** [comment]
Instead of injecting the real other documents, just inject a proxy for `otherdocuments` that does lazy loading of the stuff. No need to create magic in twig for something that can be solved at a different layer.

**Comment by bestis** [comment]
Tobion, Yes, but then our front-end developers don't like that they always have to use:
{{ otherDocuments.attribute }}

Also templates can be used better if they don't have something like that, as we also could include the document with given variables, so that some template that has {{ attribute }} is included:
{% include 'template.twig' %}
{% include 'template.twig' with {'attribute': myValue} %}

**Comment by michanismus** [comment]
I would really appreciate a undefinedVariableCallback or the removal of "final" definition of getContext function to override the method in own Template classes.
What I am trying to do is to access DI services and I dont want to use registerGlobals() function because it will end up in useless memory consumption. I guess the easiest solution would be the removal of final definition of getContext().

**Comment by fabpot** [comment]
As explained in the phpdocs, the `getContext()` method is just an implementation detail and it's not always called to get a variable value. As the logic to get a variable value is already quite heavy, we won't add any other fallback mechanism in core.

Moreover, there are other ways to fix that locally as explained by @Tobion

**Comment by fabpot** [comment]
As a matter of fact, I've decided to remove this `getContext()` method in 2.0 to avoid any confusion (see #1726).

**Comment by bestis** [comment]
"As the logic to get a variable value is already quite heavy, we won't add any other fallback mechanism in core."

Any other? So there's already some fallback way for variables? What is it?

And how would that fallback method impact performance in normal cases or make it heavier? Does people have a lot of undefined variables in their templates? As it should not add any overhead if variables are defined. Looking at #1726 there is isset, array_key_exists and the getContext with different name. There still could easily be for example method_exists check that is there implementation of undefined variable.. so are we calling it or notFound. And even if notFound is just because the language, I can't see that being a reason not to have that undefined callback. So impact would be one more if, to check setting or does method exists to variables that are undefined. Or is there some other impact that I can't understand? As that impact doesn't sound bad at all.

**Comment by jstanden** [comment]
I wrote the basic `registerUndefinedVariableCallback` implementation referenced above for [jstanden/cerb](https://github.com/jstanden/cerb/) (~8 years ago).

I'm still having to implement that hack when we update Twig, and it has singularly prevented us from being able to use Composer to manage the Twig dependency.

For some context, we built a bot/automation scripting language on top of Twig (w/ attribution): https://cerb.ai/docs/bots/scripting/

We have a key/value dictionary class for lazy-loading complex graph relationships as a flat tree of hierarchal placeholders.

For instance, if the script is running against a support "ticket", we can use placeholders like `{{ticket_first_message_sender_org_sla_expires}}` to grab values from **Ticket >> First Message >> Sender >> Org >> SLA**. Those branches only expand as they're lazy loaded, but can expand to any depth and relationship. Clients can add their own record types and fields.

We're also using that approach in our search and reporting query grammars, for adding dynamic values to YAML documents, etc.

We had considered passing in an object like `dict` or `vars` and using dot-notation, but I agree with @bestis  that it made the syntax ugly for everyone. The whole reason we went with a flat dictionary key space was to avoid object hierarchies for template designers.

A query like `id:{{current_user_id}}` is clean even to non-programmers, and something like `id:{{vars.current_user_id}}` adds unnecessary verbosity/complexity to every single placeholder. We already know we're referring to a variable because we wrapped it in `{{..}}`. The extra parent object is just inviting mistakes.

We don't actually pass any static context/values to Twig for a template. Our undefined variable callback handles everything. I'll admit that it's an unconventional use of Twig, but it has worked really well at scale for nearly a decade. There may be other pitfalls from newer design choices in Twig 2.x or 3.x, but they don't exist in 1.x.

I'd still love to see an official implementation of, or alternative to, `registerUndefinedVariableCallback`. Every other aspect of Twig is so extensible. The key/value store itself is such a fundamental part of a template language.

**Comment by jstanden** [comment]
The Twig 3.0.2+ version of my `registerUndefinedVariableCallback()` patch is at:
https://github.com/jstanden/Twig/commit/9a8091fead085c8fad6b6e7ade90958227042c78

I just verified this works with 3.1.1 as well.

It's pretty trivial to implement. As I mentioned above, we haven't seen any side effects in 8+ years with our usage.

We currently have to load Twig from a custom repository in Composer to maintain this.
