### ISSUE TITLE
Disable escaping in form_row or form_widget

### ISSUE THREAD

**Issue by AlaeddineMessadi** [twigphp/Twig#1808]
I'm trying to print a field using `form_row()` without autoescaping `|raw`
autoescaping is already enabled in the project, I want to disable it only in the search field

the form:

```
// $builder ...

    /** @Ignore */
     $placeholder = '&#xf142;';

     $builder->add('query', 'search', [
        'required' => false,
        'attr' => [
           'placeholder' => $placeholder
         ],
        'label' => 'search'
     ]);
```
I am using `{{ form_rest(form) }}` to print all the fields, but I want to disable autoescaping only on search which is the last field.

This is what I tried but it doesn't work:

``` {{ form_row(form.query)|raw }} ```

I tried `{{ form_row(form.query|raw) }}` also

**Comment by SpacePossum** [comment]
Are you sure its Twig that is escaping the output of the `form_row` function, or is `form_row` returning escaped content itself?

**Comment by stof** [comment]
Well, disablign escaping opens an CSS hole, and it is a BC break, because the string would then be expected to contain valid HTML (so ``'a & b'`` would become an invalid value for instance).

so this won't be done.
Use the UTF-8 character you need instead of passing an HTML entity, so that the string actually contain the placeholder you want.

``|raw`` indeed does not work for the way you try to use it, because this is not where the escaping happens at all

**Comment by AlaeddineMessadi** [comment]
As all pages are UTF-8, I changed the escaping sequence with byte sequence
from `$placeholder = '&#xf142;;' to``"\xEF\x85\x82"` and it works.

I would say that if the `|raw` filter could be applied in in the `form_row` one day, it would be nice :)

**Comment by stof** [comment]
@AlaeddineMessadi applying raw on form_row is useless: the function is already safe (it returns HTML). But inside this HTML, it escapes the different values being displayed (otherwise it would be a huge XSS hole), and this is where you would have to mark the value as safe for your use case (except that your feature request is actually asking to open an XSS hole and so would be rejected).
It looks to me that you don't understand auto-escaping.

**Comment by AlaeddineMessadi** [comment]
I understand you. Thanks for the clarification
