### ISSUE TITLE
BC Issue with 1.22 [Logic Exception] Cache can only be string, false or a Twig_CacheInterface implementation

### ISSUE THREAD

**Issue by Kristianwiley** [twigphp/Twig#1851]
[LogicException] 
Cache can only be a string, false, or a Twig_CacheInterface implementation.

Began getting this error after running a composer update which pulled in the latest 1.22 build. No code was changed between versions.

Reverting back to 1.21 build resolves the issue.

**Comment by stof** [comment]
I suspect ``null`` is being passed here because of using such configuration in Symfony:

```yaml
twig:
    options:
        cache: ~
```

Previously, such configuration would disable the cache, same than setting it to ``false`` because of the implementation: https://github.com/twigphp/Twig/blob/ddce1136beb8db29b9cd7dffa8ab518b978c9db3/lib/Twig/Environment.php#L231
This was already not a supported use case though.

**Comment by fabpot** [comment]
#1868 fixes this issue by re-allowing using null, but you get a deprecation notice in this case.
