### ISSUE TITLE
Embeding a text parser 

### ISSUE THREAD

**Issue by sonkengmaldini15** [twigphp/Twig#1948]
Hi, 
I want to embed a text parser called Markdown.
But when i parse my text, it returns me the text with html tags
How can i do?
PS: I use the twig template to secure my text.

**Comment by xabbuh** [comment]
Please provide more information. What exactly do you do (example code is probably useful)? What did you expect? And what happened instead?

**Comment by sonkengmaldini15** [comment]
The lib provide his how class.
I decide to parse data coming directly from database.So went i fetch  data from database, i one time do this : 
````php 
    protected function buildDomainObject(array $key)
	{

		$article = new Article();
		$article->setId($key['id']);
		$article->setTitle($key['art_title']);
		$content = MarkdownExtra::defaultTransform($key['art_content']);
		$article->setContent($content);
		return $article;
	}
`````
But went rendering it returns me html tags.

**Comment by xabbuh** [comment]
Well, your `$article` object contains HTML tags. So when it is rendered by Twig and [autoescaping is enabled](http://twig.sensiolabs.org/doc/tags/autoescape.html) it escapes some characters so that the HTML is displayed as is. You may want to take a look at the [raw filter](http://twig.sensiolabs.org/doc/filters/raw.html).

**Comment by sonkengmaldini15** [comment]
Ha thanks it works

**Comment by xabbuh** [comment]
@sonkengmaldini15 Can you close here then?
