### ISSUE TITLE
Cache path issue on Windows/IIS

### ISSUE THREAD

**Issue by kyleweishaupt** [twigphp/Twig#1951]
I just recently tried deploying a site built on CraftCMS that uses Twig to Windows Azure. The rest of the script works, but there is a fatal error when Twig tries to write to the cache. It looks like a path issue that only appears on Windows/IIS hosting. 

`[error] [exception.RuntimeException] exception 'RuntimeException' with message 'Failed to write cache file "D:\home\site\wwwroot\craft/storage/runtime/compiled_templates//c6/c6235d1e64d5ab359bc1391cecfde64d025c3099ca71702144cdc6e6d0b0d79d.php".' in D:\home\site\wwwroot\craft\app\vendor\twig\twig\lib\Twig\Cache\Filesystem.php:82`

The solution was to modify `/lib/Twig/Cache/Filesystem.php` and add the following inside the `write()` function: `$key = str_replace('/', '\\' , str_replace('//','\\',$key));`

I'm hoping this can be merged into Twig so any updates to my content management don't overwrite this change. Thanks!

Here is the MSDN link where the above solution was first presented:
https://social.msdn.microsoft.com/Forums/en-US/8458e110-aaf8-43e2-8b55-266fb8aed49f/php-permission-issues-with-craft-cms-to-azure-web-apps?forum=windowsazurewebsitespreview

**Comment by stof** [comment]
Are you configuring the cache path with a trailing ``/`` ? This might be an issue if Azure does not allow double directory separators following each other, as Twig is adding its own one between the cache path and the subpath it builds in it.

``/`` vs ``\`` should not be an issue, as PHP already handles using ``/`` on any OS since PHP 5.3

**Comment by kyleweishaupt** [comment]
I believe it's the double slash causing the issue. The mix of `/` and `\` is being handled by PHP just fine. 

I haven't specifically configured any cache path, as its handled by my content management system. If necessary I'll open an issue with Craft CMS as well. 

I dug into the Craft code and as far as I can tell it just sets the path to `craft/app/storage/runtime/cache`, without a trailing slash.

**Comment by stof** [comment]
well, what got configured in Twig is ``craft/storage/runtime/compiled_templates``, not ``craft/app/storage/runtime/cache``

**Comment by kyleweishaupt** [comment]
Oops, you're right. The path is being set as `$path = $this->getRuntimePath().'compiled_templates/';` for compiled templates.

**Comment by stof** [comment]
Then you found the issue.

**Comment by kyleweishaupt** [comment]
Is this an issue that can be fixed in Twig itself, like presented above?

**Comment by takobell** [comment]
Seems like Twig `cache` [environment option](http://twig.sensiolabs.org/doc/api.html#environment-options) should take into account whether an app has appended a trailing slash or not.

**Comment by Tobion** [comment]
`realpath` would solve the problem (not only double slash at the end, but also in the middle of the directory if you passed it like this). Doctrine cache does this: https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FileCache.php#L99
But for this you need to create the directory in the constructor already, what twig isn't doing yet.

**Comment by takobell** [comment]
> But for this you need to create the directory in the constructor already, what twig isn't doing yet.

@Tobion It could just be added here, no? https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FileCache.php#L99

**Comment by reFX-Mike** [comment]
Looks to me like a CraftCMS issue. We use IIS too and we don't have that issue that all.

**Comment by takobell** [comment]
@reFX-Mike I think it's a combination of IIS and Azure, but I disagree it's a Craft CMS issue.  The Twig `cache` environment should be graceful enough to handle if a path it is given ends in a trailing slash or not.

**Comment by reFX-Mike** [comment]
So when the caller passes an invalid path, then it's the tools job to correct it? How can this be an IIS issue? Please elaborate. It doesn't make any sense

**Comment by takobell** [comment]
Both of these are valid paths on Windows:

    D:\home\site\wwwroot\craft/storage/runtime/compiled_templates/

    D:\home\site\wwwroot\craft/storage/runtime/compiled_templates

The issues is that in the former case, Twig is blindly assuming there is no trailing slash and it gets doubled up: https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Cache/Filesystem.php#L41 and apparently IIS on Azure doesn't like that.

**Comment by reFX-Mike** [comment]
That has literally nothing to do with IIS or Azure. This has everything to do with the OS. Windows doesn't like "//" in it's paths. Linux apparently doesn't care.

Still doesn't mean it's not misconfigured. Instead of "fixing" Twig, why not simply remove the trailing slash in the configuration? Either the coder or the user blindly added the trailing slash, but somehow it's Twigs fault and it has to remove it. If CraftCMS sets the path, it has to maybe 'rtrim($path, '/') to avoid passing superfluous characters. If the user sets the path himself, then he has to omit that extra slash too. "Works on Linux" is not good enough.

You literally want somebody else to do extra work, waste their time etc. because somebody else configured a path wrong.

**Comment by takobell** [comment]
> That has literally nothing to do with IIS or Azure. This has everything to do with the OS. Windows doesn't like "//" in it's paths. Linux apparently doesn't care.

Evidence indicates otherwise.  I've tested and didn't run into any issues with double path separators on Windows 10, 8.1, 8, Server 2008 and 2012 using various IIS versions.

Additionally, for an app that's been available for 3+ years and has been installed on tens of thousands of different server configurations (Windows and Linux) this is the first time (on Azure) we've heard of the issue.

> why not simply remove the trailing slash in the configuration?

Sure, we'll add a workaround for it in the code.  Why not add a `realpath` call to Twig so a workaround isn't necessary?

> You literally want somebody else to do extra work, waste their time etc. because somebody else configured a path wrong.

No, I "literally" want to stop the next person that runs into this issue from wasting their time.  You know,  like how [Doctrine](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FileCache.php#L99) does.

**Comment by kyleweishaupt** [comment]
Of course removing the configured trailing slash is an easy workaround, but that doesn't fix the root of this problem at all. I don't understand how having the tool easily correct an extra trailing slash and produce a fully valid path is such an issue.

**Comment by stof** [comment]
> "Works on Linux" is not good enough.

Well, it looks like this issue affects only the filesystem used on Azure, not the Windows filesystem. So this is not a "Works on Linux" case.

> Why not add a realpath call to Twig so a workaround isn't necessary?

As said previously, we can't as the dir might not exist yet.
I'm OK with right-trimming it though (if they put a double slash in the middle of the path they give us, they would still be affected, but it would still be better than today).

**Comment by takobell** [comment]
> if they put a double slash in the middle of the path they give us, they would still be affected

In addition to `rtrim`ing, you could also do a couple of `str_replace` calls to take care of double slashes in the middle of the path.

**Comment by stof** [comment]
well, I'm not sure this is needed (we would have to handle backslashes too in this case, and this would complicate the code).

**Comment by takobell** [comment]
Fair enough.

**Comment by reFX-Mike** [comment]
OK. Then let me contribute something for you. Not complicated at all:

$path = rtrim(str_replace(array('//', '\\'), '/', $path), '/');

**Comment by SpacePossum** [comment]
like this https://github.com/twigphp/Twig/pull/1953 ?

**Comment by reFX-Mike** [comment]
No, that's not quite the same. Here is a fixed version:

$path = rtrim(str_replace(array('//', '\\', '\'), '/', $path), '/');

This converts all \\, // and \ to single / and then right-trims '/'.
