### ISSUE TITLE
Macro name backwards compatibility break

### ISSUE THREAD

**Issue by roberthl** [twigphp/Twig#1976]
In #1759 a check is added to prevent macros named using reserved words from being called, unfortunately this stops templates that previously had macros named using those reserved words from working - which appears to be a backwards compatibility break.

Please could we consider rolling back this check until 2.x?

**Comment by stof** [comment]
@roberthl Creating such a macro was creating a broken compiled template (as it would replace methods of the base template class with their own class). This can lead to totally broken usage of Twig. And depending on the signature of your macro, it could even lead to a fatal error in the compiled template code.

Btw, reserving such macro names was intended to be done since a very long time, but the logic building the list of reserved names was broken (building the wrong list)

**Comment by roberthl** [comment]
I understand, however unfortunately there would have been no way to know what the full set of reserved words is:
- templatename
- environment
- parent
- blocknames
- blocks
- source
- context
- attribute

Would you consider reducing the error from an exception to E_USER_DEPRECATED until 2.x?  It would also be good if we could add these to the documentation.

**Comment by stof** [comment]
@roberthl 2.x does not have reserved names anymore as we changed the way we compiled macros to forbid conflicts (but it involved breaking an edge case and so went into 2.x).
And as I said, defining a macro with such a name in Twig 1.x would break the Twig features (very hard or in more subtle ways depending on the macro signature and the name you use). Making it a deprecation would not help, as things would still be broken.
Thus, fixing this was part of a security fix (the PR you linked is the compilation of several security patches), so we won't revert it.
