### ISSUE TITLE
Unknown "endblock" tag

### ISSUE THREAD

**Issue by xxfaxy** [twigphp/Twig#1980]
I use
{% block ibox-title %}{% endblock %}
can not use -

**Comment by SpacePossum** [comment]
Hi,
From the [docs](http://twig.sensiolabs.org/doc/tags/block.html);
>Block names should consist of alphanumeric characters, and underscores. Dashes are not permitted.

So your observation is correct and a known system limitation.

**Comment by davidgorges** [comment]
I just ran into the same issue. The error message should be more clear, e.g. "invalid block name ...".

**Comment by stof** [comment]
Well, the point is that ``{% block ibox-title %}`` alone is valid. It is the same than ``{% block ibox -title %}`` i.e. creating a block named ``ibox`` with its content set by the expression ``-title`` (in which case the ``block`` tag does not expect a closing tag)

**Comment by davidgorges** [comment]
@stof while it makes sense, the behavior is somewhat unexpected.

To make things more clear, the [shortcut notation](http://twig.sensiolabs.org/doc/tags/extends.html#block-shortcuts) could require a blank space between the block name and its content. 

``{% block ibox-title %}`` would be invalid 
``{% block ibox -title %}`` would still be valid

**Comment by stof** [comment]
@davidgorges this would be very hard to implement, because spaces are optional and insignificant in Twig (there are cases where you usually use spaces to be sure that 2 things are considered as separate tokens by the lexer, but most of these cases could also use parenthesis to delimit one of the expression rather than separating them with spaces). Spaces are the mostly for readability.

**Comment by fabpot** [comment]
Closing as there is unfortunately nothing we can do to fix this easily.
