### ISSUE TITLE
Behavior of getAttribute regarding __call methods

### ISSUE THREAD

**Issue by antares993** [twigphp/Twig#1987]
Hi,

After taking a look at `Template`'s `getAttribute` method ([here](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L456)), I have noticed something weird IMO regarding the presence of a `__call` method.

Let's say I have `{{ foo.bar }}` somewhere in some template. If the value of `bar` cannot be accessed through `$foo->bar`, `$foo->bar()`, `$foo->getBar()` nor `$foo->isBar()`, if there is a `__call` method, `getAttribute` will attempt to call `$foo->bar()`.

Wouldn't it be more logical to attempt to call `$foo->bar()`, then `$foo->getBar()` and `$foo->isBar()`, as `__call` may also manage these cases?

**Comment by Tobion** [comment]
It cannot do so as there is no defined way if a call to `__call` succeeded or not. So it cannot use the alternatives.

**Comment by antares993** [comment]
There is indeed no defined way to know if it succeeded, but there is a proper way for `__call` to indicate it doesn't manage the called method: throwing a `BadMethodCallException`. Actually, from what I see [here](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L599-L602), this case is already considered, so it could be a starting point for letting a chance to `__call`: trying `bar()`, then `getBar()` if a `BadMethodCallException` is catched, then `isBar()` if another one is catched.

**Comment by lemoinem** [comment]
@tobion @fabpot I agree this would help a lot. The current implementation crashes completely in these cases and there are no ways to avert it... This renders implementation of a [Decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) (for example), much harder and much more verbose.

The definitely seems like a good choice, especially Since Twig already uses the `BadMethodCallException` to achieve a very similar goal, this seems like the best choice to provide a way to support seamless support. And it's pretty much this exception use case, as per [the documentation](http://php.net/badmethodcallexception).

If you are interested in discussing this further on or considering a tentative implementation I could easily provide a PR for you to review.

PS: This is definitely not the first time the current support of `__call` has created an issue (e.g. KnpLabs/DoctrineBehaviors#82), reconsidering it seems important to the community.
