### ISSUE TITLE
Make assistance ('get'., 'is'., ..) on method calls optional

### ISSUE THREAD

**Issue by msteltenpool** [twigphp/Twig#2031]
I understand the philosophy behind it, somewhat, I just do not wish to use it. 

My reasoning behind not wanting to use it is that it makes it that much harder to refactor code. Say I have an object with a method called 'getClass()'. In the end I always find myself tracking the last bits with a global search. If I wish to track this method down, 'getClass()' gives me far better results than 'class' (Of course proper functional tests will also help, but we aren't always that blessed).

Making this configurable I can force the use of the proper methods. I also think it's good practice that a designer knows the difference between a getter and an isser (I would even go as far as saying that it would make things more clearer for them instead of making things difficult).

**Comment by stof** [comment]
Well, allowing to disable it as a global flag would mean that you would break any template provided elsewhere and relying on the feature (for instance, the Symfony web profiler when using Symfony).
Disabling it would actually mean that you are using a different templating language (inspired by Twig).

> I also think it's good practice that a designer knows the difference between a getter and an isser

The idea is precisely that the designer does not have to care whether the backend is implementing it as a public property or as a getter or isser.

Due to the extensible nature of Twig, it would actually be possible to implement such feature in an extension though. This would be a matter of using a node visitor to replace any ``Twig_Node_Expression_GetAttr`` node by your own node which would be compiled differently. Your node visitor should have some logic to decide whether it should perform the replacement or no, to avoid the issue I mentioned above about third-party templates (detecting whether it is one of your own templates)

**Comment by msteltenpool** [comment]
I must say the entire use case of public properties slipped my mind as I rarely use them. Thanks for the concise reply and pointing me to a different approach.
