### ISSUE TITLE
Method calls

### ISSUE THREAD

**Issue by davidsteinsland** [twigphp/Twig#2039]
Given a variable `Flash` which is an instance of a class, and the following template:

```
{{ Flash.render('flash_error') | raw }}
```

This gets compiled to:

```php
echo $this->getAttribute(
    (isset($context["Flash"]) ? $context["Flash"] : $this->getContext($context, "Flash")), 
    "render", 
    array(
        0 => "flash_error"
    ), 
    "method"
);
```

Shouldn't this be compiled to something like:
```php
echo $context['Flash']->render('flash_error'); 
```
?

**Comment by stof** [comment]
the current compiled code is here to handle errors nicely instead of triggering weird PHP errors (potentially fatal ones):

- the ``Flash`` variable may be undefined, which is covered by using ``(isset($context["Flash"]) ? $context["Flash"] : $this->getContext($context, "Flash"))`` (checking with ``isset`` directly rather than using ``getContext`` directly is a performance optimization, and Twig 2 changed this to ``(isset($context["Flash"]) || array_key_exists("Flash", $context) ? $context["Flash"] : $this->notFound("Flash"))`` when allowed to remove the ``getContext`` method)
- the method may not exist on the Flash object (or it may not be an object at all)

The template compiler does not know that the ``Flash`` always exists and is an object of this type, and so needs to handle it gracefully

**Comment by davidsteinsland** [comment]
Is there a way I can tell the compiler to produce the more direct approach? Either by using a custom parser or node expression?

Because of the parenthesis around `render`, the compiler knows the `render` is a function, right? And since `render` is preceded by `Flash.`, then it *must* be an object or an array.

```php
$context['Flash']['render']();
// or
$context['Flash']->render();
```

**Comment by stof** [comment]
For the variable access, you can use a node visitor setting the ``always_defined`` attribute of this node to ``true``, which will compile it as ``$context['Flash']``.



> Because of the parenthesis around render, the compiler knows the render is a function, right? And since render is preceded by Flash., then it must be an object or an array.

yes it knows it is a method (hence the last argument of ``getAttribute`` being ``'method'``, i.e. ``\Twig_Template::METHOD_CALL``). but it does not know for sure that value stored in the ``flash`` variable is an object implementing this method.
the following template is a valid template which can be compiled (but it will fail during rendering due to the wrong value in the variable):

```twig
{% the variable could come from any place, for instance from the call to Twig_Environment::render() %}
{% set Flash = true %}

{{ Flash.render('flash_error') | raw }}
```

**Comment by davidsteinsland** [comment]
I guess I could extend the `Twig_Node_Expression_GetAttr` and check for `$type == Twig_Template::METHOD_CALL`, but seems a bit overkill just to get that optimization.

I could also short circuit the `ExpressionParser::parseSubscriptExpression()` method, but that would also be overkill.

Around line 379 of ExpressionParser.php (at the end of `if ($stream->test(Twig_Token::PUNCTUATION_TYPE, '(')) `):
```php
$node = new Twig_Node_Expression_MethodCall($node, $arg->getAttribute('value'), $arguments, $lineno);
$node->setAttribute('safe', true);
return $node;
```

Seems that I have to settle with the `getAttribute()` way.

**Comment by stof** [comment]
@davidsteinsland the fact that you call it as a method makes no guarantee on the fact that the variable is actually usable this way.
What you suggest is making Twig assume that people writing templates never make mistakes (or that they are fine with receiving a fatal error with a stack trace going into generated code without a mapping to the Twig template lines when they make a mistake). This is not the philosophy of Twig (and changing it would be a BC break btw). An error during the rendering of a template due to a bad usage of variables or other stull like that is meant to throw an exception.

**Comment by fabpot** [comment]
And don't forget that ``Flash.render()`` might mean different calls: ``Flash.getRender()``, ``Flash.isRender()``, ...
