### ISSUE TITLE
ctype_alpha needed, but not always available

### ISSUE THREAD

**Issue by ysangkok** [twigphp/Twig#2051]
Twig depends on ctype_alpha, but when running Twig from master, I encounter this error:

`PHP Fatal error:  Call to undefined function ctype_alpha() in /cygdrive/c/Users/project/progether-system/static-ui/dist/base/vendor/twig/twig/lib/Twig/Lexer.php on line 378`

As you can see I am running Cygwin. My PHP version is 5.6.21.

**Comment by SpacePossum** [comment]
that is odd, `ctype` is part of the default installed extensions on Windows (http://php.net/manual/en/install.windows.extensions.php).
Can you check if it is installed on your system?

**Comment by ysangkok** [comment]
It can be installed on Cygwin by installing the `php-ctype` package. I am reporting this as a bug since it is not mentioned in [the installation docs](http://twig.sensiolabs.org/doc/installation.html) (though I guess that page is not supposed to cover the master branch?)

**Comment by SpacePossum** [comment]
On 1.x the Lexer uses the same function so I assume you will have the same issue there.
Not sure if the maintainers want to add this package as req. to composer and/or up the docs, lets see what they say :)

**Comment by fabpot** [comment]
We do not add dependencies on PHP "core", and `ctype` is part of PHP Core (http://php.net/manual/en/ctype.installation.php).

**Comment by c960657** [comment]
@fabpot According to [this list on PHP.net](http://php.net/manual/en/extensions.membership.php), ctype is not core extension, but a bundled extension.

As mentioned in the link you posted, the extension is enabled by default. However, running non-default builds is very common. Ubuntu has split some of the extensions enabled by default into separate packages, e.g. [php7.0-xml](http://packages.ubuntu.com/yakkety/php/php7.0-xml) and [php7.0-sqlite3](http://packages.ubuntu.com/yakkety/php7.0-sqlite3). On Ubuntu, ctype is included by default, but on Alpine Linux, [php7-ctype](https://pkgs.alpinelinux.org/package/v3.5/community/armhf/php7-ctype) needs to be installed separately.

In particular, when running PHP inside Docker containers, it is relevant to reduce the number of installed packages in order to keep the containers as slim as possible.

Why not use the features provided by Composer to specify these dependencies? Adding them to composer.json is a very low-impact change that does not break anytning AFAICT. It provides a user-friendly error message in case you do not have all relevant PHP extensions installed, and it prevents dependency problems from showing up at run time.

**Comment by SpacePossum** [comment]
Polyfilling would even be more easy, especially as Twig 2.x only has a few use cases (9 function calls).
`ctype_digit` and `ctype_space` can be polyfilled relative easy, `ctype_alpha` might be more tricky.
That way the dependency would be removed completely.

**Comment by stof** [comment]
@SpacePossum as this comes from a bundled extension, reimplementing them in userland does not make sense IMO. Would you also reimplement json_encode in userland ? ext-json has the same status than ext-ctype in the PHP core (and is not even included by default in ubuntu, unlike ctype)

**Comment by javiereguiluz** [comment]
@stof what's your opinion about adding `ext-ctype` and `ext-json` in the Composer dependencies? Thanks.

**Comment by SpacePossum** [comment]
Just saying that replacing those 9 function calls to 3 diff. functions is doable as these aren't that hard in this case. Going from this scoped case to a general case of replacing `json_encode`, well I would not do it. As it is way harder than replacing a function that checks all characters in a string a digit for example.

**Comment by fabpot** [comment]
Now that Symfony polyfill supports ctype, I've added it as a dependency in both 1.x and 2.x, which fixes this issue.
