### ISSUE TITLE
hour getting

### ISSUE THREAD

**Issue by IreneArgolloDelgadillo** [twigphp/Twig#2096]
Hi, im 
the value of startTime in the bd is:
![bdfechainicio](https://cloud.githubusercontent.com/assets/11929060/17669613/4b2c0ae8-62dc-11e6-8953-c6c6a19ce81d.PNG)

but this is rendering:
![fechaindex](https://cloud.githubusercontent.com/assets/11929060/17669654/74ac3866-62dc-11e6-8920-d6a1ca983836.PNG)
and i get the time and date  in this way:
<td>{{ "now"|date("d/m/Y H:i")}}</td>
 <td>{{ testA.startTime|date("H:i") }}</td>

**Comment by fabpot** [comment]
That's probably a timezone issue. Anyway, you should use Stackoverflow for your questions as issues are only used for bugs. Thanks.

**Comment by IreneArgolloDelgadillo** [comment]
I report it here, because I was used the time zone:
 { { testA.startTime | date ( "H: i", " America / La_Paz ")} } 
It does not work as expected because it return the same value :/ , not supposed that It should return the same value of data base regardless of the time zone because it is recovering from db? :/ 
anyway, for this case, I was forced to use the date_modify function , so:
 { { testA.startTime | date_modify ( "+ 5 Hour " ) | date ( "H: i ")} }

**Comment by sstok** [comment]
@IreneArgolloDelgadillo If your database server has a different timezone this causes a conflict, and PostgreSQL actually has it's own configuration for timezones If I recall correctly.

Say your database server is configured with `America/Chicago`, and your PHP configuration with `America/La_Paz`, then the date PHP received from database is not in the same timezone.

Then when tell PHP to convert the timezone to `America/La_Paz`, it will fail because the timezone is already in the that one.
