### ISSUE TITLE
Ternary Operator DateTime

### ISSUE THREAD

**Issue by Mynyx** [twigphp/Twig#2130]
The ternary operator does not work when the expression is a DateTime variable (````foo````).

````{{ foo ?: 'bar' }}```` causes the following error:
>An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class DateTime could not be converted to string")

````{{ foo ? '' : 'bar' }}```` works

**Comment by stof** [comment]
``?:`` does not mean getting the empty string but the value of the condition (exactly like in PHP). The expanded version would be ``{{ foo ? foo : 'bar' }}``.
The ternary operator does exactly what it is supposed to do. The issue is that you are trying to display a value which cannot be casted to string.

**Comment by Mynyx** [comment]
Sorry!
