### ISSUE TITLE
"default" == 0 ?

### ISSUE THREAD

**Issue by mrohnstock** [twigphp/Twig#2172]
I stepped into confusing behavior in twig (0.9.7 - master) and can't find a way to check, if a variable is setted to `"default"`.

For example:

```
{% set my_text = 0 %}

{% if my_text == "default" %}
  my_text is "default"
{% elseif my_text == 0 %}
  my_text is "0"
{% else %}
  something else
{% endif %}
```

I thought the result would be:

```
my_text is "0"
```

but I receive, as you can see in [twigfiddle](http://twigfiddle.com/d4teao):

```
my_text is "default"
```

Why is `0` the same as `"default"`? Is this a bug or a wanted behavior?

**Comment by stof** [comment]
this is the behavior of PHP for ``==`` (when comparing a string with an integer, it casts to integer, not to string).

If you want to use the PHP ``===`` operator, use ``is same as(...)``.
Otherwise, you can also avoid mixing different types in the same variable, which will avoid reaching into such issue (a variable named ``my_text`` and containing an integer looks like a bad idea)

**Comment by mrohnstock** [comment]
great, thanks @stof, you're right :).
