### ISSUE TITLE
[Feature Request] Function to get all required variables in a template

### ISSUE THREAD

**Issue by mickadoo** [twigphp/Twig#2188]
I saw a [stackoverflow question](http://stackoverflow.com/questions/12799094/how-to-retrieve-all-variables-from-a-twig-template/) requesting a function to get all the required variables and thought it would be nice to have. In my case I didn't want to provide defaults for variables but I did want to validate that all the context was supplied. I could do this with try catch on `render()`, but I wanted to show all the required variables, not just the first missing one.

I made a function and wondered if it would be useful. I posted my code to [stack overflow](http://stackoverflow.com/a/40105067/1196369). I haven't contributed here before, but if it would be useful I could make a PR for this, otherwise you can just close this issue.

**Comment by stof** [comment]
I don't think this belongs to the core.

Btw, your implementation is flawed, because it does not deal with many cases (and dealing with all of them is quite a lot of work, which is another reason I don't think it belongs to the core).

Cases where you list a variable as required while it is not (this list may be incomplete)

- variables defined inside the template (and so they can be accessed without needing to be passed from the outside, after they are defined and as long as we don't leave the scope)
- global variables (always defined)
- special variables accessible thanks to Twig features (``loop`` inside loops, ``_self``, etc...)
- variables created by a macro import
- variables defined inside a parent template before the rendering of the block needing it
- variables inside macros (as macros don't inherit the current context but access their arguments only)
 
Cases where you are missing required variables:

- variables needed by the parent template (outside blocks, in a block not overwritten by the template or in a block calling ``parent()``)
- variables needed by an embedded template not using ``only`` (you don't enter into embedded templates)
- variables needed by an included template inheriting the current context (btw, this is why *not* merging the current context when including or embedding a template makes maintenance easier, as it avoids these 2 cases)

**Comment by mickadoo** [comment]
@stof I did think it would need some work but that's a huge list off the top of your head! I'll close this and consider making an extension. Thanks for the feedback

**Comment by rookie0** [comment]
@stof I found all output variables parse to NameExpression, so can i get all template variables by filter AST node tree with condition node is NameExpression and has attribute always_defined false?

**Comment by cwilby** [comment]
@rookie0 I'm doing something like this at the moment based on the functionality of [jinja2schema](https://github.com/aromanovich/jinja2schema/tree/master/jinja2schema).

It's still very much in development. I managed to build what I need for my application, but it doesn't cover some of the points mentioned by @stof.

https://gist.github.com/cwilby/2847624d6533585311e11cdb463e06f5

**Comment by rookie0** [comment]
@stof @cwilby @mickadoo Maybe i solved this, [twig-infer](https://github.com/rookie0/twig-infer) can u guys take a look.

**Comment by guilliamxavier** [comment]
Thank you @rookie0 (and @cwilby too)! While probably still not comprehensive, for basic self-contained templates it does the job!
