### ISSUE TITLE
Ship vendor/bin/twig-lint

### ISSUE THREAD

**Issue by dkarlovi** [twigphp/Twig#2266]
If you use Twig standalone, you don't get access to a lint command you get with Symfony. It would be great if this was available in Twig itself.

I know it's somewhat related to the config, but you could ship something which works with defaults and it would work for 99% of the users.

**Comment by stof** [comment]
The issue is that Twig itself cannot ship this linter, because it cannot access your configured Twig_Environment instance.
Creating a new instance would not work, as it would not have the extensions used in your project, and so any template using a feature coming from an extension would be reported as broken.

**Comment by fabpot** [comment]
We don't have it in Twig itself for the reasons given by @stof (that's also why we have a recipe about this).

**Comment by dkarlovi** [comment]
OK, fair enough, thanks.
