### ISSUE TITLE
[feature request] Ability to disable usage of C extension in Environment configuration

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#2274]
Right now it looks like the only way to disable GetAttr’s usage of the C extension is to write a NodeVisitor that runs this on every node:

    if ($node instanceof Twig_Node_Expression_GetAttr) {
        $node->setAttribute('disable_c_ext', true);
    }

It would be nice if there was a central place to disable it, like a setting on the Environment.

**Comment by fabpot** [comment]
What for? If you have the C extension installed, it means you want to use. It you don't want to use it, disable the C extension.

**Comment by stof** [comment]
The ``disable_c_ext`` attribute is here mostly for testing purpose, to be able to run the test with the C extension and compare the result of the execution in C and userland.
I don't see any reason to use it in prod.

**Comment by brandonkelly** [comment]
We (Craft CMS) have encountered hosts that have the C extension installed, which causes errors depending on what the templates are doing. I’m not sure whether it’s due to bugs in the extension that still exist of if they have been fixed - it’s been a while since we started seeing this and since then we have just been force-disabling the C extension even if it’s available, by hacking GetAttr.php to set the default `disable_c_ext` value to `true`.

Now we are working to move to vanilla Twig, so we need a way to disable the extension without hacking Twig code. If this FR is rejected I will go the NodeVisitor route instead.

**Comment by brandonkelly** [comment]
^ so in summary: There are hosts that have (possibly buggy) versions of the extension installed, which we and the web developer don’t have control over. To support these hosts we need to be able to tell Twig to not use the extension even if it’s available.

**Comment by stof** [comment]
There has been such bugs in the past, but they have been fixed (unless your bugs are not the same one that the bugs which have been reported to us, in which case you should report them).
If the issue is old versions of the C extension, I would rather automatically disable the usage of the C extension when detecting them (we can detect the version of the C extension easily) rather than adding a configuration setting. This way, Craft CMS could still benefit from the C extension performance for people running on a PHP 5.6 host with an uptodate extension.

**Comment by brandonkelly** [comment]
That would certainly be ideal!

**Comment by fabpot** [comment]
@stof Do you have a version of the C ext in mind that would be the minimum "acceptable" one or do you suggest that we only support the C ext that has the exact same version as the Twig PHP one?

**Comment by stof** [comment]
@fabpot we should forbid anything before 1.20 (1.20 being allowed) or before 1.26 (1.26 being allowed).
Versions between 1.20 and 1.26 are not buggy, but they trigger a deprecation warning when checking for the sandbox extension (as they access it by name rather than class name, which was changed in 1.26 when deprecating the name).

Versions before 1.20 must be forbidden as this is the last time we made meaningful changes in the extension other than this deprecation (i.e. something else than bumping the version or adding dots in exception messages), and the fix done in 1.20 was a security fix)

**Comment by fabpot** [comment]
Disabling the extension should trigger some kind of warning to the developer. Like a deprecation notice? Or something else?

**Comment by stof** [comment]
Well, I'm not sure a deprecation notice is appropriate here, but I don't see a better way if we want to make them notice it (as we don't have a logger available)

**Comment by stof** [comment]
note that the disabling based on version must be consistent between the compilation and the detection of the extension usage when generating the cache key (otherwise it breaks the logic changing the cache key when the compiled template uses the extension)

**Comment by reFX-Mike** [comment]
Is this still useful? Especially with PHP 7 the performance difference seems to be negligible and thus it should be considered to abandon the C-extension altogether.

**Comment by stof** [comment]
@reFX-Mike the existing C extension does not exist at all for PHP 7. there is a WIP about creating a new extension for PHP 7, but we are not sure yet whether it is worth it

**Comment by brandonkelly** [comment]
I'm closing this FR - agree with @stof a better solution would just be to ignore the C extension if a known buggy version is installed. And knowing that it doesn't even exist for PHP 7 makes the whole thing pretty moot, since the world is ditching PHP 5 pretty quickly anyway.
