### ISSUE TITLE
[feature request] Spaceship operator

### ISSUE THREAD

**Issue by muspelheim** [twigphp/Twig#2320]
I think Twig should have a <=> operator in our templates, its very usefull for design preparation.
I can develop this funtional, if  its need.

@fabpot what do you think about it?

**Comment by reFX-Mike** [comment]
Just curious: can you give me an example how it would be useful?

**Comment by muspelheim** [comment]
@reFX-Mike any deals with orderings in templates.

**Comment by reFX-Mike** [comment]
So you are actually sorting items using Twig? Like a for-loop where you compare each entry etc.?

**Comment by fabpot** [comment]
@muspelheim Can you give a Twig template you would want to write with such an operator? I fail to see how you would use it in the context of Twig.

**Comment by javiereguiluz** [comment]
I'm not sure about the spaceship operator ... but I often need to sort arrays/collections by some property. I'd love to have a `by` parameter in the `sort` filter:

```twig
{% for user in users|sort('name') %} ... {% endfor %}

{% for foo in bar|sort('product.price') %} ... {% endfor %}
```

But you'll tell me that sorting is something for PHP and not Twig ... and you are probably right :)

**Comment by fabpot** [comment]
Closing this issue as I don't see how it would be useful in Twig.

**Comment by bpolaszek** [comment]
Hello there,

I'd like to reopen this because sorting is not the only purpose of comparing values.
Here's another use case which is purely view-centric:

```twig
{% for affiliate in affiliates %}
    {% set payout_cmp = affiliate.payout <=> offer.default_payout %}
    <span class="{% if -1 == payout_cmp %}text-danger{% elseif 1 == payout_cmp %}text-success{% else %}text-primary{% endif %}">
        {{ affiliate.payout }}
    </span>
{% endfor %}

``` 

I understand the point that sorting should be done on the controller side but another use cases may be considered. 

Of course, this example is dummy enough to be converted to 'if >= and <=" etc., then a spaceship operator would just add some more syntactic sugar, but for more complex use cases (i.e comparing on multiple properties like `{% set foo_cmp = [objectA.propertyA, objectA.propertyB] <=> [objectB.propertyA, objectB.propertyB] %}`) I definitely think it would be useful in Twig, wouldn't it?
