### ISSUE TITLE
variable embed file not interpretted correctly

### ISSUE THREAD

**Issue by mindfullsilence** [twigphp/Twig#2324]
Version 1.30.0:

```twig
{% set component_type = "heading" %} {# value actually comes from context #}

{{ 'components/' ~ component_type ~ '.twig' }} {# outputs components/heading.twig #}

{% embed 'components/' ~ component_type ~ '.twig' %}
{% endembed %}

```
The embed throws a fatal error that it cannot find the template file "components/.twig". Note that the variable is stripped from the string. As seen above, simply printing the concatenated string works fine.

I've tried wrapping the string in parens, same issue. Also tried setting the entire concatenated string to a variable, and embedding with the single variable, then twig throws fatal with "Cannot find template file '' ", where the string is empty. 

Downgrading to 1.29.0 resolves the issue.

**Comment by stof** [comment]
Are you using ``only`` on your real embed tag ? See these 2 examples:

- https://twigfiddle.com/m23vu1 without only: working fine
- https://twigfiddle.com/m23vu1/2 with only: undefined variable (which would do your case as well without strict variable by using ``null`` for the variable)
- https://twigfiddle.com/m23vu1/3 with only and passing the variable: working fine

And the second case is actually logical given how embed works: it creates an internal template with a ``{% extends %}`` tag containing the embedded template name, so the resolution of the parent template name happens with the context of the inside of the tag, not of the outside.

**Comment by stof** [comment]
Btw, we should probably update the embed documentation to mention this case

**Comment by mindfullsilence** [comment]
I assumed the _contents_ of the embed, e.g. the blocks within, were sandboxed to the variables passed in, but not the file name itself. Shouldn't this be parsed and compiled prior to running the new context? This is how it has worked for quite some time.

**Comment by stof** [comment]
@mindfullsilence There is no BC break. The ``{% embed %}`` tag works this way since it was introduced in Twig 1.8.0. You can test it with the second fiddle by changing the version used when running it. I suspect that the change is that you were not using ``only`` previously (or you were not using variables in the template name).

The issue is that it cannot be evaluated at compile time (variables are not available at compile time). And at runtime, the ``{% embed %}`` block looks like an include of an internal template extending the embedded template. And this means that evaluating the name of the parent is done inside this internal template, not in ``main.html.twig``.
You can look at the compiled templates in https://twigfiddle.com/m23vu1 to see how this looks like.

**Comment by mindfullsilence** [comment]
Well summumagun. My apologies. Closing out
