### ISSUE TITLE
String concatenation and trans filter

### ISSUE THREAD

**Issue by jacoz** [twigphp/Twig#2351]
It might actually be a `symfony/twig-bridge` bug, but I can't open any issue in that repo.
Anyway, having something like `{{ "my.message." ~ someVar|trans }}` or `{{ ("my.message." ~ someVar)|trans }}` the translation fails because the engine doesn't seem to be able to parse the concatenation.

**Comment by javiereguiluz** [comment]
@jacoz if this is related to TwigBridge, you can open an issue in symfony/symfony repo (use `[TwigBridge]` at the beginning of the issue title).

**Comment by jacoz** [comment]
@javiereguiluz cool, thanks!

**Comment by stof** [comment]
``{{ "my.message." ~ someVar|trans }}`` not doing what you expect is logical due to the precedence of the concatenation and filter operators. It is equivalent to ``{{ "my.message." ~ (someVar|trans) }}``.

However, ``{{ ("my.message." ~ someVar)|trans }}`` should work fine (I use it in my own code, and it does)

**Comment by fabpot** [comment]
Closing as this is not related to Twig.
