### ISSUE TITLE
Parsing of unused parent blocks

### ISSUE THREAD

**Issue by wesleylancel** [twigphp/Twig#2381]
When a template A extends template B, contents of the blocks in template B are still parsed even when they're overruled in template A and not referenced using something like `parent()`.

This can be an issue when the parser fails to parse the contents of an unused block in template B, while it's able to parse the same block in template A just fine.

**Comment by stof** [comment]
This cannot be solved. Templates are compiled and rendered separately (and the result of the compilation is generally cached to be reused).
There is no way to know at parsing time whether a particular part of the template will be used or no.

Thus, skipping the parsing of the block content is not even possible due to the Twig syntax. We must parse the content of the block to find the corresponding ``{% endblock %}`` tag.

**Comment by wesleylancel** [comment]
@stof Yeah, I was afraid that would be the case. Would it be possible to disregard errors from within those blocks? Specifically, unknown tags like {% javascripts %} when Assetic is disabled.

**Comment by stof** [comment]
No, because Twig does not know how to parse unknown tags. So it cannot compile the template properly. It cannot even know where the unknown part ends, as the TokenParser is fully responsible for parsing the related content, allowing any structure (btw, the usage of ``end*`` for the closing tag of a tag using a body is just a convention. you could name it however you want so Twig cannot do guessing based on it. And tags don't always need a body and closing tag. they can end themselves)

**Comment by fabpot** [comment]
Closing as this is not possible.
