### ISSUE TITLE
1.33.0 and "empty" test will try to load random strings as classes

### ISSUE THREAD

**Issue by bestis** [twigphp/Twig#2431]
Hi,

After upgrading to 1.33.0 I started getting errors from class loader and found that release notes had:
`* "empty" test will now consider the return value of the __toString() method for`

Which is in code: twig/twig/lib/Twig/Extension/Core.php:
```
function twig_test_empty($value)
{
    if ($value instanceof Countable) {
        return 0 == count($value);
    }
    if (method_exists($value, '__toString')) {
        return '' === (string) $value;
    }
    return '' === $value || false === $value || null === $value || array() === $value;
}
```

Which is the reason, method_exists without any previous checks.. 
http://www.php.net/manual/en/function.method-exists.php
`Note:
Using this function will use any registered autoloaders if the class is not already known.`

And that's not nice! In many other cases in the same file there is is_object check first, this should also have it! So next version should have:
```
    if (is_object($value) && method_exists($value, '__toString')) {
        return '' === (string) $value;
    }
```

**Comment by fabpot** [comment]
Can you submit a pull request?

**Comment by mpdude** [comment]
Too bad we removed that in 749d36473911b24773d51b4b05e61cc3938257f2

**Comment by mpdude** [comment]
See #2433

**Comment by xkobal** [comment]
Hi,

Can you tag a new Twig version with that fix as soon as possible ? Because it create a real bug with symfony usage:

- When method_exists is triggered on a non object, the Symfony autoload is called (APC Autoloader in production environment)
- In APC Classloader (https://github.com/symfony/class-loader/blob/master/ApcClassLoader.php#L131) when a key doesn't exists, it create a new entry

The result is that your APC Cache if full when you have a lot of page and object

Thanks you.

**Comment by fabpot** [comment]
@xkobal Done for both 1.x and 2.x branches

**Comment by SpacePossum** [comment]
thanks @fabpot :D :+1:

**Comment by xkobal** [comment]
Thanks @fabpot
