### ISSUE TITLE
Support with keyword in block definitions

### ISSUE THREAD

**Issue by mogsie** [twigphp/Twig#2435]
Today it's possible to provide "data" to blocks by wrapping the block definition in a `{% with %}`:

    {% with { "foo": "ONE"} %}
      {% block one %}
        foo one: {{foo}}
      {% endblock %}
    {% endwith %}

If the template is embedded elsewhere, and the block `one` overridden, it has access to the `foo` variable:

    {% embed "something.twig" %}
      {% block one %}
        my foo one: {{foo}}
      {% endblock %}
    {% endembed %}

The output of this would be `my foo one: ONE`

Here's a fiddle:  https://twigfiddle.com/n9e1dr

This is a neat feature.  It allows you to set up variables for each block, allowing the "user" of the template (where it is embedded) to access these variables.

I wonder if the following short-hand would make sense:

    {% block one with { "foo": "ONE"} %}
      foo one: {{foo}}
    {% endblock %}

**Comment by mogsie** [comment]
Another proposition (albeit a different one perhaps) is the ability to pass in parameters when you override a block.  Consider the template above, 

```
{% embed "something.twig" %}
  {% block one with { "foo": "BAR" } %}
    my foo one: {{foo}}
  {% endblock %}
{% endembed %}
```

It's pretty clear that the value of "foo" would be the value I'm passing in.

**Comment by stof** [comment]
This would be very hard to implement without breaking BC and without ambiguity, due to the short syntax for defining blocks.

You second proposal would not work. Overwriting a block cannot alter the context. Defining the context is a runtime action, and the runtime action happens for the parent block (which is both a block definition and a block reference) or for calls to the ``block()`` function (which is only a block reference). You would have to use a with tag *inside* your block definition if you want to change the variable in the child template.

**Comment by mogsie** [comment]
Ok, thanks for the swift feedback. I'll close the issue, as it's just syntactic sugar on top of existing functionality.
