### ISSUE TITLE
Don't escape specific tags by default

### ISSUE THREAD

**Issue by toxpal** [twigphp/Twig#2456]
Please excuse my ignorance, but I didn't find an example in  documentation if it's possible to configure Twig (v 1.x) NOT to escape some tags by default.

In other words, some variables in my script are HTML-formatted messages that contain basic tags (bold, line break, etc.). If I want them to be displayed properly, I use this code:

`{{ page_message|striptags("<a><b><br><hr><i><li><ol><strong><u><ul>")|raw }}`

How can I configure Twig not to escape these tags by default, so if I simply use code `{{ page_message }}` basic HTML tags are not escaped? Is it possible without writing custom filters or extensions (because I'm new to Twig and that might be difficult for me)?

**Comment by stof** [comment]
no it is not possible without custom filters. What you are asking is not escaping, but filtering of the HTML.

What you would need to do is to write a custom filter, which would perform the necessary filtering, and mark this filter as safe for the HTML format (so that its output does not get escaped by the auto-escaper).
But be careful about this: marking a filter as safe can create XSS holes in your application if the implementation of the filter itself is not actually safe against them.

**Comment by sstok** [comment]
And to be clear `striptags` DOES NOT PROTECT AGAINST XSS!! Use something like http://htmlpurifier.org/ instead.

**Comment by stof** [comment]
Also, note that `striptags` is a bad idea to implement a *safe* filtering, as allowing the `<a>` tag allows XSS for instance. I suggest you to look at https://github.com/ezyang/htmlpurifier/ instead. And have a look at https://packagist.org/packages/exercise/htmlpurifier-bundle too if you want, as it contains a Twig extension for it (or just use this bundle if you use Symfony.
