### ISSUE TITLE
Twig escaping should be more reusable

### ISSUE THREAD

**Issue by tomasfejfar** [twigphp/Twig#2466]
When I wanted to reuse escape filter in twig outside of template I noticed how tangled and complicated the whole thing is. I don't understand why it's in global function `twig_escape_filter` and the actual escaping is there inline for most common formats - each in a switch branch. It needs twig environment even though the usage in the actual escapers is limited to pulling charset from it, that could have been passed as parameter. 

Is this somehow intentional? Why aren't the "default" escapers implemented as escapers when the functionality is already there? Why is the function global? Why is it so long and you can't use JS escape or HTML escape in isolation? 

I'd be willing to help improve it, but I believe that this has something more to it than meets the eye that I need help understanding.

**Comment by stof** [comment]
Using a single function taking the Environment as argument is required due to the Twig compilation: we have a single `escape` (taking the strategy as argument), so we can only have a single callable. And filters can request access to the environment, but not to the charset only.
We *could* implement the different strategies as separate functions called by the main `twig_escape_filter`, but this would add a performance impact (adding 1 method call for each usage of escaping, and it is used a lot).

The twig escaping implementation is meant to fulfil the needs of Twig in the most efficient way, not to provide reusable escaping strategies for external code (functions providing the implementation of filters should be considered internal in Twig). If you want a reusable implementation, use a library dedicated to provide such feature (Twig is about providing a templating engine, not reusable escaping). An example of such library is https://packagist.org/packages/zendframework/zend-escaper (which is where the implementation of the `html_attr` strategy comes from btw, as Twig just copied their code for this one)

**Comment by tomasfejfar** [comment]
I understand the motivation. And I understand that Twig is not intended as escaper. Nevertheless, I see a viable use-case where I have extensively used and tested escaping in Twig. I'm developing a twig extension. I output some HTML from the extension, so I mark it as "safe HTML". 

I'd argue that it's much better DX-wise to have escape function ready. I can hardly imagine that many people would add new external dependency just to escape a piece of code. I imagine that now most people won't escape "safe HTML" output from extensions at all or just use htmlspecialchars() without all the bells and whistles that Twig implementation has. 

Also I understand the reasoning about performance. But wouldn't it make sense to take advantage of the compilation and compile the function contents inline, while still allowing to use it separately? It would add little bit of "magic", but I think it's perfectly reasonable in the compilation step.

**Comment by stof** [comment]
@tomasfejfar inlining the logic is not possible, as we cannot keep it as an expression inside a statement (try to write the whole implementation inside a single statement and you will see that it does not work well). Thus, it would require inlining the full code in some cases (as the strategy being used may not be known at compile time if the argument being passed relies on a Twig variable).

And when writing Twig filters or functions in an extension, it is very easy to get access to the Twig_Environment to pass it to the `twig_escape_filter` function, thanks to the same feature than used by the `escape` filter: telling Twig that you want to get the environment as first argument of your callable when calling your function/filter.

**Comment by fabpot** [comment]
I'm closing this issue as we won't make the escapers more decoupled. As @stof mentioned, the current code is optimized for performance. That's very important as the code is potentially called thousands of times to render a complex page.
