### ISSUE TITLE
RFC: Move to namespaces

### ISSUE THREAD

**Issue by dborsatto** [twigphp/Twig#2482]
Hello everyone,

I've been a happy Twig user for a few years, and even though lately I haven't used it as much (doing more API stuff), I really love it.

However, one thing that always looked weird to me was having code that _looked_ legacy. I know that Twig has a long history (it wasn't called Twig initially, if I remember correctly) and I know that BC is a strong selling point. However, I feel like lately there has been some opening towards breaking BC in a more deep way -- I'm thinking about PHPUnit and Symfony especially, with PHP 7.1, Flex, etc. As I'm seeing here, `composer.json` now requires PHP 7.0 in the `master` branch, so some of that moving forward attitude has trickled down to Twig as well.

My question here is: given everything that's been going on, would it make sense to think about refactoring the code to use namespaces now? I know that Fabien [thought about it a few years ago](https://twitter.com/davide_b88/status/631755499369840640), but eventually he preferred to favor BC instead.

I hacked together a [POC](https://github.com/dborsatto/Twig/tree/namespaces) last couple days, tests are green but there's still some cleaning up to do (like changing inline `\Twig\Something` to `use` statements, squashing commits, etc). Given that we're using PHP 7.0 as a starting point, it could also be the chance to add some type hinting (though it may be out of scope).

Of course this would be a complete BC break (though even PHPUnit did the same recently, and for most people it was a simple matter of renaming `PHPUnit_Framework_TestCase` to `\PHPUnit\Framework\TestCase`, or adding a `use` statement). Because of this, a new major version would be required (Twig 3?), but I'm not currently sure what the plans for that are, at the moment.

What do you think? Personally I feel like a new coat of paint would help attract new contributors and end users, so it wouldn't be a simple change for changing sake.

**Comment by stof** [comment]
The difference is that people using PHPUnit deal with very few classes of PHPUnit. Most classes are internal to PHPUnit. Users are calling PHPUnit through the command-line tool.

For Twig, such migration would be much more painful, as Twig is a library, not a command-line tool, and so people use many Twig classes directly.
Migrating to namespaces would create lots of pain in the community, without any real benefit (there is nothing making namespaces mandatory to use newer PHP features).

**Comment by dborsatto** [comment]
That's certainly true about Twig being a library and not the same as PHPUnit, however I think that most people who work with Twig directly use a rather limited subset of it's classes (I'm thinking _mostly_ Twig_Function and Twg_Filter).

I know it's comparing apples to oranges, but years ago I didn't want to use libraries such as PHPMailer because they looked old (I was extremely happy when Swift became popular). I know it's not at all a valid metric of quality, but I'm afraid using old style class naming might have a similar effect to developers today.

On the side: are there currently plans for Twig v3?

**Comment by javiereguiluz** [comment]
I agree with the argument of *"let's not change this because it'll break everything while providing no benefit"*.

However, this is causing issues for example in Symfony's Dependency Injection (see https://github.com/symfony/symfony/issues/22851 for details).

So, my crazy question for Composer experts:

1. Could we update the Twig source code to use namespaces ...
2. ... but at the same time provide some autoloading config in Composer to not break applications still using the old classes?

Can Composer define two different ways to load a singles class in a given package? (So both `use Twig\Environment;` *and* `use Twig_Environment;` work).

**Comment by stof** [comment]
@dborsatto if they use Twig without using the Twig_Environment, things are weird.

And Twig users also have to configure Twig to use it (for instance the loader), so they deal with more code from Twig (people using Symfony write less code using Twig, because lots of it is in Symfony itself, but Symfony is still an external package as far as Twig is concerned, and so is a target of the Twig migration path too)

@javiereguiluz the Symfony issue you linked is not even related to Twig, but to Twig-extensions, which is a separate project (and indeed much easier to migrate to namespaces, as there is only a few classes in it).

AFAIK, there is no plans for Twig 3 yet. We don't have a need to break BC yet (I don't think we have lots of deprecated APIs in 2.x yet)

**Comment by dborsatto** [comment]
@stof if there's no plan for v3 at the moment, how come was the required PHP version bumped to 7 in master? Shouldn't this kind of change warrant a new major release? Just curious :-)

**Comment by stof** [comment]
@dborsatto version *2* requires PHP 7

**Comment by dborsatto** [comment]
Sorry my mistake, I was basing my timeline on [this tweet](https://twitter.com/fabpot/status/631731242816421888) from 2015 so I thought it was older, then I checked the actual date on Packagist and on the commit that changed the required PHP version. My bad!

**Comment by stof** [comment]
Well, Twig 2.x took quite some time to finalize.

btw, when looking at a commit, Github shows you which tag it belongs to

**Comment by hkdobrev** [comment]
See also this https://github.com/twigphp/Twig/issues/2108#issuecomment-244262066

**Comment by fabpot** [comment]
Done
