### ISSUE TITLE
Why PHP 5.2 support drop happened in a minor version?

### ISSUE THREAD

**Issue by sciamannikoo** [twigphp/Twig#2504]
As per semver convention, minor updated are supposed to be backwards compatible.

I've just found out that in Twig 1.34.0, support for PHP 5.2 has been dropped.

This decision forces us to set a fix version to 1.33.0 in Composer, in all our projects.

Why hasn't the support drop been done in a major release?

**Comment by stof** [comment]
Well, dropping support for a PHP version unmaintained since 6 years was considered OK for a minor version.

Btw, composer itself handles selecting a version compatible with your PHP version, if you configure it properly (if you want PHP 5.2 compat, you need to tell composer to use 5.2 as PHP version rather than your current PHP version).
Btw, you should not force Twig 1.33 in your project if it is installable as a dependency. Anyone asking composer to resolve deps for a project not needing PHP 5.2 compat should be able to get a newer Twig version (and people wanting PHP 5.2 compat for whatever weird reason should configure Composer for that)

**Comment by fabpot** [comment]
Dep versions are not part of semver as far as I know. Anyway, @stof is right.
