### ISSUE TITLE
attribute function "Accessing Twig_Template attributes is forbidden."

### ISSUE THREAD

**Issue by chapterjason** [twigphp/Twig#2534]
I'm using the `attribute` function to dynamically call a `macro` all within the same File, Im ensured that I use local variables and dont use any "upper" variables...

My used code(https://twigfiddle.com/256p12):
```
{% import _self as macros %}

{% macro link(title, url) %}
    <li class="nav-item">
        <a class="nav-link" href="{{ url }}">{{ title }}</a>
    </li>
{% endmacro %}

{% macro dropdown(title, url) %}
    <a class="dropdown-item" href="{{ url }}">{{ title }}</a>
{% endmacro %}

{% macro render(item, macroName) %}
    {% import _self as submacros %}
    {% set macroName = macroName|default('link') %}
    
    {{ attribute(submacros, macroName, [item.url, item.title]) }}
{% endmacro %}


<ul class="nav">
    {% for item in items %}
        {% if item.items|length > 0 %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">{{ item.entry.title }}</a>
                <div class="dropdown-menu">
                    {{ macros.render(item, 'dropdown') }}
                    <div class="dropdown-divider"></div>
                    {% for subitem in item.items %}
                        {{ macros.render(subitem, 'dropdown') }}
                    {% endfor %}
                </div>
            </li>
        {% else %}
            {{ macros.render(item) }}
        {% endif %}
    {% endfor %}
</ul>
```

**Comment by harmstyler** [comment]
Basically, the `attribute` can't be used to call macros anymore? I'm experiencing the same issue. https://twigfiddle.com/kr852e

**Comment by stof** [comment]
well, using attribute access to call macros is indeed what has been deprecated, as this forces a bunch of limitations on the way macros are compiled (and introduced a security issue in the past).
why are you using a macro calling a dynamic macro instead of calling the `dropdown` macro directly in your case ?

**Comment by chapterjason** [comment]
In this example you can see that I'am generating menus from a datasource in this example from database. To represent subpages I've a `MenuEntry` entity with a self-referenceing relationship. I currently see that I also could use the `dropdown` macro directly.  

My use case currently expanded a bit, I've different entities in the `render` `item` param that have a `@MappedSuperclass` where I detect if the link is the current page to render is correctly. 

Recently I created this extension to call the macros dynamically.
```
/**
 * Class CallUserFuncArrayExtension
 * @package SoureCode\Bundle\CoreBundle\Twig\Extension
 */
class CallUserFuncArrayExtension extends \Twig_Extension
{
    /**
     * @return array
     */
    public function getFunctions()
    {
        return [
            new \Twig_SimpleFunction('call_user_func_array', [$this, 'call_user_func_array']),
        ];
    }
    /**
     * @param $object
     * @param $method
     * @param $attributes
     * @return mixed
     */
    public function call_user_func_array($object, $method, $attributes)
    {
        return call_user_func_array([$object, $method], $attributes);
    }
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'call_user_func_array';
    }
}
```
```
{{ call_user_func_array(macros, type, [entry.title, entry.url]) }}
```

Which limitations are there? Which security issue?

**Comment by stof** [comment]
Limitations of allowing access to macro as attributes are these (list may not be exhaustive, I may have forgotten some when writing this message):

- it forces us to compile macros without any prefix in the method name (so that accessing them as attribute works), leading to name conflicts with methods of the Twig_Template class (in Twig 1.x, a bunch of macro names are forbidden because of that)
- it does not use the optimized rendering code for macros (as it is not considered as a macro usage)
- it forbids us to refactor the way macros are referenced internally (as making any change to the way we handle macros would break things for people calling them through attribute access rather than through macro call)
- it forbids us to implement support for named arguments in macros (which was requested in the past)

The security issue was related to the fact that attribute access was implemented in Twig_Template previously, and so would allow to access protected APIs of the class when accessing attributes on a Twig template. This allowed to bypass the sandbox (and to cause weird bugs too).

I would recommend against exposing `call_user_func_array` to Twig template. This could cause weird issues (and don't ever do that when you want to use the sandbox). And if you use it to call macros, it would rely on the internal implementation of compiled macros as you would have to know the compiled name, and this is something subject to change at any time now that attribute access is not supported anymore for them.

**Comment by kevinpostma** [comment]
Isn't it possible at all to call macro's dynamically. i am having this issue too. Will there be some sort of function that can call macro's dynamically in the future?

**Comment by Humeira** [comment]
I've just updated Twig to 2.x on one of my projects, I have been using attribute to call macro dynamically. Now obviously I have lots of breaking changes. Any quick proper way to fix all these?

**Comment by fabpot** [comment]
Closing as that's not something we will revert/change (for reasons explained by @stof).
