### ISSUE TITLE
UseTokenParser::parse() does not adhere to interface

### ISSUE THREAD

**Issue by dbrumann** [twigphp/Twig#2538]
I was doing a static code analysis to see if there are type issues in Twig worth fixing and stumbled upon the following problem. I'm not sure if it's worth fixing in the first place and if so, what would be the best way to approach this.

The [TokenParserInterface::parse specifies a return type Twig_Node in it's docblock](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/TokenParserInterface.php#L27). The [UseTokenParser::parse()](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/TokenParser/Use.php#L28) does not adhere to that interface as it returns void.

Since moving to type hints in Twig is not a priority I think this might not be worth dealing with in the first place, but should at any point the return type on the interface be enforced this parser will break. I therefore suggest making the return type (in the docblock) on the interface optionally null or (less desirable) just add a `return new Twig_Node()` to the UseTokenParser. As a quick fix I tried to return the Node that is generated and passed to `parser::addTrait()` instead, but unlike with the empty dummy node, that will break a lot of tests.

Feel free to just close the issue, if you think it's not worth discussing/fixing at the moment.

**Comment by stof** [comment]
Well, the code in Twig_Parser explicitly supports returning `null` too. So the mistake might rather be the TokenParserInterface.

The `{% use %}` tag is very special: it is here to import a trait in the parser, but does not contribute anything to the AST of the template (well, traits are in the AST, but as part of the `Twig_Node_Module` representing the whole template).

I think adding an empty Twig_Node in the AST when encountering a `{% use %}` might have unwanted side effects in a few cases (if it happens outside blocks in a template extending another one, I'm not sure whether this will trigger the violation due to forbidden content there).

So the right fix would be to change the phpdoc of the interface (to reflect the actual contract) or to make usage of an actual dummy node (i.e. a dedicated node class which can be known to have no effect) and deprecate the possibility to return null.

**Comment by stof** [comment]
I'm not sure there can be any use case for returning `null` outside Twig itself, as such token parser would then have to alter the Twig_Parser itself to have an effect (and external libraries cannot add feature in Twig_Parser directly).
The only case I can imagine would be implementing a `{% comment %}{% endcomment %}` tag (i.e. something you want to make disappear from the template entirely), but Twig already has a syntax for comments.
