### ISSUE TITLE
"in" operator behaves wrong if there's a "-" in the keys

### ISSUE THREAD

**Issue by wnoveno** [twigphp/Twig#2542]
Here's the fiddle of the issue.
[https://twigfiddle.com/ijzyu9](https://twigfiddle.com/ijzyu9)

In the sample 430001 should not be selected but it's being seen by the in operator since the options have it as well.
This issue only pops up if a substring is separated by a "-".

**Comment by fabpot** [comment]
The behavior comes from PHP :(

First, when iterating over the array, PHP automatically converts `"430001"` to the `430001` integer. So, in the loop, `value` is an integer, not a string.

Then, and that's really an annoying PHP behavior, `in_array(430001, array("430001-7","430001-8"))` returns `true`. Note that `in_array("430001", array("430001-7","430001-8"))` returns `false` as expected.

That's because PHP tries to be smart :( Behind the scenes, as `430001` is an integer, PHP converts the array values to integers for comparison. And `430001-7` is converted to `430001`. Bingo.

We could use `true` as the third argument to `in_array()`, but that would be a BC break. So that's unfortunately not an option.

As this is a PHP behavior, there is, unfortunately, nothing we can do in Twig.
