### ISSUE TITLE
Twig_Source is final and has no interfaces - what is the idea behind this?

### ISSUE THREAD

**Issue by kiler129** [twigphp/Twig#2549]
While digging more and more into Twig internals I discovered @fabpot made a change in https://github.com/twigphp/Twig/pull/2288/commits/e89c712f58a5639c1537c609ace5fde116d0d7f3 which made `Twig_Source` final.

The class in question is simple, yet in my opinion, limiting. There's an internal assumption template will always be a file located under local path. While writing own loader is a mater of creating a class implementing `Twig_LoaderInterface` there's no sane* way to really attach any information to returned template. 

Such scenario is extremely useful while dealing with "templates" loaded from e.g. database. Additionally I don't see any downside of extending `Twig_Source` class - can you explain me the reasoning behind the class being final?

_* I can attach magic public property, but this is just plainly stupid ;)_

**Comment by sstok** [comment]
You can abuse the `path` parameter to store your template-name, but I'm no fully this is safe 😛

**Comment by stof** [comment]
Twig_Source has 3 properties:

- the code of the template
- the name of the template (which is what you use to refer the template in your project, and what the loader receives as input)
- the **optional** filesystem path (which can stay `null` if your template is not stored on the filesystem, for instance in your case), which is here to improve error reporting (rewriting stack traces to go to the template source rather than the compiled template).

What kind of custom information do you want to add ? Making this extendable will not be done without a clear use case justifying the extension point (any new extension point has a maintenance cost, and inheritance-based extension points are the most costly in regard to backward compatibility)

**Comment by stof** [comment]
@sstok I would not do that, as it would make error reporting totally messy.

**Comment by fabpot** [comment]
Closing as there is no feedback anymore.
