### ISSUE TITLE
Add note to documentation about `if` operator perfomance

### ISSUE THREAD

**Issue by terales** [twigphp/Twig#2576]
Thank you for ongoing improvement of the Twig!

I found a noticeable performance difference between rendering operators inside `if` branches:

```
// First case
{% if some_var %}
    {% include 'inline-version.twig' %}
{% endif %}

// Second case
{% if some_var %}
    … the same content as in 'inline-version.twig' goes inline here
{% endif %}
```

I've obfuscated file from my colleague and measured differences in https://github.com/terales/twig-if-perfomance. Here are my results in seconds:
```
// PHP 5.6 + Twig2
inline-version.twig:  0.2901
include-version.twig: 0.0051

// PHP 7.1 + Twig1
inline-version.twig:  0.0432
include-version.twig: 0.0012

// PHP 7.1 + Twig2
inline-version.twig:  0.0391
include-version.twig: 0.0011
```

I would like to add a note about that difference to the twig documentation, would you accept PRs to the 1.x and 2.x docs?

**Comment by stof** [comment]
your test is unfair: you don't compare rendering time. You compare the compile+rendering time. And your test for `include-version.twig` does not recompile the `inline-version.twig` template as it is already compiled by the previous rendering. Change the order of both cases, and you will see the opposite number.
The only thing that your benchmark is showing is that compiling templates takes more time than reusing the already compiled one (which is something we know since ages, which is why Twig is able to store the compiled template in a persistent cache).

**Comment by terales** [comment]
Thanks for taking a look! I've tried to run separate tests and numbers are basically the same, so there is no issue there.

Sorry for taking your time!
