### ISSUE TITLE
[Doc] Is  there any markdown format docs, I can help translate into Chinese

### ISSUE THREAD

**Issue by slince** [twigphp/Twig#2597]
:sweat_smile:

**Comment by stof** [comment]
Documentation is in rST format in the `doc` folder.

However, if you want to translate it into Chinese, you would have to maintain the translation on your side. We don't want to maintain the Chinese translation in the main repo (because we are not able to maintain it as we don't know Chinese, and outdated translation is worse developer experience than no translation)

**Comment by slince** [comment]
@stof 
 
Hi! I am more familiar with markdown and I can generate a static website with some tools like [hexo](https://github.com/hexojs/hexo) or gitbook;   But I do not know how to deal with `rst` file, can you recommend some tools?  For example "http://twig.sensiolabs.org/" how to generate this?

> if you want to translate it into Chinese, you would have to maintain the translation on your side

This is no problem
