### ISSUE TITLE
Restore methods from Twig_Loader_Filesystem to protected visibility

### ISSUE THREAD

**Issue by twoixter** [twigphp/Twig#2609]
Issue #1773 moved some helper methods from protected to private visibility. This prevented proper inheritance of `Twig_Loader_Filesystem` class to create new file loading strategies. For instance, we are creating a new class inherited from `Twig_Loader_Filesystem` to locate files based on the current application locale. `{% include "template" %}` would select `template.en.twig` or `template.es.twig` based on the current locale. Other interesting file searching strategies can be accomplished by overloading the `findTemplate(..)` method.

The relevant methods to make protected again are:

- `normalizeName()`
- `parseName()`
- `validateName()`
- `isAbsolutePath()`

This is so that they're visible for child classes. Additionally, I think those methods are helpers, they don't use `$this` so that they can be easily be static as well. Think of `Twig_Loader_Filesystem::normalizeName()` as the canonical way to normalize a file name for loaders. Same for `Twig_Loader_Filesystem::parseName()`, etc.

**Comment by ericmorand** [comment]
I agree on this totally.

I can't see why those methods have been made private. They are not harmful if overriden by a subclass.

And more importantly: why would anyone explicitely want to prevent overriding in a OO language? What is the point? Setting methods as private doesn't substract the maintainers from unit testing those methods so what is the benefit exactly?

The PR you mentioned have @fabpot setting those method to private just "because", without a single explanation as to why and for which benefit. It's difficult to defend his move.

**Comment by stof** [comment]
making them protected means they are extension point, for which we need to preserve backward compatibility, limiting the kind of refactorings we can do.

The maintenance cost of a protected method compared to a private method is the fact that this becomes an extension point.

Btw, the use case described about about changing the file being loaded based on the locale is precisely a case where the extension point is harmful: this kind of logic is broken if the caching layer is not aware of it (so that the cache varies based on the same business rules). So implementing it by extending the `Twig_Loader_Filesystem` means that any refactoring to our caching layer potentially becomes a BC break too (forbidding us to do it). This is the kind of maintenance cost I'm talking about.

**Comment by stof** [comment]
And the fact that the PR does not have the explanation is because this is not the initial PR moving protected to private. It is a PR *continuing* the migration by changing *more* places (as said in the title). I think the original discussion has more details.

**Comment by fabpot** [comment]
Closing as we won't go back to protected without a good use case.
