### ISSUE TITLE
Lexer errors lack template name and lineno

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2628]
Consider the following Twig template:

`{{{  width }}`

https://twigfiddle.com/h8wm63

The error message should read `"Unexpected "}" in "main.twig" at line 1."` Instead it only read `"Unexpected "}"."`

The culprit is probably this line:

https://github.com/twigphp/Twig/blob/45990c3644032f255824a6a3819ba5d828236eef/lib/Twig/Error.php#L164

**Comment by stof** [comment]
Well, the file and line of the Exception object are set to the proper location, so that the PHP stack trace points at the original Twig source.

The fact that twigfiddle only displays the exception message and not the exception location is an issue in Twigfiddle, and should be reported to this project.

**Comment by stof** [comment]
And actually, Twigfiddle is displaying the location of the error too:

![twigfiddle_reporting](https://user-images.githubusercontent.com/439401/36388304-b6205200-159b-11e8-952c-6634316694f6.png)

**Comment by ericmorand** [comment]
@stof, thanks for your support.

It happens that the problem (or lack thereof) comes from the fact that when using filesystem loader, the errors won't output template name and line number while they will when using array loader.

Probably by design even though it is a bit confusing that error messages formatting differ depending on the loader used.

**Comment by stof** [comment]
Well, when it can put the location as the location of the exception (which requires having an actual file), Twig does it (so that your PHP stack trace itself points to the error).
When the source is not a file, we cannot point the stack trace there (it would break the expectation of error handling tools if the file location was not a valid file name) and so Twig adds the info in the message so that it still exists somewhere.

**Comment by ericmorand** [comment]
@stof, thanks a lot, that makes sense.
