### ISSUE TITLE
One cent missing using round - floor

### ISSUE THREAD

**Issue by Anamican** [twigphp/Twig#2631]
I'm using Twig 1.24.1 and I found that when I try to round - floor like below, the precision is reduced by 1 in 2nd decimal

{{ 149.95|round(2,'floor') }} 

Expected output: 149.95
Actual output: 149.94

Further more it happens for other numbers as well.
And it does not happen in 4 digit numbers

I tested this on all twig versions from the fiddle page,  fiddle here: https://twigfiddle.com/i5g9a2

**Comment by jfcherng** [comment]
Some float numbers cannot be precisely stored since it may use IEEE 754 representation internally. That is, `149.95` is stored as something like `149.94999...` on your computer.

# References

- http://www.exploringbinary.com/floating-point-converter/

**Comment by fabpot** [comment]
Closing as there is nothing to fix here, just normal PHP behavior.

**Comment by Anamican** [comment]
Thank you

**Comment by jmldavis** [comment]
I've had this same issue and found a somewhat hacky way to fix it. Probably a bit late to help you @Anamican but if anyone else encounters this...

For e.g. rounding a number down to 2 decimal places:
```
{% set numericValue = numericValue * 100 %}
{% set numericValue = numericValue|split('.')[0] %}
{% set numericValue = numericValue / 100 %}
````
`numericValue` will therefore = `10.04` instead of `10.03` which it does if only using `numericValue|round(2, 'floor')`
