### ISSUE TITLE
Can twig be extended to modify the behaviour of {{ }} ?

### ISSUE THREAD

**Issue by martixy** [twigphp/Twig#2642]
It boasts with being able to define new language constructs, however I fail to see a way to define a way to create a shorthand for `verbatim`.
With the proliferation the mustache syntax in various templating engines outside of twig(e.g. handlebars, vue) it pays to have a shorthand for outputting functional twig syntax verbatim. Say `@{{ thing }}`.

Is there a way to extend twig to do that?
Are there plans of creating such a mechanism?
If not, why?

**Comment by ericmorand** [comment]
I'm sure this is not easily done because the lexer uses regexes to parse the delimiter:

```php
        $this->options = array_merge(array(
            'tag_comment' => array('{#', '#}'),
            'tag_block' => array('{%', '%}'),
            'tag_variable' => array('{{', '}}'),
            'whitespace_trim' => '-',
            'interpolation' => array('#{', '}'),
        ), $options);
```

And unfortunately this property is private which means that changing theses regexes it is not supported at all (i.e. not tested) and that you would have to provide a whole new class instead of extending `Twig_Lexer`. And of course you would have to override the `tokenize `method of `Twing_Environment ` to use your custom class but at least this one is public.

If you want to try, I'm very curious about the result.

**Comment by fabpot** [comment]
You can definitely change the delimiters: https://twig.symfony.com/doc/2.x/recipes.html#customizing-the-syntax.

But you cannot add a new one.

Adding support for `@{{ ... }}` is interesting. I'd like more opinion though. /cc @stof

**Comment by stof** [comment]
So what would `@{{ thing }}` do ? Echoing `{{ thing }}` ? This would be a huge BC break, as it would break any place displaying something after a `@` char today (anything outside the curly brace is pure output, so it can be anything and we cannot extend the syntax there)

**Comment by fabpot** [comment]
I was not saying that this particular syntax was a good idea, just the idea of having the possibility to have something shorter to have verbatim tags. We could use `{{@ }}` instead.

**Comment by ericmorand** [comment]
@fabpot amazing, I never noticed that `$options` was a parameter of `Twig_Lexer::__construct`

**Comment by martixy** [comment]
> We could use {{@ }} instead.

That certainly seems like a fair compromise.
Similar on `whitespace_trim` there could be a `'verbatim' => '@'`.

And while `@{{ thing }}` would be a BC break, it is also one that would be very easy to fix with a vanilla search and replace.

**Comment by stof** [comment]
@martixy doing such search & replace in the whole ecosystem is out of our scope => we cannot perform it, so BC break is not an option.

and this would thus make it harder to display a `@` before a Twig output.

**Comment by kiler129** [comment]
Defining your own tag like verbatim is not possible unfortunately, but you can still define your own token parser where you match everything between `{% foo %}` and `{% endfoo %}` using `$stream->expect(\Twig_Token::TEXT_TYPE)`. Then you just do `$token->getValue()` instead of calling subparse.

**Comment by plashenkov** [comment]
Yep, another vote for providing a handy way to echoing a `{{ }}` as is. Mixing Twig and Vue (for example) is a pain now. `@{{ }}` syntax used in Blade (https://laravel.com/docs/5.7/blade#blade-and-javascript-frameworks). Let's make this syntax configurable with the ability to turn it completely off for those who need BC.

**Comment by plashenkov** [comment]
@fabpot I've found this PR: https://github.com/twigphp/Twig/pull/2128 and have read comments.

- Regarding BC break: an ability to turn it off (or even turn it off by default) solves the BC issue.
- Regarding "mixing template engines is a bad practice": rules for the sake of rules is a bad practice, sometimes we need to do that. For example, when we write traditional MPA (instead of SPA) and need some JS reactivity and MVVM in our pages.
- Regarding "just use another interpolator in your JS framework instead of `{{ }}`". Changing interpolator breaks code reuse: you will not be able to use your or 3rd-party reusable JS components, templates, etc. until you rewrite them to use new non-standard interpolator. Even if you rewrite them your IDE stops to understand your templates.

We need this functionality!

**Comment by stof** [comment]
>     * Regarding BC break: an ability to turn it off (or even turn it off by default) solves the BC issue.

no it does not: turning it on or off globally makes it impossible to use that syntax in a package you share: if you share a package expected this new feature to work, it cannot be used in a project turning off the feature. And if you write a template expecting things to work as today (a `@` being output and then something else being output), it cannot be used in a project turning the feature on.
This would create a community-split.

Blade can make this syntax because `@` is its reserved char for the Blade syntax (meaning you probably need to escape a `@` if you want to display it, similar to what you need to do for `{{` or `{%` in Twig). `@` is absolutely not a reserved char in Twig, and turning it into a reserved char cannot be done in a BC way.

**Comment by plashenkov** [comment]
> no it does not: turning it on or off globally makes it impossible to use that syntax in a package you share: if you share a package expected this new feature to work, it cannot be used in a project turning off the feature.

Well, the same is true for https://twig.symfony.com/doc/2.x/recipes.html#customizing-the-syntax
If you customize the syntax you cannot use packages which use default syntax. But you are still able to customize. If this custom block will be added and disabled by default, then globally nothing changes. You just can turn it on for your project, that's all. The second situation: if this block will be added and turned ON by default, you can turn it off for your old project for BC (and you need to do that only if it really conflicts with your templates). Yes, you will not be able to use 3rd-party templates which are decided to use this new feature. But that's totally OK.

> Blade can make this syntax because @ is its reserved char for the Blade syntax (meaning you probably need to escape a @ if you want to display it, similar to what you need to do for {{ or {% in Twig). @ is absolutely not a reserved char in Twig, and turning it into a reserved char cannot be done in a BC way.

I am not saying we must use exactly `@{{ }}`. This is just an example, not more. Let's use another, more Twig-oriented variant.

**Comment by stof** [comment]
> Well, the same is true for https://twig.symfony.com/doc/2.x/recipes.html#customizing-the-syntax
> If you customize the syntax you cannot use packages which use default syntax. But you are still able to customize.

and that's why TwigBundle does not allow configuring these settings in a Symfony project for instance.

**Comment by fabpot** [comment]
Re-reading comments on #2128, I'm going to close this one. See #2140 for some docs about the same.
