### ISSUE TITLE
The trim filter trims more than expected

### ISSUE THREAD

**Issue by sevfurneaux** [twigphp/Twig#2708]
When using the `trim` filter in the example code:

{{ 'https://youtu.be/uFsHIEDJWU0'|trim('https://youtu.be/') }}

The string trims more than `https://youtu.be`, and removes the `u`. For example:

`FsHIEDJWU0`

This _should_ be:

`uFsHIEDJWU0`

**Comment by SpacePossum** [comment]
Hi,
This is because the `trim` filter strips characters, not strings, similar to the PHP `trim` functions.
In your example you trim all the characters in `https://youtu.be`, since the characters `u` and `/` are in there it these get removed, or stated differently: the first character found in the source that is not `https://youtu.be` is `F` that is why the trimming stops there.
If you know the number of characters you want to remove from your string you might be better of using 
[slice](https://twig.symfony.com/doc/2.x/filters/slice.html).

**Comment by fabpot** [comment]
Or replace

**Comment by sevfurneaux** [comment]
Thanks @fabpot and @SpacePossum – in that case I'll use `replace` 😊

**Comment by sevfurneaux** [comment]
Closing 👍
