### ISSUE TITLE
[BUG?] Filtered for loop skips too many results

### ISSUE THREAD

**Issue by zelding** [twigphp/Twig#2723]
Tested in version **1.35**

The `{% for i,v in data if i != 'something' %}` statement doesn't produce the expected results, in my case one row less than it should.

the first (left) table is a for loop without a condition, the second should skip the last row which index is `_sum`.

The way i was able to get around this problem is to create a filter extension that tests for numbers
My version was this: 
```
 new Twig_SimpleTest('number', function ($value) {
    return is_numeric($value) && (int) $value === $value;
 }
```

and used like this: `{% for i,v in data if i is number %}`

Here is a [fiddle](https://twigfiddle.com/z9ipek) and a screenshot
![twig_loop_error](https://user-images.githubusercontent.com/16646014/43067948-3fcad7c8-8e69-11e8-9c5a-09d28cbb1989.png)

**Comment by jvasseur** [comment]
That one is tricky, but basically what appends is that `0 == '_sum'` is true for PHP (https://3v4l.org/euqNi). It work like this because when comparing a integer and a string PHP cast the string to an int and when casting non-numeric strings to ints you get 0. You should use `if i is not same as('_sum')` instead.

**Comment by zelding** [comment]
@jvasseur thank you for explaining
