### ISSUE TITLE
Can't figure out how to remove / replace `&nbsp;`

### ISSUE THREAD

**Issue by su-narthur** [twigphp/Twig#2742]
I need to replace `&nbsp;` with normal spaces so that `|trim` will work as expected. However, neither copying the `&nbsp;` char into a `|replace` filter nor literally writing `'&nbsp;'` work. How can I do this?

**Comment by stof** [comment]
writing the HTML entity literally won't help you to replace the non-breaking space char, as they're not the same strings (HTML entities gets replaced by their corresponding char only when parsing HTML).

To replace chars, use a string containing a non-breaking space for the replacement. Copy-pasting may not work fine, as your software might turn it into a normal space at some point of the process (and it would probably hurt maintenance due to not being visible that it's not a normal space). Using an escape sequence is a safer solution. See https://twigfiddle.com/nn8ss5 for an example.

**Comment by su-narthur** [comment]
@stof Hey, fantastic, that works! I never knew about escape sequences before. That's super useful.

**Comment by stof** [comment]
Well, it looks like supported escape sequences are not documented in the place describing string literals (except saying that backslashes need escaping): https://twig.symfony.com/doc/2.x/templates.html#literals

The escape sequences in Twig string literals are the one supported by https://secure.php.net/stripcslashes

**Comment by iamsahilralkar** [comment]
First, get your whole HTML div and convert it to the string

    convertHtmlToText(str)
    {
       str = str.toString();
      return str.replace(/<[^>]*(>|$)|&nbsp;|&zwnj;|&raquo;|&laquo;|&gt;/g, ' ');
    }

you will get the text without HTML tag and &nbsp etc

This is a solution for HTML tag and &nbsp etc and you can remove the useless conditions

**Comment by Adgivi** [comment]
First I hope you know the actual difference between this two characters. If you do and you still need the replacement you can do it with a custom filter:
```php    
public function clearNbsp($str)
{
    $entities = str_replace('&nbsp;', ' ', htmlentities($str));
    return html_entity_decode($entities);
}
```

**Comment by MichaelBrauner** [comment]
`{{ text|striptags|raw }}`

Important is, that the striptags come before the |raw filter.

**Comment by skylar-pink** [comment]
> [@stof](https://github.com/stof) Hey, fantastic, that works! I never knew about escape sequences before. That's super useful.





https://lnkr.fun/b9e40c8

**Comment by anikajb92** [comment]
I had this issue when assigning **.innerText** but the literal string translated into a space when using **.innerHTML** instead. Hope this helps.
