### ISSUE TITLE
CVE-2018-13818

### ISSUE THREAD

**Issue by bh-e** [twigphp/Twig#2743]
Hello. 

I couldn't find which change  fixed CVE-2018-13818. Please help.

**Comment by stof** [comment]
I don't know about this CVE, and Twig does not do anything with `$_GET` parameters by itself.

And the exploit https://www.exploit-db.com/exploits/44102/ linked on https://www.cvedetails.com/cve/CVE-2018-13818/ talks about accessing `http://localhost/search?search_key={{ls}} ` to trigger the exploit. But this implies a website, not just Twig.

So I think this CVE was not tied to the right source. The issue was most probably in a different package (maybe *using* Twig among other things).

**Comment by stof** [comment]
And the diff of 2.4.4 makes it even less likely that such thing got fixed: https://github.com/twigphp/Twig/compare/v2.4.3...v2.4.4

**Comment by bh-e** [comment]
@stof , Have you attempted to reproduce https://www.exploit-db.com/exploits/44102/ .

**Comment by nicolas-grekas** [comment]
Same as @stof, this looks like an invalid or at least incomplete report. @bh-e there is no way to reproduce this: Twig is not a web app so you cannot hit it. It needs a webapp to wrap it. It's the responsibility of the webapp to do it properly. If you have more details about this CVE, we would be happy to try a reproducer.

**Comment by bh-e** [comment]
@nicolas-grekas , @stof . I have contacted the exploit author via twitter and his reply: https://mobile.twitter.com/jameel_nabbo/status/1032593354704515072?s=20
