### ISSUE TITLE
Accessing an ArrayObject with a null value fails

### ISSUE THREAD

**Issue by X-Coder264** [twigphp/Twig#2744]
Code to reproduce the problem:

```php
return $this->render('test/index.html.twig', [
     'foo' => new \ArrayObject(['bar' => null]),
]);

{% if foo.bar is defined %}
    {{ foo.bar }}
{% endif %}
```

After running this you get

`E_NOTICE: Undefined property`

which is not the expected behaviour as I specifically test if it's defined before outputting it.

**Comment by linaori** [comment]
Are you sure this is the code being executed?

```php
php > $a = new ArrayObject(['foo' => null]);
php > var_dump(isset($a['foo']) || array_key_exists('foo', $a));
bool(true)
php > var_dump($a['foo']);
NULL
```
Which is the code as I think is compiled from here: https://github.com/twigphp/Twig/blob/84b2eb541026dbd39590ba80269ae7676b1bfc46/lib/Twig/Node/Expression/Name.php#L35-L40

**Comment by yceruto** [comment]
The warning appears when the expression is being evaluated as `$foo->bar`, because [`$object instanceof ArrayAccess && isset($object[$arrayItem])`](https://github.com/twigphp/Twig/blob/caf2caa8f4d24f16e9e01d1e8074d488be0fbbe3/lib/Twig/Template.php#L516) returns `false` in this case, hence the expression is treated as object property instead of array access. https://3v4l.org/qtss2

I think this bug can be solved by using `$object->offsetExists('item')` instead of `isset()`.

**Comment by yceruto** [comment]
The error appears when the expression is being evaluated as `$foo->bar`, because [`$object instanceof ArrayAccess && isset($object[$arrayItem])`](https://github.com/twigphp/Twig/blob/caf2caa8f4d24f16e9e01d1e8074d488be0fbbe3/lib/Twig/Template.php#L516) returns `false` in this case, hence the expression is treated as object property instead of array access. https://3v4l.org/qtss2

I think this bug can be solved by using `$object->offsetExists($arrayItem)` instead of `isset()`.

**Comment by linaori** [comment]
The problem is that it _is_ an object, checking the interface/type would cause additional checks and thus a performance loss. Would it be viable to switch the array_key_exists and isset checks?

**Comment by yceruto** [comment]
@iltar see the linked condition (1.x):
https://github.com/twigphp/Twig/blob/caf2caa8f4d24f16e9e01d1e8074d488be0fbbe3/lib/Twig/Template.php#L515-L517

The interface/type has already been verified, is the `isset()` check that fails. 

Another solution could be change the condition to:
```php
if ((is_array($object) || $object instanceof ArrayAccess) && (isset($object[$arrayItem]) || array_key_exists($arrayItem, $object))) {
```
thus, the `array_key_exists()` check at the end resolves the issue.

> Would it be viable to switch the array_key_exists and isset checks?

I guess there is a performance reason for the current order.

**Comment by stof** [comment]
doing `isset` before `array_key_exists` is indeed done this way for performance reason.

but anyway, the code in https://github.com/twigphp/Twig/blob/84b2eb541026dbd39590ba80269ae7676b1bfc46/lib/Twig/Node/Expression/Name.php#L35-L40 is not about reading `bar`  in your example, but about reading the `foo` variable.

**Comment by yceruto** [comment]
see https://github.com/twigphp/Twig/pull/2749
