### ISSUE TITLE
Autoloader expected class

### ISSUE THREAD

**Issue by EtienneDx** [twigphp/Twig#2747]
Hey, I've been struggling for a few days and no one seems to have the answer on stackoverflow either, so here I am. I've been using symfony 4 successfully till about 5 days ago, when a sudden bug appeared on the online version. I decide to re upload everything but a bug remain, the autoloader doesn't manage to load any class from twig. Looking at the code for the classes, they are all inside some if(\false) conditions, which obviously explains why the classes aren't loading. Is this intended and if so how can I fix my project, or is it an error that happened due to the replacement of require_once by class_exists (the commit was on the 17 of june 2017 so I don't get how comes it stopped working just now). Here's one of the file that causes problem : 
`<?php
namespace Twig\Extension;
class_exists('Twig_ExtensionInterface');
if (\false) {
    interface ExtensionInterface extends \Twig_ExtensionInterface
    {
    }
}`
this is from [https://github.com/twigphp/Twig/blob/2.x/src/Extension/ExtensionInterface.php](url)

Here's my bug report from symfony : 
![image](https://user-images.githubusercontent.com/32039535/45613272-0a7a0700-ba66-11e8-8304-dd28f05d5e7b.png)
.........
![image](https://user-images.githubusercontent.com/32039535/45613293-1e256d80-ba66-11e8-91c7-6da891fe3c52.png)

I really need to get this project working soon, so any help would be apreciated :)

**Comment by linaori** [comment]
Have you verified that the file listed in the error message exists?

**Comment by EtienneDx** [comment]
Yes, I did, it contains the code I included in the post...

**Comment by Tobion** [comment]
The namespaced classes like https://github.com/twigphp/Twig/blob/2.x/src/Environment.php are only there for your IDE and not actually used (which is why they are wrapped in `false`).
Instead, the namespaced classes are just aliases, see https://github.com/twigphp/Twig/blob/c8020aa5d848fcb934b047d85304544b174a95a7/lib/Twig/Environment.php#L970

There should not be any problem normally. I can imagine, that you still have old versions of the classes in opcache and thus the aliases are not loaded. So try clearing opcache.
Are you using the composer autoloader?

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
