### ISSUE TITLE
Use embed within template_from_string

### ISSUE THREAD

**Issue by rubenrubiob** [twigphp/Twig#2761]
Hi,

I am trying to use an `embed` tag in a call to the `template_from_string` function. Summarized, the code is something like the following:

```twig
{% set element = '<p>text text text</p>
                    {% embed "_snippets/_download-item.html.twig" %}
                        {% set download_item_url = "" %}
                        {% set download_item_title = "22 gener 2018" %}
                        {% set download_item_summary = "Suspendisse potenti" %}
                    {% endembed %}'

{{ include(template_from_string(element)) }}
```

When trying to render this, Twig throws an error:

```
Unable to find template "__string_template__54b3a6e2128ff1c07931188225a8717a29c821eab5f09ad82231dfff78713dca"
```

Of course, I have checked that the code works if used directly, without calling `template_from_string`.

Is it possible to use an `embed` within `template_from_string`? If it is not possible, I might write an extension that does what I intend, but I do not see clearly how to do so. Maybe an extension that generates a temporal template in cache —or in memory— that can be loaded within the environment?

Thank you!

**Comment by ericmorand** [comment]
Well, this may be a bug.

The loader tries to load `__string_template__54b3a6e2128ff1c07931188225a8717a29c821eab5f09ad82231dfff78713dca` instead of `_snippets/_download-item.html.twig` and fails since this template is not registered in the loader - and i can confirm it fails with both array and filesystem loaders.

@stof, but isn't the `createTemplate `environment method supposed to add a loader that can resolve that template name?

**Comment by ericmorand** [comment]
This may be coming from that line:

https://github.com/twigphp/Twig/blob/5dd532eed87b6b3b1aec28957dd7a4b67ac6e79a/lib/Twig/Environment.php#L430

Commenting it out solves the issue but I'm not sure of the side effects.

Edit: test suite pass perfectly with that line commented.

**Comment by ericmorand** [comment]
@rubenrubiob, as a workaround, you could come with your own environment subclass that only reimplement `createTemplate` without that line above.

**Comment by rubenrubiob** [comment]
I have checked commenting that line and it indeed works fine.

Meanwhile, I will try the workaround you propose me, waiting for the solution of the issue.

Thank you!

Regards!

**Comment by stof** [comment]
this indeed looks like a bug

**Comment by stof** [comment]
And removing the line you mentioned would create other bugs. This does not look like the right fix.

**Comment by fabpot** [comment]
fix in #2883

**Comment by ericmorand** [comment]
> And removing the line you mentioned would create other bugs. This does not look like the right fix.

@stof, Could you please elaborate? The test suite pass entirely when removing this line and it fixes the bug. One may wonder what is the purpose of this line and why there is no test to ensure that this purpose is fulfilled.

The official fix is really disturbing. Parsing object classname to support runtime needs, I don't even know where to start...

**Comment by stof** [comment]
@ericmorand the testsuite passes because it does not keep using the loader after the embed. Not resetting the loader would leak the embed template for any following usage of Twig (which can create weird issues).

The official fix relies on the fact that the embedded template has already been compiled at the same time than the main template (and so the class is defined). And we have a convention for the naming of class names for embed templates based on the name of the compiled class for the main template. So we can avoid going through `Environment::getTemplateClass` to get the class name based on the template name (which would expect the loader to keep knowing about that name).
