### ISSUE TITLE
[RFC] Added support for classes function

### ISSUE THREAD

**Issue by lyrixx** [twigphp/Twig#2797]
The [`classes`](https://github.com/JedWatson/classnames) function in javascript is quite useful.
Do you think it could be in twig ?
I would port it if you want

**Comment by yceruto** [comment]
Yes, that's something we need often! I did it for some apps in another way, by adding a custom filter `|filter` (for PHP: `array_filter()`) in combination with `|keys|join(' ')`, but definitely a built-in function would be quite useful. 

I'm guessing something like this:
```twig
<div class="{{ class_names({
    'class1': condition1, 
    'class2': condition2,
    'class3': condition3,
}) }}">
    {# ... #}
</div>
```

**Comment by javiereguiluz** [comment]
I like this proposal ... but I'm not a big fan of the proposed function names. Although Twig is for front-end people, it's used by lots of backend people, so "classes" sounds like programming classes, not CSS classes.

Also, front-end people use classes in JavaScript ... so it may be confusing to them too.

What about calling it `css_class()` ? There's no need to use plural because in Twig we always use singular even when the usage is plural (e.g. `include()` and not `includes()`)

**Comment by gharlan** [comment]
Or maybe something more generic, like `join` (maybe confusing with the existing filter with same name?) or `conditional_join`, with explicit separator?

```twig
<div class="{{ conditional_join(' ', 'a-class', 'another-class', {
    'errored': object.errored,
    'finished': object.finished,
    'pending': object.pending,
}) }}">
</div>
```

`conditional_join(separator, ...args)`

**Comment by gharlan** [comment]
> What about calling it css_class() ?

Is it really a "css" class? Isn't it a class for a html element, that can be used in css and js to access that html element?

**Comment by lyrixx** [comment]
It generates a some css classes.

**Comment by fabpot** [comment]
Closing the issue so that all the discussion happens on the PR.

**Comment by stof** [comment]
@lyrixx I think @gharlan is right. It generates HTML classes.
