### ISSUE TITLE
html_attr docs are misleading / unclear

### ISSUE THREAD

**Issue by timglabisch** [twigphp/Twig#2817]
i had a discussion with some of my co workers about escaping strategies and when to use 'html_attr'.

from my point of view, we should add an example when to use `html_attr` instead of `html`.

The docs are saying that:

```
html: escapes a string for the HTML body context.
html_attr: escapes a string for the HTML attribute context.
```

# example 1

following the docs, this wouldn't be best practice, but it seems to be "fine".
https://github.com/twigphp/Twig/issues/2615#issuecomment-370008276

```jinja
{% set untrusted = 'untrusted' %}
<div class="{{ untrusted }}">{{ untrusted }}</a>
```

# example 2

if you stick to the docs this should be best practice?

```jinja
{% set untrusted = 'untrusted' %}
<div class="{{ untrusted | e('html_attr') }}">{{ untrusted }}</a>
```

is there any reason why *example1* is wrong?

**Comment by stof** [comment]
example 1 is quite fine here, because your attribute value is quoted, and the `html` escaping strategy already escapes quotes.

The wrong cases are these one:

- using a dynamic attribute name
- using an unquoted attribute value

That's because in these cases, a lot more thing need to be escaped (spaces and `=` for instance), which is what `html_attr` is doing.

**Comment by fabpot** [comment]
@stof is right. Escaping HTML attributes depends on how you use them (single-quoted, double-quoted, no quotes). I'm closing as there is nothing to do here. I've added a note in #2950 to guide users to some docs about these topics.
