### ISSUE TITLE
Add Twig as standalone application

### ISSUE THREAD

**Issue by alehaa** [twigphp/Twig#2823]
I'd like to use Twig as standalone application for rendering templates with a given dataset, like [mustache](https://mustache.github.io) does. Therefore a standalone application is required.

I already have a similar script in use for private purposes, which doesn't implement anything but reading a JSON file and rendering a given template with this data. I'd like to know, if I could contribute such a script in an PR.

**Comment by yceruto** [comment]
Don't asks to contribute, just contribute! :)
You're free to explain the idea and send code, this is OSS, so you're welcome! :)

**Comment by stof** [comment]
What do you mean by "standalone application" ?

**Comment by stof** [comment]
If you mean the CLI tool like https://mustache.github.io/mustache.1.html I suggest you to build it in a separate package, which would use the Twig engine as a dependency.

But given that Twig is not a logic-less templating engine but a rich extensible engine, running it without allowing to configure any other extensions than the core one does not make much sense IMO.
A standalone application rendering mustache template makes sense because the engine is not extensible.

**Comment by alehaa** [comment]
I like some of the features implemented by Twig, which are not available in e.g. mustache, like `if` or `for` loops.

For rendering e.g. a LaTeX file with a given dataset, the plain Twig engine without extensions is just fine. What I like to achieve is simply running `twig data.json template.tex | pdflatex -jobname=foo“ and getting a compiled LaTeX PDF.

As @stof points out, a separate repository could be used for this. Therefore this issue was meant as a discussion about wheater to add this script in this repo or an extra one.

**Comment by stof** [comment]
IMO, it does not belong to the core, as that is not the way Twig is meant to be integrated in projects (precisely due to the fact that it would not support using extensions).

**Comment by alehaa** [comment]
Ok, I'll put the application in a separate repository. Thanks! :)
