### ISSUE TITLE
Using has* in twig_get_attribute() feels odd

### ISSUE THREAD

**Issue by alexpott** [twigphp/Twig#2833]
https://github.com/twigphp/Twig/pull/1969 added support for hassers on Twig but I think this does not work as expected. Methods called hasSomething are supposed to return Boolean values but twig_get_attribute() is treating them as getters. Very very confusing. For me the logic of behaving the same as https://symfony.com/doc/current/components/property_access.html#using-hassers-issers is flawed.

This means that Drupal is has to work around this to upgrade to Twig 2 - we have to implement a getter so our implementation of a hasser is not called. See https://www.drupal.org/project/drupal/issues/2572605#comment-12967292

**Comment by stof** [comment]
Well, `isSomething` is also returning a boolean. An accessor for a boolean field may not need to be named `get*`.

**Comment by alexpott** [comment]
Yes but `hasSomething` is often used for things that are not boolean whereas `isSomething` is always a Boolean thing.

Examples in Symfony code:
\Symfony\Component\Routing\Route::hasScheme
\Symfony\Component\Console\Input\InputDefinition::hasShortcut
\Symfony\Component\Console\Formatter\OutputFormatter::hasStyle

**Comment by stof** [comment]
but if you have both `has*` and `get*`, Twig already uses the `get*` method as the getter. It only uses `has*` when neither `get*` nor `is*` exists.
So if you use the hasser in combination with a getter, things already work fine.

Adding `has*` as an accepted accessor was added because of cases when a boolean fields makes more sense to be accessed through `has*` than `is*` in the naming.

The only case which could hurt AFAICT is what your expected API contains both the getter and the hasser, but the getter is implemented through a magic method rather than being an explicit method.

**Comment by stof** [comment]
note that removing support for hasser as an attribute accessor cannot be done in 2.x anyway as that would be a BC break (and I don't think it is a change we want to do in 3.x, as support for it was precisely added to make the accessor rules consistent between Twig and the Symfony PropertyAccess component)

**Comment by fabpot** [comment]
Reading this issue, I can understand that it was not necessarily the best decision to support hassers as they have different meaning depending on how one uses them. Unfortunately, this is now part of Twig, so we cannot remove them anymore.
