### ISSUE TITLE
Twig follows semver pattern?

### ISSUE THREAD

**Issue by prhost** [twigphp/Twig#2919]
Because this commits goes totally against the definition of PATCH ☹️

https://github.com/twigphp/Twig/commit/6c91803a9067b5aeab4ab029ce92c34ed72f0467
https://github.com/twigphp/Twig/commit/1dead73882c6e08c084312d20701d5c698c3a7dd

I know Twig 2 is just PHP >= 7.0, but this should have been done at the beginning of version 2.0 and not in a patch, or just for version 2.8 or 3.0.

**Comment by xabbuh** [comment]
What issues do you face after these changes?

**Comment by fabpot** [comment]
These changes are on private methods or final ones, so it should not break anything. Can you tell us a bit more about your issues?

**Comment by prhost** [comment]
the problem is in the instance of `Twig_Source`, I believe that they are not doing the correct treatment of the content passed in the parameter and at some moment passing `null`

https://github.com/octobercms/october/blob/master/modules/cms/twig/Loader.php#L63

![Screen Shot 2019-03-26 at 11 43 02](https://user-images.githubusercontent.com/3984760/55006339-592bcf00-4fbc-11e9-99da-cc00f37f24d6.png)

**Comment by xabbuh** [comment]
This looks like an issue in the loader provided by October CMS which returns `null` as the source of a template instead of a `string`.

**Comment by stof** [comment]
The documented contract of the method was always `@param string $code`, even before. So that is the usage covered by BC rules of semver.
Passing a value not matching the documented signature is undefined behavior (ensuring BC for it would forbid doing any change, as any implementation detail might make something fail for non-string while it was working before).

**Comment by prhost** [comment]
I'm going to report to the October CMS staff. Thanks @xabbuh.

@stof Anyway I understand his argument, but it does not nullify the fact that this modification is not a `PATCH` as it describes the semver rules.

But thanks for return @xabbuh and @fabpot.

**Comment by stof** [comment]
@prhost Semver requires a major version for BC breaks in the public API. The public API of Twig has *always* been to accept only a string for this argument.
Due to PHP limitations, phpdoc has to be used to define the contract for methods for some cases (much more cases in PHP 5.x which did not have scalar typehints). This is part of defining what the public API covered by semver is.
