### ISSUE TITLE
Dynamic block names

### ISSUE THREAD

**Issue by marius109** [twigphp/Twig#298]
Using vars  for block names not working. 

{% set block_name =  "my_block_name"  %}

{% block block_name %} 
     some html ...
{% endblock %}

**Comment by vincentpazeller** [comment]
Sorry for opening a cold case ^^. I think I may have encountered a use case that would benefit from the dynamic block names...

I use Doctrine with single table inheritance (base abstract class = Article, and News + Faq extends Article).

Then, I have created form classes to be able to create News and Faq. But all forms use the same twig template. Then I needed to customize a field template (say article.product) as described [here](http://symfony.com/doc/current/form/form_customization.html#how-to-customize-an-individual-field).

The problem is that, the name of the field changes depending on which form is used. The name will be either news_product or faq_product, so it would be handy to be able to customize my form fields like this to avoid repetitions:

`{%- block '_'~type~'_product_widget'  -%}
    ...
{% endblock %}`

After some research, I solved this by forcing the prefix of the form in the different form type classes using getBlockPrefix, so that all forms will have the same field names, and I can simply customize article_product:

`public function getBlockPrefix(){
        return 'article';
    }`

So just wanted to document this use case which may help someone...

**Comment by stof** [comment]
Block names are part of the structure of the template, and so must be known at compile time. 
Variables are only known at runtime.

**Comment by Vac1911** [comment]
I was attempting to do the same thing and found a solution using the [template_from_string][1] function.

Normally twig is compiled before hand and unchanged at runtime. However the `template_from_string` function will create and compile a template at runtime.

*_items.html.twig*

    {% for item in items %}
     {{ '{% block ' ~ item.name ~ ' %}'}}
     sometext
     {{ '{% endblock %}' }}
    {% endfor %}
    enter code here

*page.html.twig*

    {% embed template_from_string(include('_items.html.twig')) %}
     {% block someItemName %} someDifferentText {% endblock %}
    {% endembed %}

What's happening is the block tags are initially being created as text. Then we use the [include][2] function to get the rendered content of `_items.html.twig`, as a string. Finally, we convert that string to a working template, which we can [embed][3] or [extend][4]. 

(Also posted this on a [stackoverflow question](https://stackoverflow.com/a/71618312/10518765))

  [1]: https://twig.symfony.com/doc/3.x/functions/template_from_string.html
  [2]: https://twig.symfony.com/doc/3.x/functions/include.html
  [3]: https://twig.symfony.com/doc/3.x/tags/embed.html
  [4]: https://twig.symfony.com/doc/3.x/tags/extends.html
