### ISSUE TITLE
 'ignore missing' does not ignore missing templates

### ISSUE THREAD

**Issue by derekalmond** [twigphp/Twig#3085]
This appears like it might well be a Twig bug, on my local, using the version on my branch (v1.38.4 ) adding a made up template to the homepage:

{% set x = 'bad' %}
{% embed x ~ 'ger.twig' ignore missing %}
{% endembed %}

Does not error, removing 'ignore missing' causes it to error…

Upgrading twig/twig (v1.38.4 => v1.42.1)

At which point the ignore missing directive appears to no longer work and the above test fails 

Twig\Error\LoaderError thrown with message "Unable to find template

**Comment by fabpot** [comment]
I've tried several times to fix it but it's really complicated as we don't have enough context when we need it.

**Comment by kitsguru** [comment]
Just tried updating from twig 2.6 to 2.12 and "ignore missing" is not working here either. I reverted to 2.6. Is this going to be fixed?

**Comment by fabpot** [comment]
@kitsguru It will be fixed eventually, but any help would be more than welcome.

**Comment by kitsguru** [comment]
I just tried V3.0.0 and it is broken here as well. I have been looking through the code and can't find a test for "ignore missing". You mention something about not having enough context but it would seem to me that the only context needed is if the attribute is present. If present don't throw an exception.

Am I missing something here? If you could point me in the right direction, I will keep on looking.

As a workaround I am modifying my app and adding a folder called 'missing', adding an array for the embed file instead of a single file and placing a dummy file in 'missing'.

**Comment by TomasVotruba** [comment]
This error still happens nowadays. I'm looking into the version change this happened.

EDIT:

* This is first narrow version change this bug first occurs: v2.14.8 => v2.14.9
* The full diff between those 2 versions:  https://github.com/twigphp/Twig/compare/v2.14.8...v2.14.9
* **So this is the breaking commit:** https://github.com/twigphp/Twig/commit/695423e14e212930099838102c23dc8ee8ac1558

**Comment by fabpot** [comment]
My comment was probably related to another issue 🤷 
Anyway, here is the fix #4340
