### ISSUE TITLE
is_dir for absolute path return false for isolated site

### ISSUE THREAD

**Issue by MarselCoder** [twigphp/Twig#3096]
Throw exception when directory of site is isolated by hosting.
https://github.com/twigphp/Twig/blob/5bfe590de545c791e4c3c98a908f65cc6c79b404/src/Loader/FilesystemLoader.php#L106

Some hostings have option "Isolating site". (Site site_name.com can edit files only inside /www/site.com/). That's why is_dir('/home/p1234/www/site_name.com/...') return false 

Fatal error: Uncaught Twig_Error_Loader: The "/" directory does not exist ("/").

**Comment by ericmorand** [comment]
Well, that's a bug from either PHP or the isolated site feature, no? `/home/p1234/www/site_name.com/` definitely exists, so why would the hosting machine pretend it doesn't?

**Comment by MarselCoder** [comment]
Yes, it's an isolated site feature. An isolated site does not have access to other folders. Even for reading.

Solution: Don't use absolute paths. Use only relative paths like:

    is_dir('../../some_dir/')

**Comment by ericmorand** [comment]
Well, I really think it is an isolated site bug then. Because if your definition is correct ("An isolated site does not have access to other folders. Even for reading."), there is no point that, when asking an isolated site its path, I get '/home/p1234/www/site_name.com'. I should get "/" and it should be resolved by the isolated site file system handler to "/home/p1234/www/site_name.com".

You are proposing using relative paths but how can Twig or any other product guess where the isolated site starts and where it ends? That's a genuine question. I don't know how this feature work.

**Comment by fabpot** [comment]
Let's close as I don't think there is anything to do in Twig.
