### ISSUE TITLE
Twig Stacks support

### ISSUE THREAD

**Issue by Herz3h** [twigphp/Twig#3123]
Is there a way to achieve same thing as [Blade's stack](https://laravel.com/docs/5.8/blade#stacks) feature with twig ? 

Consider this example:

base.html.twig
```
{% block body %}
{% endblock %}

{% block javascripts %}
{% endblock %
```

main.html.twig
```
{% extends 'base.html.twig' %}
{% block body %}
  My content here
  {{ include('path/to/mytemplate.html.twig') }}
{% endblock %}

{% block javascripts %}
<script src="myfristscript.js"></script>
{% endblock %
```

mytemplate.html.twig
```
{% block body %}
  Additional content here
{% endblock %}

{% block javascripts %}
<script src="myseconscript.js"></script>
{% endblock %
```

How do I make it so that mytemplate.html.twig appends content to blocks in main.html.twig

**Comment by lyrixx** [comment]
You should use {{ parent() }}

**Comment by rybakit** [comment]
@Herz3h Take a look at the [Deferred Twig Extension](https://github.com/rybakit/twig-deferred-extension), with the `deferred` block attribute you can postpone block rendering and manipulate its content from any template (see the advanced example in [README](https://github.com/rybakit/twig-deferred-extension#advanced-example)). Also, read this article which describes the same problem the Grav CMS had and how they solved it with this extension: https://getgrav.org/blog/important-theme-updates.

@lyrixx You can't use `parent()` in `mytemplate.html.twig` because it doesn't extend any template.

**Comment by lyrixx** [comment]
I mean using parent in the `mytemplate.html.twig`:

```twig
{% block body %}
{{ parent() }} {# ------------ HERE ------------ #} 
  Additional content here
{% endblock %}

{% block javascripts %}
{{ parent() }} {# ------------ HERE ------------ #}
<script src="myseconscript.js"></script>
{% endblock %
```

https://twig.symfony.com/doc/2.x/functions/parent.html

**Comment by lyrixx** [comment]
@rybakit Oh, I missed that part. thanks

**Comment by Herz3h** [comment]
Thank you very much, didn't know about that extension 👍
