### ISSUE TITLE
Allow multiple classes per single condition in html_classes()?

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#3144]
I've been looking at the [React classnames package](https://www.npmjs.com/package/classnames) which the new `html_classes()` function takes inspiration from.

Looking at this example:

```twig
<body class="{{ html_classes(
    'container',
    'container-ajax': is_ajax_request,
    'page-' ~ category,
    ['logged-user', 'private']: app.user,
    {
        'user-active': app.user.active,
        'user-customer': app.user.hasPurchased
    }
) }}">
```

I'm not sure if this use case (which is supported by React) is supported by our function:

```twig
['logged-user', 'private']: app.user,
```

Setting more than one CSS class for a single condition may come in handy, specially to not repeat the condition when it's complex.

I know that in this example you can do:

```twig
'logged-user private': app.user,
```

But the classes to add could be more dynamic or stored in an array Twig variable.

**Comment by stof** [comment]
> I'm not sure if this use case (which is supported by React) is supported by our function

I don't see it supported by React. I think you are confusing the syntax for computed properties in JS objects (an expression returning a string, wrapped in square brackets) with the support for arrays.
the readme does not have an array classes in the `[`btn-${buttonType}`]: true`.

And Twig already has a syntax for computed properties in hashes (except it uses braces, not square brackets, as we made this in Twig before the feature was added in ECMAScript so we could not take it as inspiration).
Thus, array keys cannot be arrays in PHP (and object properties names cannot be arrays either in JS, so the same argument applies to React classnames) so your proposal is plain impossible.

You could use `(some_array|join(' '))` as key though if you have a dynamic array.

and btw, your snippet also misses curly braces around `'container-ajax': is_ajax_request`, as that's not a valid syntax otherwise.

**Comment by javiereguiluz** [comment]
@stof I made a mistake ... it's not React's `classnames()` but this `class_string()` function for RubyOnRails which was inspired by React: http://www.carlosramireziii.com/a-cleaner-way-to-set-multiple-conditional-css-classes-for-link-to.html

In any case, this is probably an edge case that can be solved differently with the tools already available, so I think we should close. Thanks.
