### ISSUE TITLE
Feature Request: Template Functions or "typed" macros

### ISSUE THREAD

**Issue by alinnert** [twigphp/Twig#3166]
I do know that you can implement functions for Twig templates in PHP, but I'm using Twig with [CraftCMS](https://craftcms.com). It requires you to write an entire Craft plugin just to extend Twig in any way, which is pretty overkill imo. On the other hand my idea is already very close to macros. It's not something crazily new (from a syntax standpoint).

What I would need is basically a macro with two key differences:

- It doesn't print
- Instead it returns a value using a new `return` tag (which can be a number, boolean, array etc. or also a string)

My idea goes like this:

~~~ twig
{% macro silent count(items) %}
  {% set i = 0 %}
  {% for item in items %}
    {% set i = i + 1 %}
  {% endfor %}
  {% return i %}
{% endmacro %}
~~~

And some other template can get the value and still make numeric checks on it:

~~~ twig
{% from "count" import count %}
{% set itemCount = count(someArray) %}

{% if itemCount == 1 %}
  There is one item.
{% elseif itemCount > 0 %}
  There are {{ itemCount }} items.
{% else %}
  There are no items.
{% endif %}
~~~

Other syntax proposals are:

~~~ twig
{% macro function count(items) %}...{% endmacro %}
{% function count(items) %}...{% endfunction %}
~~~

The `import` can work the same way as it does for macros.

What do you think?

**Comment by gmhenderson** [comment]
I use this kind of functionality all the time in my Craft sites. Currently I use a [Craft Module](https://docs.craftcms.com/v3/extend/module-guide.html) to register a custom Twig extension that implements the `return` tag, which I borrowed from [this plugin](https://github.com/marionnewlevant/craft-twig_perversion). This tag allowed me to return values from macros. You could also just install the plugin.

**Comment by ericmorand** [comment]
I think that it all comes to what a templating language is expected to do and what it is _not_ expected to do. Twig is already filled with features that are very detabable for a templating language. And Twig 2.12 is absolutely nonsensical in that regard since it actually provides features that are only resolvable by the system that provides the data like internationalization (should I remind that a templating language is _by definition_ agnostic about the system that is executing it and only dependent on the data passed to the template?), or non-agnostic like CSS inlining - so now Twig is a templating language that renders HTML, right, or can someone explain us the purpose of inlining CSS for JavaScript, plain text or markdown?

Adding function support would make it even less of a templating language and more a programming language.

**Comment by stof** [comment]
@ericmorand Css inlining is part of an extension, not of the core. And indeed, inlining CSS makes sense only for HTML. We never said that it should be used for all templates. Twig is not specific to rendering HTML, but it can definitely be used to render HTML, in which case the CSS inlining feature can be useful.

**Comment by ericmorand** [comment]
@stof, correct me if I'm wrong but `inline_css`, `inky` and the other filters available in Twig 2.12 are in the lanuage reference documentation of Twig:

https://twig.symfony.com/doc/2.x/

Which means they are part of the language itself and not an extension.

Would thay be part of an extension, why aren't they available in another repository with another documentation like any other extension?

**Comment by alinnert** [comment]
@gmhenderson Thanks for pointing out Craft Modules. I've only extended Craft 2 so far which didn't have modules. They're still some work to do for just a tiny function but worth considering if functions in Twig won't make the cut. If I write a module I could just write the functions in PHP instead of Twig.

Btw: Is there some information about Twig 2.12? I found some elements in the docs that got introduced in 2.12 but I can't find any information about that version. No pre-release, no introduction, no change log.

**Comment by stof** [comment]
@ericmorand they are part of separate Twig packages (official extensions, but not `twig/twig` and so needs to be registered).
See the note in the doc page about it needing to install and register the corresponding extension.

**Comment by ericmorand** [comment]
I iget it. There is a difference between the language specifications (aka everything that is part of the core extension) and what is on the _Twig Reference_ documentation. That changes a lot of things for non-official implementations.

I'll se what I can do with that. Thanks for your help.

**Comment by stof** [comment]
There is nothing like a language specification for Twig.

And note that the Twig website also contains the list of all filters and functions implemented in the symfony/twig-bridge. This does not make them part of the core.

**Comment by ericmorand** [comment]
> And note that the Twig website also contains the list of all filters and functions implemented in the symfony/twig-bridge. This does not make them part of the core.

No, but there are identified as _not_ being part of Twig Reference:

_Twig Reference from Symfony
Symfony provides many more features via the symfony/twig-bridge Composer package._

https://twig.symfony.com/doc/2.x/

Which is not the case of the filters that depends on an extension. That means that template designer have to read the full documentation of each tags, filters and operators to make sure they can use it (which is the right thing to do, reading the manual I mean) and should avoid using any of them that is not part of the core extension because they don't know by advance the environment that will compile and render their templates (which is not something that is expected by anybody when reading the title `Twig Reference`).

Do you think it would be possible to have a list grouped by extension to identify clearly what template designers can use safely and what they can't? I can provide a PR if you think it is appropriate.

**Comment by alinnert** [comment]
I'm happy I've been able to not only help improve Twig but also Twing, even if it's in a way I was not expecting at all. 😄

**Comment by fabpot** [comment]
I think that this is going "too far" for being integrated in Twig core. Thanks for the suggestion.
