### ISSUE TITLE
Render properly non breaking spaces

### ISSUE THREAD

**Issue by Jiri-Mihal** [twigphp/Twig#3221]
Hi,

I use standalone Twig and I can't figure out how to properly render `&nbsp;`. I don't want to allow any other html tags or special characters. Ideally if could write my own filter.

```php
$filter = new \Twig\TwigFilter('fixp', function ($string) {
    return preg_replace('/\s(\w)\s/', ' $1&nbsp;', $string);
});
```

Inside a Twig template:
```php
{{ 'Ahoj v Praze.'|fixp }}
```

Desired output with properly rendered non-breaking space:
`Ahoj v Praze.` 

Output I get:
`Ahoj v&nbsp;Praze.` 

Thank you for your help.

**Comment by stof** [comment]
I don't understand what you are asking for. Your code snippet for a filter seems to turn spaces into `&nbsp;` entities (with the config missing related to autoescaping), while your template snippet seems to suggest you want the opposite.

**Comment by Jiri-Mihal** [comment]
@stof Sorry, I corrected my question.

**Comment by stof** [comment]
Well, you filter is probably fine as is (well, assuming your regex is the right one of course. to make things work with auto-escaping, you would have to configure your filter so that escaping is applied before running the filter rather than after. This is done in the core for `nl2br`: https://github.com/twigphp/Twig/blob/e9f5fff78f798528aab1e7282306dcd7327a634a/src/Extension/CoreExtension.php#L198

- `safe` marks the output of the filter as safe for HTML so that the escaping is not applied after it
- `pre_escape` tells the auto-escaper that it should make sure that the input value is properly auto-escaped (just marking the output as safe without being sure that the input is safe would be a security issue due to escaping not being applied at all as the filter is not escaping)

**Comment by stof** [comment]
and of course, to make the filter available, you need to register it in your Twig environment, either through an extension that you register or directly through the `\Twig\Environment::addFilter` method

**Comment by Jiri-Mihal** [comment]
How does it solve my question?
> I don't want to allow any other html tags or special characters.

**Comment by Jiri-Mihal** [comment]
Maybe it's not clear enough from my question. I don't want to allow other html tags or special characters to be not escaped. It means only `&nbsp;` should be raw.

**Comment by stof** [comment]
well, the auto-escaping feature of Twig will handle that already (assuming you haven't turned it off)

**Comment by Jiri-Mihal** [comment]
At first I didn't understand what exactly `pre_escape` does, now I see it. Thanks for your help!

For anyone else who is looking for correct rendering of Czech prepositions. Here is the working Twig filter that properly renders non-breaking spaces and keeps the filter input auto-escaped.

```php
$filter = new \Twig\TwigFilter('fixp', function ($string) {
    return preg_replace('/\s(\w)\s/', ' $1&nbsp;', $string);
}, [
    'pre_escape' => 'html',
    'is_safe' => ['html'],
]);
```
