### ISSUE TITLE
Lazy initializing Function, Filter, Global, ...

### ISSUE THREAD

**Issue by rkrx** [twigphp/Twig#3238]
Currently the definition of twig-functions (and filters and so on) is eager-initializing.

In a recent project I need quite a lot functions and filters, that aren't simple Closures, but Objects with `__invoke`-Methods, that are only sometimes needed (but always declared). Because __DI__.

So I end up having a lot of ...
```
...
$twig->addFunction(new TwigFunction('foo', $container->get(Foo::class)));
$twig->addFunction(new TwigFunction('bar', $container->get(Bar::class)));
$twig->addFunction(new TwigFunction('fooBar', $container->get(FooBar::class)));
...
```

... which is quite a performance-killer. Since `TwigFunction` is final now, I can't simple write a LazyTwigFunction-descendant, where I could put an initializer-closure to work. Like...

```
$lazy = static function (string $className) use ($container) {
    return static function () use ($className) use ($container) { // Layer A
        $obj = $container->get($className);
        return static function (...$params) use ($obj) { // Layer B
            $obj(...$params);
        };
    }
};
...
$twig->addFunction(new LazyTwigFunction('foo', $lazy(Foo::class)));
$twig->addFunction(new LazyTwigFunction('bar', $lazy(Bar::class)));
$twig->addFunction(new LazyTwigFunction('fooBar', $lazy(FooBar::class)));
...
```

Here `Layer A` is called only on first invokation in template-context and `Layer B` is called on every invokation in the template-context.

A better solution would be to have both `TwigFunction` and `TwigFilter` to implement an Interface each and make `Environment::addFunction` and `Environment::addFilter` (and all other methods) to rely on that Interface instead on the final classes.

**Comment by stof** [comment]
Twig already has a feature to separate the implementation of functions to separate objects. That's the `Twig\RuntimeLoader\RuntimeLoaderInterface` (and it already ships with an implementation based on a PSR-11 container).

**Comment by rkrx** [comment]
I can't see how this helps with my lazy initialization issue.

Can you give an example on how you can recognize the call of a not yet defined function and then deliver this function accordingly?

**Comment by stof** [comment]
it would look like that:

```php
$twig->addFunction(new TwigFunction('bar', [Bar::class, '__invoke']); // not sure whether omitting __invoke will work, to be checked
```

And then you would have to configure a RuntimeLoader able to provide the runtime object for `Bar::class`. In your case, as your own code uses `$container->get(Bar::class)`, the built-in implementation based on PSR-11 will probably fit your needs (assuming your container is a PSR-11 one).

Functions must still be defined before being used. But their runtime may be lazy-loaded.

Note that for named arguments to keep working, it is important that the string used to reference the runtime is actually the class name (so that Twig can still do a `new ReflectionMethod(Bar::class, '__invoke')` during template compilation to match the argument names).

**Comment by rkrx** [comment]
This coveres the issue only partly.

While DI indeed works for _functions_, the same declaration method does not work for _filters_ or _globals_, since they are not thrown against the container, I suppose.

Compiled twig-template context for a filter call:
```
call_user_func_array($this->env->getFilter('...filter-name...')->getCallable(), [...parameter...])
```

`getCallable` still returns [string, string] here.

And this only works for classes, not for closures. I would suggest introducing a set of methods for lazy-evaluation:

```
$env->defineGlobalFactory('myGlobal1', SomeFactoryWithInvokeMethod::class);
$env->defineGlobalFactory('myGlobal2', static function (MyProvider $prov, Container $container, SomeClass $someClass) {
    /* ... */
   return $actualGlobalValue;
});

$env->defineFilterFactory('myFilter1', SomeFactoryWithInvokeMethod::class);
$env->defineFilterFactory('myFilter2', static function (MyProvider $prov, Container $container, SomeClass $someClass) {
    /* ... */
    return $actualFilterCallable;
});

$env->defineFunctionFactory('myFunc1', SomeFactoryWithInvokeMethod::class);
$env->defineFunctionFactory('myFunc2', static function (MyProvider $prov, Container $container, SomeClass $someClass) {
    /* ... */
   return $actualFunction;
});
```
Here the 2nd `callable`-Parameter of each `define*Factory`-method is just called once and is used as a factory to emit/return the actual callable to be used in templates.

This callable should always be thrown against a parameter-reflection-interpreter / di-container.

**Comment by stof** [comment]
Filters can also use the runtime loader. This works exactly the same than for functions (and twig tests also support it).

Looking at the compiled call for your existing filter to discover the support for the runtime loader is the wrong way: the generated code will be different when using the runtime. it would be using `$this->env->getFilter('...filter-name...')->getCallable()` anymore (which is the code generated when no better optimized code can be generated, either by using an extension method or a runtime object or a named function or a static method for the callable).

Globals are indeed not something lazy-loaded. But that would be useless anyway: the first thing that `render()` does is getting all globals to merge them with the provided context, so that global variables are available in your context.

Your proposal is not acceptable for Twig, because it hides the signature of the function in a place where Twig cannot inspect it (so named arguments would not work anymore). And your snippet is not realistic either: your factories would have to be functions without any arguments, as Twig would not know about your `MyProvider` and `SomeClass` objects. Forcing to perform autowiring of callable arguments at runtime to match your expectation is a no-go. That would make it impossible to use Twig in Symfony for instance (which never performs autowiring at runtime for performance reasons).
Expecting a PSR-11 container to provide the runtime means that the container is free to instantiate things however it wants internally without Twig having to be aware about it (and so without coupling it to a specific DI implementation).


And this indeed does not allow implementing a lazy-loaded runtime using a PHP closure. But my question is why would you need it absolutely ? Lazy-referencing a closure is not possible anyway as the only way to reference an anonymous function is to have the function itself (because it is anonymous) and so any dependency injected in it would be instantiated already.

**Comment by rkrx** [comment]
> Filters can also use the runtime loader. This works exactly the same than for functions (and twig tests also support it).

Ok, than may be it's a version issue on my side. I will investigate.

> Globals are indeed not something lazy-loaded. But that would be useless anyway: the first thing that render() does is getting all globals to merge them with the provided context, so that global variables are available in your context.

That would be ok as long as the factory is wrapped into a `Future`-like object that will resolve the factory on first touch and this Wrapper is passed around instead of the actual global value. This would mean, that the global value is not _passed by copy_ anymore*, bat that would seem to be a plus in my view.

_*_ I'm not perfectly sure if this is the case right now.

> Your proposal is not acceptable for Twig, because it hides the signature of the function in a place where Twig cannot inspect it (so named arguments would not work anymore).

The function is hidden until the first call is made and then the function is inspectable like before. If you don't need a particular function for a request, you also don't need to know, how it's method signature looks like. You can't use the static sigature for compile-time, since you can't act on source-changes. So, why would late signature-inspection be a problem?

> And your snippet is not realistic either: your factories would have to be functions without any arguments, as Twig would not know about your MyProvider and SomeClass objects. Forcing to perform autowiring of callable arguments at runtime to match your expectation is a no-go. That would make it impossible to use Twig in Symfony for instance (which never performs autowiring at runtime for performance reasons).

I don't feel like this is an issue in 2020 anymore, as the performance-footprint is rather small. And you still have to compare the avoided instantiation of objects never used by a particular request against the eager instantiation that is required now. And at least we can still cache the method-signature in live-environments.

But ok, I get your point. Just leave the autowiring-stuff out. It is not an absolute requirement for me. I could just wrap the autowiring-stuff into the lazy-evaluated closure.

> Lazy-referencing a closure is not possible anyway as the only way to reference an anonymous function is to have the function itself (because it is anonymous) and so any dependency injected in it would be instantiated already.

Could you elaborate on that?

**Comment by stof** [comment]
> That would be ok as long as the factory is wrapped into a `Future`-like object that will resolve the factory on first touch and this Wrapper is passed around instead of the actual global value. This would mean, that the global value is not _passed by copy_ anymore*, bat that would seem to be a plus in my view.
> 
> _*_ I'm not perfectly sure if this is the case right now.

That would require rewriting property access entirely in Twig, to add a layer resolving this lazy globals on any property access in case the variable was a lazy global and not a usual variable. That's insame from a performance PoV. If you have something which is heavy to initialized and which is not used a lot, my suggestion is to define a Twig function returning it rather than injecting it as a variable.

> The function is hidden until the first call is made and then the function is inspectable like before.

Signature must be inspectable during the compilation of the template. Twig named arguments are resolved at compile time, not at runtime (for performance reason).

> I don't feel like this is an issue in 2020 anymore, as the performance-footprint is rather small. And you still have to compare the avoided instantiation of objects never used by a particular request against the eager instantiation that is required now. And at least we can still cache the method-signature in live-environments.

Eager instantiation is **not** required. That's the whole point of the runtime loader.

**Comment by rkrx** [comment]
> If you have something which is heavy to initialized and which is not used a lot, my suggestion is to define a Twig function returning it rather than injecting it as a variable.

Yes, exact. You have to memorize, which globals are heavy and hence behind functions or rather light and therefore actual globals. Not elegant, but the best solution available.

> Eager instantiation is not required. That's the whole point of the runtime loader.

But only if you use _classes_ as functions (or filters) for twig. Closures are not supported, but would feed most natural in most of my situations.

> Signature must be inspectable during the compilation of the template. Twig named arguments are resolved at compile time, not at runtime (for performance reason).

So I suppose, I haven't figured out yet how you managed to track source changes (and therefore changes in function/method-signatures) in dev-environments, but this works somehow magically.
