### ISSUE TITLE
Cache collision.

### ISSUE THREAD

**Issue by SOULITY** [twigphp/Twig#3284]
```
# Case 1.
set twig root ".../root-1"
set twig cache dir "/caches"

.../root-1/tmpl/child.html
{% extends "/tmpl/root.html" %}
{% block body %}
<h1>ROOT-1</h1>
{% endblock %}
```

```
# Case 2.
set twig root ".../root-2"
set twig cache dir "/caches"

.../root-2/tmpl/child.html
{% extends "/tmpl/root.html" %}
{% block body %}
<h1>ROOT-2</h1>
{% endblock %}
```

In this case, "/tmpl/root.html" uses the same cache file.
To avoid this problem I modified the source.
As a result, the problem was solved.
Please solve this problem with your own hands.

```
class Twig\Loader\FilesystemLoader
    .
    .
    .
    public function getCacheKey($name)
    {
        if (null === ($path = $this->findTemplate($name)) || false === $path) {
            return '';
        }

        // $len = \strlen($this->rootPath);
        // if (0 === strncmp($this->rootPath, $path, $len)) {
        //     return substr($path, $len);
        // }
        //
        // return $path;

        return md5($path);
    }
```

**Comment by xabbuh** [comment]
I am not sure if I understood your issue correctly, but do you mean that you have two different applications that share the same cache directory?

**Comment by SOULITY** [comment]
> I am not sure if I understood your issue correctly, but do you mean that you have two different applications that share the same cache directory?

Yes.
Two applications share the same cache directory.
And the same file has the same extends path, "{% extends "/tmpl/root.html" %}" and "{% extends "/tmpl/root.html" %}".
In this case, the "extends file" has a bug that uses the same cache file.

**Comment by fabpot** [comment]
Sharing a cache like you are doing is not supported. You should have 2 separate cache directories.

**Comment by SOULITY** [comment]
> Sharing a cache like you are doing is not supported. You should have 2 separate cache directories.

I need to share one cache directory.
So I modified the source as above, and it works as I want.

If the "extends file" has the same path, the same cache file is used even if the contents of "root.html" are different.

Because of this code.
```
return substr($path, $len);
```

**Comment by stof** [comment]
> I need to share one cache directory.

why do you need that ?

> Because of this code.
> 
> ```
> return substr($path, $len);
> ```

This code is here to make the generated cache portable rather than hardcoding the path in which the project is when generating the cache. This makes it possible to warmup the cache on a machine, and then deploy the project with its Twig cache already warm (and potentially read-only if you don't rely on compiling additional templates dynamically).
So the fact that the cache key depends only on the path relative from the project root rather than on the absolute path is not a bug. It is a key feature.

**Comment by SOULITY** [comment]
@stof 

I understood.
However, due to my service environment, I will modify it individually.
Thank you for your kind answers.

**Comment by stof** [comment]
Well, if your requirement is that only a single folder is writeable for the cache, this does not prevent you from separating the cache folders of both projects: `/writeable-folder/project-1/` and `/writeable-folder/project-2/` could be your Twig cache folders.
That's why I'm trying to understand what could force you to share the Twig cache between projects.
