### ISSUE TITLE
Issue when accessing array keys that start with a number

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#3316]
Hi all! In a Symfony app I have a class like this:

```php
class SomeObject
{
    public function getSomething(): array
    {
        return [
            '32bit' => '...',
            '64bit' => '...',
        ];
    }
}
```

However, if I try to do this in a Twig template, it doesn't work:

```twig
{{ someObject.something.32bit }}
```

It works like this:

```twig
{{ someObject.something['32bit'] }}
```

If the key is `bit32`, I can use the first syntax too `{{ someObject.something.bit32 }}`

Is this done on purpose to match the restriction of PHP property names (they can't start with a number) ... or could this be considered a bug? Thanks!

**Comment by stof** [comment]
identifiers are not allowed to start with a number in Twig (as well as in many other languages). I think this is done to avoid ambiguities in the syntax too.

Btw, try the same in Javascript (which has the same `.` and `[]` notations to access properties in objects) and you will get the same limitation.

**Comment by redreinard** [comment]
php is just fine with identifiers that start with numbers:

```
$x = 123;
$$x = 'a';
echo ${123};
```
or even simpler
```
${1} = 'hello';
echo ${1};
```

I find the comparison to JavaScript interesting when twig is written in PHP and mostly used from PHP? Calling that an "identifier" is a bit misleading too. It's an array index. Twig is choosing to interpret it inconveniently as an identifier. If there is no technical reason (like parsing issues), then i find it arbitrary to disallow this on purpose.

**Comment by stof** [comment]
@redreinard no. It is an array index in the PHP values. But in the Twig syntax `something.32bit`, the `32bit` part is an identifier here (`array index` is not something that exists in the *syntax*.

Also, the equivalent  in PHP would be `$123`, not `${123}`. The `${}` notation to access variables is precisely a syntax allowing arbitrary expressions instead of only identifiers (and the equivalent feature in Twig is the `attribute` function).


> I find the comparison to JavaScript interesting when twig is written in PHP and mostly used from PHP?

We are talking about the syntax of the language here, not about where it is called from. And Twig expressions are actually closer to JS expressions than to PHP ones (see the list and hash literals, the `.` operator, etc...)

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because the current behavior is expected. Thanks!
