### ISSUE TITLE
Spaces removed between text and twig

### ISSUE THREAD

**Issue by ShaneSchroll** [twigphp/Twig#3358]
When writing:
`<p>Pest Control in {{office_name}}, {{office_state}}</p>`
with spaces in-between the text and twig tags, it results in this now:
"Pest Control inManhattan,Kansas" without the space between "in" and the commas, whereas before the spaces worked normally. Removing the spaces and adding `&nbsp;` between text and twig fixes this issue for now.

**Comment by xabbuh** [comment]
Can you create an example that allows to reproduce this? On https://twigfiddle.com/vfzs61 it works as expected.

**Comment by ShaneSchroll** [comment]
Weird, I just checked my Live version against my local version and it is working fine on the live one... Very odd that it is only affecting my local copy. I'm using a standard WordPress php file as the controller and then letting Timber render the view via the associated twig file, local and production code are identical at this time.

**Comment by mdruilhe** [comment]
I had the exact same problem : was working fine on one installation, but not on another (same server, same code and same twig version).
The difference was PHP version : reverting back from PHP 7.4.9  to PHP 7.3.21 fixed the problem.
HTH.

**Comment by boonkerz** [comment]
Same Issue here

**Comment by boonkerz** [comment]
downgrade PHP Version works

**Comment by Wohlstand** [comment]
The downgrade of PHP is a workaround, the issue is still being here. At me, I run PHP 7.4.7, and the bug is still reproducible.

I have next:
```
<dl class="icon {{TOPIC_IMG_STYLE}}">
```

and I get:
```
<dl class="icontest">
```

but should be:
```
<dl class="icon test">
```
but, seems this would fix an issue:
https://github.com/twigphp/Twig/commit/841906b1103599291a72044fcde3aafd9f2272f8
I'll try at me locally, will it work or not...

EDIT: Nope, didn't help...

One note that at me is phpBBex used which has some old Twig version (I don't know which one) inside, and I trying to fix the issue. Anyway, running new Twig with hand-made dummies works perfectly. Maybe the bug at the side of phpBB's lexer that converts own code into Twig-compatible? :thinking:

**Comment by stof** [comment]
if you don't run the latest Twig, please upgrade to latest Twig first. Otherwise, no support will be provided (we won't spend time trying to resolve bugs that have already been fixed).
Also, this must be something reproduceable with Twig itself. If a custom phpBB lexer is necessary to trigger the bug, that's where the bug should be reported.

**Comment by Wohlstand** [comment]
At me locally with the latest Twig, it works fine, however, I trying to fix my copy by myself. I need at least a hint to let me easier figure what the actual bug is: an incorrect regular expression that accidentally takes the spaces at the left side or an unnecessary trimming that makes the loss of important spaces in the text? The fact on PHP 7.3 the thing works fine, but on PHP 7.4 it causes loss of important spaces.

At me, the forked phpBB version called phpBBex. I do patching it by myself because its original developers aren't working on it so much. So, I'll build the separated copy of a forum engine to give an attempt to upgrade the Twig on it... It seems a really old copy of Twig (the phpBBex is based on phpBB 3.1.9).

**Comment by Wohlstand** [comment]
Okay, just now I backported the `whitespace_line_trim` and `whitespace_line_chars` from this file https://github.com/twigphp/Twig/blob/3.x/src/Lexer.php include conditions and new content of regexes array, and the issue getting been completely solved!

The change I made if anyone needs: https://github.com/Wohlstand/phpbbex-wohlsoft/commit/873beb1dfaf226b7d9ed197a95edf3b641aadfda

**Comment by jakimoff** [comment]
In your Twig class you find some like that 

`if (isset($this->positions[2][$this->position][0])) {
            $text = rtrim($text);
        }`

you have to change it

`if (isset($this->positions[2][$this->position][0]) && ($this->options['whitespace_trim'] === $this->positions[2][$this->position][0])) {
            $text = rtrim($text);
        }`

**Comment by jap1968** [comment]
Same problem here wit an old project using Twig 1.x **with no options to update**. So far, we have solved the problem inserting the html code for spaces (normal ones, not the nbsp) where necessary in the templates. I mean:

`<p>Pest Control in &#32; {{office_name}}, &#32; {{office_state}}</p>`

**Comment by giazach** [comment]
[jakimoff](https://github.com/jakimoff) your solution works! thank you!

**Comment by MateiSorin** [comment]
> [jakimoff](https://github.com/jakimoff) your solution works! thank you!

**Comment by Arasil** [comment]
> [jakimoff](https://github.com/jakimoff) your solution works! thank you!

**Comment by DaveJWilcox** [comment]
[jakimoff](https://github.com/jakimoff)  It works for me too! I am lumbered with Twig from 2015.  Thank you so much, you've saved me a huge task.
