### ISSUE TITLE
Imported macros get nuked after using embed

### ISSUE THREAD

**Issue by TRowbotham** [twigphp/Twig#3385]
PHP version: 7.0.2
Twig version: 2.12.5
Fiddle: https://twigfiddle.com/iuo5db

For some reason, globally importing macros get removed from the current template's scope/context after an embed tag is used. This seems to only affect PHP versions 7.0.0 - 7.0.2.

**Comment by stof** [comment]
an {% embed %}` tag defines an (anonymous) included template, so imported macros are separate *inside* that tag. But it should not affect what happens after the end tag.

If this is really happening on PHP versions from 7.0.0 to 7.0.2 but not on PHP 7.0.3+, I would say that this is a bug in PHP itself. And then, I would say there is nothing to be solved in Twig: the whole 7.0 branch is EOLed since January 2019, and 7.0.2 is far from being uptodate inside that branch (the last 7.0 release is 7.0.33).
