### ISSUE TITLE
Variables priority

### ISSUE THREAD

**Issue by ludekbenedik** [twigphp/Twig#3396]
Hi,

I found problem with variables priority. Maybe it is a "feature" and no a bug, but I think the actual behaviour is not ideal.

```twig
{# layout.html.twig #}
{% set var = 2 %}
{% block body %}{% endblock %}

{# page.html.twig #}
{% set var = 1 %}
{% extends 'layout.html.twig' %}
{% block body %}{{ var }}{% endblock %}
```

The result of rendering of page.html.twig is **2**. This is a simple example, but problem is when a variable is defined in a controller and a layout use same variable name. Third party controllers do not know about variables in layouts. I must use special variable names in layouts (menu rendering, ...).

I think the layout should only add new variables, but do not replace existing variables.

 * https://twigfiddle.com/bcacoz
 * Twig version: 3.0.5

**Comment by stof** [comment]
Code outside blocks in the child template is executed *before* the code in the parent template. So that's expected (doing the opposite would make the handling of assignments very hard to specify, as we would have to make the previous assignment win over the current one in some cases).

the solution to avoid variable conflicts in parent templates is to limit the scope of these variables, so that they are used for the part needing them (the menu rendering) but don't leak elsewhere by being in the scope when rendering blocks of the child templates.
There is 3 ways to create a new scope in Twig:
- the `{% with %}` tag (that's its only purpose)
- the `{% block %}` tag (blocks have an isolation scope, so any variable assignment done inside a block have no effect outside it)
- the `{% macro %}` tag also creates a new scope (but is not a solution for your problem).

So to allow the menu rendering to use any variables it needs without conflicts with child templates, you would wrap it either in a `block` tag (if there is a use case to allow child templates to override the menu rendering) or in a `with` tag (better if you don't want to allow overriding, and probably a very little bit faster at runtime as it does not need to resolve and call the block)
