### ISSUE TITLE
Objects with magic __call and implicit getter

### ISSUE THREAD

**Issue by althaus** [twigphp/Twig#342]
Hey there,

I've encountered a problem with the handling of magic getters. I'm currently using a setup similar to http://www.php.net/manual/en/language.oop5.overloading.php#103478.

I've got an object with a real protected property _myprop_ and a magic __call()_ method which will check for calls to _getMyProp()_. When I now want to access _object.myprop_ in Twig this will fail.

If I add an ___isset()_ method, Twig tries to directly access the protected property. If not, it tries a magic _object.myprop()_ call. Both tries will fail.

I fixed it on my end for now, with providing a magic getting without the "get", but it'd be nice, if Twig could handle this somehow. Otherwise tell my if there's an error in my approach?

You can easily reproduce it with the linked code example and trying to access foo.a in a Twig template.

Cheers
Matthias

**Comment by homersimpsons** [comment]
Hi, sorry for "reopening" this ticket but I've got this problem too.
Let's explain:
1. I use https://github.com/KnpLabs/DoctrineBehaviors to get my entities translations
2. Before I used : `{{ entity.translate(app.request.locale).name }}` to display the name matchnig the current locale
3. Now I use a magic `__call` to get this easier (comming from [that thread on StackOverflow](http://stackoverflow.com/questions/17409580/how-to-print-translatable-data-in-sonata-admin-with-doctrinebehaviors-from-kpnla):
`public function __call($method, $arguments)
    {
        return $this->proxyCurrentLocaleTranslation($method, $arguments);
    }`
4. That means that now I should be able to call my entity translation using  `{{ entity.name }}` but this fail with `"Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'AcmeBundle\Entity\EntituTranslation' does not have a method 'name'"`
5. But calling `{{ entity.getName }}` do works with that method.

Can you check out a way to be able to magic display using a `__call` function? (because I found this even more beautiful than the previous way, and will help a lot people translating their database)

**Comment by robfrawley** [comment]
What your asking for, while technically viable, would require countless additional calls to be performed, and this would be a performance penalty for the 99.9% of people who do not require such special handling. Therefore, IMHO, its going to be dead in the water.

**Comment by homersimpsons** [comment]
@robfrawley Okay, thank you for your reply.
Do you think this can be added as a [Twig Extension](https://github.com/twigphp/Twig-extensions) ?

**Comment by Rud5G** [comment]
Is it possible to use: `{{ attribute(object, method) }}` ?
