### ISSUE TITLE
Twig 2 - "raw" filter extremely slow

### ISSUE THREAD

**Issue by toxpal** [twigphp/Twig#3465]
I had problems with some pages being rendered extremely slowly for months, and only today I realized it's caused by **raw** filter.

The code:
`{{ some_var_text|raw }}`

If **some_var_text** is short (contains several words), it works perfectly. However, on specific pages **some_var_text** is a long text (5-6 pages in A4 format), and it takes up to 5 seconds to render this text when using **raw**. If I remove this filter, page is rendered in just a second.

Hence, I believe there's something wrong about **raw**. In case someone wonders why I need to output such long text, it's because this text is contract preview (and most contracts contain lots of text, as you know). I can't output text without using **raw** because it contains some HTML stuff (like bold or italic text, a few tables and lists, etc.)

**Comment by stof** [comment]
this looks weird to me, as `raw` is a no-op at runtime. the difference is that it removes the auto-inserted `escape` filter, which means it will actually *remove* work.

When you say that rendering is extremely slow, are you talking about the server-side time, or about the time to render the page in the browser ? If this is the second case, I could make a guess: adding the `raw` filter allows your huge HTML to appear in the DOM (making the DOM huge) instead of having a DOM containing a single (huge) text node with all your content. And the size of the DOM impacts the performance in the browser. But then, that's not an issue of Twig but an issue of the rendering of your page in the browser.

**Comment by toxpal** [comment]
It's the second case (takes lots of time to render page in browser).

Your comments about DOM were very useful. I copied/pasted whole HTML stuff into template directly for testing purposes (using `{% autoescape false %}` tag) and found that content is still rendered extremely slowly in browser.

Then I performed more tests and found that if I remove all the TWIG code from template, pasted HTML is rendered super-fast. Which means the issue is not related to DOM being huge.

Finally, I started debugging each part of TWIG template (with hope to find which function/filter causes slow rendering) and found that it's not TWIG itself, it's html-compress-twig extension ( https://github.com/nochso/html-compress-twig ). Once I disabled it, everything started working instantly. Super-fast rendering even with **raw** filter.

I will probably test another minify plugin ( https://github.com/voku/html-compress-twig ) to see if it causes any problems with **raw**. If it does, will switch to plain TWIG without extensions.

Thank you for giving me a hint.

**Comment by fabpot** [comment]
Let's close here then. Thanks for the discussion.

Out of curiosity, is it really useful to use an HTML compressor/minifier? Especially if you enable HTTP compression?

**Comment by toxpal** [comment]
Well, when caching is enabled, minified HTML helps. Personally I can't spot a huge difference myself, but testing with Google Page Speed and/or GTMetrix clearly shows that minification reduces page load time.

**Comment by stof** [comment]
For reference for anyone reading this in the future, this is not the `raw` filter being slow. this is https://github.com/nochso/html-compress-twig being slow with a complex DOM (the difference observed due to `raw` being only that the auto-escaping applied on the variable containing HTML turned that into a simple DOM containing one huge text node instead of a complex DOM).

**Comment by toxpal** [comment]
Also worth mentioning (if someone reads this in future) that I tested https://github.com/voku/html-compress-twig and this one works fine. Be aware that it doesn't compress inline JS (nochso extension did so), but at least it works fast with large and complex DOM.
