### ISSUE TITLE
self imported macro are deprecated

### ISSUE THREAD

**Issue by Colir** [twigphp/Twig#3482]
Hello.
Could someone please give me some information about the use of macros when they are defined and called in the same file.

I have the following code

```
{% if elem.acf_fc_layout == 'text' %}
	{{ _self.wrap_html(full_width, elem.body) }}
{% endif %}

{% macro wrap_html(full_width, content) %}
	{% if full_width == true %}
	<div class="row">
		<div class="col-md-10 col-lg-8 col-xl-7">
	{% endif %}
	<div class="c-editorial">{{ content }}</div>
	{% if full_width == true %}
		</div>
	</div>
	{% endif %}
{% endmacro %}
```

But this one raises the following warning:
`"Calling "wrap_html" on template "/components/blocks/section_layout.html.twig" from template "/components/blocks/section_layout.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0."`

I don't understand this warning because my macro is defined and use in the same file, so according to the doc, i can directly use it by using the keyword "_self"...

Thank you.

**Comment by stof** [comment]
this looks like a shortcoming of the deprecation warning in 1.x related to the fact that `_self` changes meaning in Twig 2.0 to allow direct macro calls.
Twig 1.x does not have a special behavior for `_self.wrap_html()`. the call is indeed done through the deprecated way of calling macros, due to `_self` being the `Twig\Template` instance.

The easiest way to avoid such deprecation warning would be to migrate to Twig 2.x or 3.x instead of sticking to Twig 1.x. Given the amount of time since the releases of 2.0 and 3.0, I'm not sure doing a big refactoring of 1.x to detect such usages is actually worth it.

**Comment by fabpot** [comment]
I agree. Let’s close.

**Comment by Colir** [comment]
OK, great.
Thank you

**Comment by stof** [comment]
One of the reason is actually that `_self.wrap_html` was indeed not working at all in 2.0.0. Support for calling own macros with `_self.*` was added in a later 2.x release.
So the deprecation notice is not even wrong in 1.x.
