### ISSUE TITLE
Use strict types everywhere

### ISSUE THREAD

**Issue by cypherbits** [twigphp/Twig#3489]
Most projects are moving to implement strict types everywhere. For security, convenience and other goals. We should do it on Twig too. 

declare( strict_types = 1 );

**Comment by stof** [comment]
strict_types is not adding anything related to security.

And the Symfony core team decided not to use it, because it is not helping convenience either. It will often lead to cases where you end up writing an explicit cast instead of the automatic type coercion, but an explicit cast is **less typesafe** as the type coercion has some rules about when it is safe to cast (and these rules are getting better in newer PHP versions).
