### ISSUE TITLE
Feature Request : format HTML before sending response

### ISSUE THREAD

**Issue by Nayte91** [twigphp/Twig#3537]
Hello,
Here's the 'problems' that make me thinking about this feature :

1. I want a well formated HTML when sending, with perfect line returns, whitespace, indentations. When I look at the source code of a page generated by Symfony, I don't want to see a cacophony,
2. I don't want to fight with Twig too much to reach such a common and framed result, so whitespace trimming, line whitespace trimming, spaceless variations of my {% %} and {{ }} blocks are low valuated fights.

So I wonder how much it can take for a php function to format HTML - after twig templating work and before sending response - the standardized way ? How much cost for a auto https://webformatter.com/html handled on serv side ?

If this is affordable in term of milliseconds, I feel like it can be a good tradeoff; get rid of some complexity in Twig API, letting developers to indent the template files the way they want, and still provide a perfectly format result.

I guess this Feature Request can fit more on the http foundation side, as Twig can template mails and stuff, outer of HTML. Maybe having a new, named parameter $format = true in the AbstractController->render() method can be better, but as I'm not sure, it's maybe better here for a start.

Thank you for your time considering this,

**Comment by stof** [comment]
Well, the answer is easy: do that after calling Twig. Twig itself is not responsible for anything related to the Response of Symfony, so there is no reason for Twig to be responsible for that.

Note that I would vote against a `$format = true` parameter in the `AbstractController->render()` method in Symfony. Most projects don't care about pretty indentation of the HTML. Browsers don't care about it, and a human wanting a perfect indentation could do that client-side the one time they want it instead of forcing the server to do extra work for all pages. Even if you find a very performant HTML formatter, running it will still be slower than doing nothing.
If you want your project to have that behavior for your pages, create your own `render` helper (having to duplicate the method of FrameworkBundle to add a step in the middle is not a big deal, as the method does not contain any complex logic: https://github.com/symfony/symfony/blob/d1b81fbc324cf5703f44276021ee98f6c74f4b93/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L257-L267)

**Comment by fabpot** [comment]
I'm going to close as this is not related to Twig.

**Comment by Nayte91** [comment]
DO we agree there is NO room in the Twig's juridiction to handle such a feature ? For example after generating the template/before giving it back the the framework ?
Otherwise, sounds legit to close.

**Comment by stof** [comment]
@Nayte91 processing the output of Twig is something that belongs to the caller. There is no point trying to hook into Twig (which would probably require a new dedicated extension point in Twig) for that.
