### ISSUE TITLE
[RFC] Anonymous blocks

### ISSUE THREAD

**Issue by Bilge** [twigphp/Twig#3572]
This proposal seeks to support anonymous blocks: blocks without a name argument. That is, `{% block %}` (without a name) would be a valid block tag. Consider the following simple and contrived example with named blocks.

```twig
{# button_group.twig #}
<div class="button-group">
    {% block buttons %}{% endblock %}
</div>
```

```twig
{# my_template.twig #}
{% embed 'button_group.twig' %}
    {% block buttons %}
        <div class="button">Button 1</a>
        <div class="button">Button 2</a>
        <div class="button">Button 3</a>
    {% endblock %}
{% endembed %}
```

In this example we only declare a single block, so the name of the block isn't needed to distinguish it from other blocks. In any case, the anonymous block can be thought of as a block that has a name but whose name is empty. As such, is would be invalid to specify two anonymous blocks since they would share the same (empty) name. However, applying the anonymous block in this case can be used to simplify both templates as follows.

```twig
{# button_group.twig #}
<div class="button-group">
    {% block %}{% endblock %}
</div>
```

```twig
{# my_template.twig #}
{% embed 'button_group.twig' %}
    <div class="button">Button 1</a>
    <div class="button">Button 2</a>
    <div class="button">Button 3</a>
{% endembed %}
```

Eliminating the name made a small difference to our `button_group.twig` template, but we were able to eliminate the entire block tag pair from `my_template.twig` and reduce indentation by one level. This would be possible under this proposal because of the following additional change: normally, templates that embed or extend can only declare block tags, but under this proposal it would also support and collect content outside any block declaration and treat it as content for the anonymous block.

It would still be possible to include named blocks as normal as in the following example that mixes named and anonymous blocks.

```twig
{# button_group.twig #}
{% if block('title') is defined %}
    <h1>{% block title %}{% endblock %}</h1>
{% endif %}
<div class="button-group">
    {% block %}{% endblock %}
</div>
```

```twig
{# my_template.twig #}
{% embed 'button_group.twig' %}
    {% block title %}My buttons{% endblock %}
    <div class="button">Button 1</a>
    <div class="button">Button 2</a>
    <div class="button">Button 3</a>
{% endembed %}
```

**Comment by Bilge** [comment]
Since this RFC seems to have been overlooked, I hope you don't mind some pings, @stof @fabpot. I find myself keep wanting to do this when I want to inject markup into mini-templates (i.e. components) and the name given to the single, named block is just arbitrary and superfluous.

**Comment by stof** [comment]
Your proposal is a big BC break (without any possible migration path, because child templates are allowed to have some stuff outside blocks (as long as it does not output something, so declaring variables for instance, that will be available in the parent template). So automatically collecting top-level content into an anonymous block won't work well. Also, this is ambiguous syntax if you still want to allow overriding other blocks without making them part of the anonymous block (remember that blocks can be nested).

> ```
> {# button_group.twig #}
> {% if block('title') is defined %}
>     <h1>{% block title %}{% endblock %}</h1>
> {% endif %}
> <div class="button-group">
>     {% block %}{% endblock %}
> </div>
> ```

This example is quite broken anyway (not counting), because `{% if block('title') is defined %}` will always be true (the block `title` is defined in that template).

**Comment by Bilge** [comment]
If child templates could not previously have any output, but with this proposal they can, I do not see how that can be a BC break. If they were emitting output before, it would be an error, so no working solution is doing this currently.

**Comment by stof** [comment]
@Bilge but if you have a `{% set foo = 'bar' %}` node in the AST, should it go inside the collected block or stay a child of the root node in the AST ? And if you have a `{% block foo %}`, is it a child of the root node or a child of the anonymous block node in the AST ? Your proposal makes the parsing of a template ambiguous.

**Comment by Bilge** [comment]
You are right I have not considered blocks within blocks. I have never seen this documented or used in practice. Do you have any practical examples of this usage?

**Comment by stof** [comment]
> You are right I have not considered blocks within blocks. I have never seen this documented or used in practice. Do you have any practical examples of this usage?

the most common use case is when you have multiple levels of inheritance: a template extends another one, and defines some blocks to allow its own children to extend more places. I have hundreds of such cases in my project.

**Comment by Bilge** [comment]
I suppose, in the worst case, we could just permit the child to declare its anonymous block in the same way as the parent, i.e explicitly. That way there is no ambiguity.

```twig
{# my_template.twig #}
{% embed 'button_group.twig' %}
    {% block title %}My buttons{% endblock %}
    {% block %}
        <div class="button">Button 1</a>
        <div class="button">Button 2</a>
        <div class="button">Button 3</a>
    {% endblock %}
{% endembed %}
```

It's not as nice, of course.

**Comment by stof** [comment]
```twig
{% extends 'parent.html.twig' %}

{% set var_from_child = true %}

{{ 'foo' }}

<button>{% block button_text '' %}</button>

{% block title 'foo' %}

{% if a %}
    {% set has_a = true %}
    {% block not_allowed '' %}
{% endif %}
```

This will produce the following AST today (before throwing the Syntax error instead of actually instantiating the ModuleNode in the forbidden state, which is where the auto-collecting would probably have to happen in your proposal)

```yaml
ModuleNode
  blocks: ['button_text' => BodyNode(...), 'title' => BodyNode(...), not_allowed => BodyNode(...)]
  parent: ConstantExpression('parent.html.twig')
  body: BodyNode [
    Node           # empty node produced by the parsing of {% extends %} which has a special handling to fill the parent
    TextNode("\n")                                     # ignored today
    SetNode(name: var_from_child, value: ConstantExpression(true))
    TextNode("\n")                                     # ignored today
    PrintNode(ConstantExpression('foo'))
    TextNode("\n<button>")                      # invalid today
    BlockReferenceNode('button_text')                  # ignored today
    TextNode("<button>\n\n")                    # invalid today
    BlockReferenceNode('title')                        # ignored today
    IfNode
      condition: VariableExpression('a')
      then: BodyNode [
        SetNode(name: var_from_child, value: ConstantExpression(true))
        BlockReferenceNode('not_allowed')       # invalid today, because nested
      ]
  ]
```

If we were trying to wrap some of the content in an implicit block, which content would this be ?

Today, any node implementing NodeOutputInterface (we have 5 of them in core, TextNode, PrintNode, IncludeNode, EmbedNode and BlockReferenceNode) is forbidden in the body of a ModuleNode having a parent with these exceptions:
- anything nested inside a NodeCaptureInterface (only SetNode in core) is allowed
- whitespace-only TextNode are skipped
- top-level BlockReferenceNode are skipped (considering that we only want the declaring part of such `{% block %}` tag, and not the referencing part

Nodes that are not implementing NodeCaptureInterface are traversed as part of this filtering to apply the rule to their children (note that the body of blocks are not descendants of the body of the ModuleNode).

So you can have complex AST tree at the top-level (if what you do inside them is no printing something), which runs before rendering the body of the parent when executing.

And even if we allow to define the anonymous block explicitly, this only allows us to infer cases where we should not do the implicit wrapping, but does not tell us what to do in other cases (and the only BC solution is to never wrap implicitly, as the current behavior is not to wrap).
Wrapping implicitly only when we encounter a case that is invalid today would be bad for DX. It would turn on implicit wrapping silently when doing mistakes (which will then be a WTF if the parent does not ever render an anonymous block).

And this is not even counting the other issue: how does it work to reference that anonymous block to render it, when multiple level of inheritance is involved ?

**Comment by Bilge** [comment]
If a child provides an anonymous block to a parent that does not render an anonymous block, this should still be treated as an error. This avoids the WTF case because if it _does_ render it, you will see the mistake (since it will be rendered _somewhere_, albeit perhaps in a different block than anticipated).

Having not spent enough time analysing internals, I suppose if you believe it is not feasible then perhaps it is not, which is a shame.

**Comment by stof** [comment]
@Bilge that's totally unexpected to me, because children are allowed to define blocks that the parent does not care about.
and it still does not solve the issue of knowing *unambiguously* when to wrap things (and what to wrap) in an implicit block.
And also not how this works with multiple levels of inheritance.
