### ISSUE TITLE
Abstraction for Twig\Environment for better extendability

### ISSUE THREAD

**Issue by m-vo** [twigphp/Twig#3606]
The `Environment` class contains quite some complexity and is used directly in Symfony at lots of places. As there is no interface, extending its functionality in a cooperative way (decorating within a bundle) is impossible.

In my case I need to dispatch an event pre/post render. I'm left with replacing the service with my own that extends from the class.

Is there a way out? Even if there would be an interface, the class still has ~60 public methods. :upside_down_face:  
Maybe this monolith can be split into different concerns in the future?

**Comment by stof** [comment]
Well, Twig exposes lots of supported extension points. Replacing the environment itself is not one of them.

**Comment by m-vo** [comment]
Would you be fine with adding pre/post render events?

**Comment by fritzmg** [comment]
👍 for pre/post render events. I always assumed they were already there actually 🙃

**Comment by stof** [comment]
What is the use case for those events ?

**Comment by m-vo** [comment]
> What is the use case for those events ?

Adjusting the context before rendering and the rendered output after. These are typical scenarios in a CMS where extensions must be able to alter (all) templates even without knowing beforehand that they exist.

**Comment by stof** [comment]
If the goal is to inject some variables in all templates, there is an extension point for that: a Twig extension implementing `Twig\Extension\GlobalsInterface`
If the goal is to modify the template source before compiling the template, this should be done by decorating the loader, not the environment. Or maybe by writing a Twig extension registering a node visitor to modify the AST instead of the source.

Decorating the environment will *not* work for such cases, because it would only apply to template rendering calls done through your decorator, but not to other template rendered from another template (with `include()` or other Twig constructs)
