### ISSUE TITLE
Override blocks defined in a template embedded by the base template?

### ISSUE THREAD

**Issue by PC-COLLEGE-Training** [twigphp/Twig#3665]
> base.html.twig
```
{% block css %}
{% endblock %}

{% block html %}
{% endblock %}
```

> base.email.html.twig
```
{% extends 'base.html.twig' %}

{% block css %}
    <style>body { font-size: 11pt; }</style>
{% endblock %}
{% block html %}
    {% if true %}
        {% embed 'confirmation.html.twig' %}
        {% endembed %}

        {% block baseoverride %}
            BASE
        {% endblock %}
    {% endif %}
{% endblock %}
```

> confirmation.html.twig
```
{% block suboverride %}
    SUBCONFIRM
{% endblock %}
```

> reconfirmation.html.twig
```
{% extends 'base.email.html.twig' %}

{% block suboverride %}
    OVERRIDECONFIRM
{% endblock %}
{% block baseoverride %}
    SUB
{% endblock %}
```

The output is:
```
<style>body { font-size: 11pt; }</style>
CONFIRM
SUB
```

The `baseoverride` block defined in the template extended from is overridden, but the `suboverride` block in the template embedded by the base template is not. How would I go about overriding that block?

**Comment by stof** [comment]
You cannot. An embed tag is really defining an anonymous template (embedded inside the main one), so it has its own block definitions. And so child templates of the main templates cannot hook into it.

This is similar to how a child class in PHP cannot override protected methods of an anonymous class defined inside the parent class:

```php
class Confirmation
{
    public function render(): string
    {
        return $this->suboverride();
    }

    protected function suboverride(): string
    {
        return 'SUBCONFIRM';
    }
}

class Base
{
    public function render(): string
    {
        $embeddedConfirmation = new class extends Confirmation {
        };

        return $embeddedConfirmation->render() . PHP_EOL . $this->baseoverride();
    }

    protected function baseoverride(): string
    {
        return 'BASE';
    }
}

class Child extends Base
{
    protected function baseoverride(): string
    {
        return 'SUB'
    }

    // there is no way to override the Confirmation::suboverride method
    // of the $embeddedConfirmation anonymous class from here
}
```

**Comment by PC-COLLEGE-Training** [comment]
That clears it up. I ended up rendering the content of the blocks with the block() function and passing that to the confirmation.html.twig template.

**Comment by m-vo** [comment]
@stof Would you be up for a change, though? Implementation wise it would be possible to pass certain blocks to the embedded template when displaying it. 

I tested a hacky adjustment to the `EmbedNode`, so that blocks containing a prefix in the name (e.g. starting with `_embed_`) would be passed as the second argument into `display()` (without the prefix). We could maybe allow "named embeds" like `{% embed "foo.html.twig" as "bar" %}` and then allow accessing blocks in child templates like `{% block bar.baz %}`. Wdyt?

Or maybe a new attribute to the embed node, that makes all blocks being adopted (so that getting the parent would be more straightforward): `{% embed "foo" with blocks %}`.

So it basically boils down to the question: Is this a limitation by design or by the current implementation?

**Comment by stof** [comment]
I would say, a bit of both.

**Comment by m-vo** [comment]
So, if I get you correctly, this means you would not be open to a PR that improves that enables this behavior in a way? Care to share the design decisions? :slightly_smiling_face: 

The current situation is kind of a bummer if you're a framework that wants to provide templates reusing components (with embed), that your users should still be able to adjust. The only way around this would be to create an extra template extending the component for each usage and then embedding these or lots of nasty set blocks and magic variables (meh).

**Comment by stof** [comment]
Well, this would require rewriting entirely the way blocks and `{% embed %}` work in Twig. And I fear this would create a mess regarding what `parent()` means for instance (because a block could then have 2 different parents when we have embed blocks if they are not isolated). I doubt you will be able to open such a PR (especially not without BC breaks) due to the impact on the whole architecture of Twig.
