### ISSUE TITLE
Suggestion: Support array of enums in `join` filter

### ISSUE THREAD

**Issue by ThomasLandauer** [twigphp/Twig#3689]
Since `doctrine/orm` 2.12.0 arrays of enums are supported (see https://github.com/doctrine/orm/pull/9497):
```php
#[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true, enumType: MyEnum::class)]
private array $foo = [];
```
But this breaks the `join` filter: `{{ entity.foo|join(',') }}` results in:
> Object of class App\Enum\MyEnum could not be converted to string

And `{{ entity.foo.value|join(',') }}` doesn't work either:
> Key "value" for array with keys "0, 1" does not exist.

So I'm suggesting:
* Either modify the `join` filter to automatically use the `value` if the element is an enum
* Or create a new filter `|enumJoin()`

I haven't really checked if other filters are affected as well: https://twig.symfony.com/doc/2.x/filters/index.html

**Comment by stof** [comment]
Well, the `join` filter is just a usage of `implode`. Doing `implode(',', $entity->getFoo());` also breaks when you start using enum in that array instead of strings.

To me, there is no reason for `join` to do a special treatment for backed enums. This filter has always be documented as expecting an array of strings (or of things castable to strings).
And I don't think `joinEnum` should be in the core either. There are other ways to solve this issue, by converting your array of enums to the array of strings expected by `implode()`

**Comment by nicolas-grekas** [comment]
I agree with @stof. This is not a concern twig should care about. This an engine-level consideration.
Closing in favor of https://github.com/php/php-src/pull/8825
