### ISSUE TITLE
can't get a value of a objet 

### ISSUE THREAD

**Issue by tanguyguillo** [twigphp/Twig#3739]
hello

can't get a value of a objet like in screenshoot:

  <pre>
 {{ dump(array.postModified) }}     OK
{{ dump(array.user_id) }}                NULL   (should be here 67
{{ dump(array) }}                             OK
</pre>

<img width="1735" alt="Capture d’écran 2022-08-26 à 15 21 36" src="https://user-images.githubusercontent.com/18627668/186913458-fbe22217-28ea-43f0-b35c-da0d9ecaf55a.png">

can you help me for that ?

**Comment by WebMamba** [comment]
It looks like the user_id property is private. So twig is maybe using a getter method that return null. Maybe check if you have getUserId method that return null 🤔

**Comment by stof** [comment]
Well, `user_id` is a private property, so you cannot access it directly. Without seeing your class definition, I cannot help you to get the right code.

Side note: I recommend using the strict_variables mode in the Twig configuration, which throws an error when it cannot access a variable instead of returning `null`. It makes debugging a lot easier.

**Comment by tanguyguillo** [comment]
In fact i resolve this issue by creating a new entity at the end of my objet and now it's ok.....
