### ISSUE TITLE
[Question] How to print modified AST back to twig syntax?

### ISSUE THREAD

**Issue by TomasVotruba** [twigphp/Twig#3755]
Hi,

I'm trying to modify the Twig node with node visitors. I managed to do that, but I could not find a how to print the modified node back to Twig.

My goal is to change single item like following:

```diff
-{{ product.title }}
+{{ product.name }}
```

How can I achieve that? 

Thank you

**Comment by stof** [comment]
There is no AST printer in Twig (this is not a core use case, and adding support for it would probably add requirements on custom nodes as the Twig AST is extensible, so it is unlikely to be implemented in the core IMO)

**Comment by TomasVotruba** [comment]
Thanks for quick answer! 
Where would you recommend to start if I'd like to make one?

**Comment by brandonkelly** [comment]
It would be next to impossible because the parsing to node conversion is a lossy process. Token parsers are basically just walking through the token stream and doing whatever they want with it, as they convert it to nodes.

One thing nodes do have is knowledge of the line number the token began on, so if you’re OK with doing something a little hacky, you could just refer to the original `.twig` template, and do a basic string replace on it, for the first occurence of the variable/property/method name you want to replace, starting at the line number of the matching node.

**Comment by stof** [comment]
Indeed, to perform refactoring of the template, you would probably need a CST rather than an AST to preserve formatting. And you would indeed need a printer that knows about each kind of nodes, which is impossible in an extensible syntax tree unless each node is required to provide its own printing implementation.

**Comment by TomasVotruba** [comment]
@stof What does CST stand for?

**Comment by TomasVotruba** [comment]
@brandonkelly The line replacement sounds like a really good idea to try out, thanks. What experience do you have with such changes?

**Comment by brandonkelly** [comment]
None, just thinking out loud :) Theoretically possible though, as nodes make their line number available via a public `getTemplateLine()` method.

**Comment by stof** [comment]
@TomasVotruba it stands for Concrete Syntax Tree, i.e. a syntax tree that preserves all information about formatting, comments, etc...
