### ISSUE TITLE
[FR] DocBlocks for functions and filters

### ISSUE THREAD

**Issue by kaermorchen** [twigphp/Twig#3866]
Hi!

I am author of [Twig Language Server](https://github.com/kaermorchen/twig-language-server). It does not have a lot of features right now.

I have hardcoded completions like Twig's functions and filters. It brings some bad practices:

1. It adds more code that needs support.
2. Different versions of twig have different features.

I think the best way to fix it is just parse the Twig package from the composer dictionary, find Twig's functions and filters, and generate completions "on the fly".

But for this, functions and filters should have valid DocBlocks with descriptions and parameters. They haven't right now.

My feature request is to add good DocBlocks descriptions for all things like this.

**Comment by lyrixx** [comment]
IMHO, this is not the right direction. Instead you should boot twig, and ask some question to it. Like "give me the list of functions".

the good question is: how to get **the** good twig. Because you need the one configured in the application.

If the application is symfony, it's quite easy, since everything is a service, you can get it.

But for a project with using just twig, this is quite impossible IMHO.

So I think a solution is to ask for a path, that return a twig instance when you execute it. Then in the service, you call and execute this file, and ask what you need.

phpstan does that does instance

**Comment by kaermorchen** [comment]
> So I think a solution is to ask for a path, that return a twig instance when you execute it. Then in the service, you call and execute this file, and ask what you need.

Will it require a PHP environment? I would like the language server to work just on the javascript platform.

**Comment by lyrixx** [comment]
Yes

**Comment by stof** [comment]
As the list of functions and filters is extensible, I don't see any solution that does not require a PHP environment to boot Twig.

Lots of functions and filters are not defined in the Twig package itself.

**Comment by fabpot** [comment]
Let's close as I don't think there aren't any viable solutions without a PHP env unfortunately.
