### ISSUE TITLE
Cache tags don't work in Symfony when @cache.app is TagAware

### ISSUE THREAD

**Issue by rpkamp** [twigphp/Twig#3869]
I wanted to create this issue in the twig-extra-bundle repository, but since issues seem to be disable there I'll create it here.

The problem I encountered is that twig-cache doesn't work in Symfony when `@cache.app` is TagAware, because the TwigExtraBundle wraps `@cache.app` with a `TagAwareCacheAdapter`, so the cache is tag aware twice to say. Which doesn't work at all, and causes every read to be a MISS.

Making `@cache.app` not TagAware solves the problem, but ideally I didn't want to have to that.

I can see multiple solutions:
1. At least document this so people are aware
2. Check if `@app.cache` is TagAware and if so behave differently
3. Allow configuration for what cache should be injected instead of always using `@cache.app`

**Comment by nicolas-grekas** [comment]
I think `cache.app` shouldn't be made tag-aware. There's already `cache.app.taggable` to get a tag-aware adapter that relies on `cache.app`. It'd be nice to forbid making `cache.app` tag-aware (and tell about `cache.app.taggable` in the exception message ideally when ppl try to do so.)

Can you please open an issue on https://github.com/symfony/symfony/ so that we can keep track of this, and maybe also consider a PR to implement this?

**Comment by rpkamp** [comment]
Issue opened - https://github.com/symfony/symfony/issues/54339

Will close this one now.
