### ISSUE TITLE
replace function fails with variable 'from'

### ISSUE THREAD

**Issue by tacman** [twigphp/Twig#4002]
While I realize there are better ways to remove the host, I discovered this problem and wanted to report it.

```twig

 {% set host = 'https://4e6c-187-244-120-218.ngrok-free.app' %}
        {{ 'https://4e6c-187-244-120-218.ngrok-free.app/oauth/check/google'|replace({
            host : ''
        }) }}

        {{ 'https://4e6c-187-244-120-218.ngrok-free.app/oauth/check/google'|replace({
             'https://4e6c-187-244-120-218.ngrok-free.app':  ''
        }) }}


```

I expected to see '/oauth/check/google', but the replacment doesn't happen.  With the literal string, though, it does work.

**Comment by stof** [comment]
this is because your first filter does not replace the substring `https://4e6c-187-244-120-218.ngrok-free.app` but the substring `host`.

this is due to the way the syntax for Twig hashes (associative arrays) works: quotes are optional around string keys as long as they are valid identifiers (this is the same rule than when creating JS object literals btw, which use the same syntax for them). So `{ host: '' }` is the same than `{ 'host': ''}`.

The way to use an arbitrary expression (and so a variable in your case) in a key is to wrap it in parentheses: https://twig.symfony.com/doc/3.x/templates.html#literals

**Comment by tacman** [comment]
Thanks -- the parenthesis hint is very helpful!

**Comment by stof** [comment]
Note that in JS, computed property names are enclosed in square brackets, not in parentheses. This is a case where the Twig syntax differs from the JS syntax for the hash literals.
