### ISSUE TITLE
Element at index of filtered array throws exception

### ISSUE THREAD

**Issue by JE4GLE** [twigphp/Twig#4104]
Hello!

`{% set filteredList = list|filter(x => x > 0) %}`
`{{ filteredList[0] }}`

will throw the following error:
`Impossible to access a key "0" on an object of class "CallbackFilterIterator" that does not implement ArrayAccess interface.`

Thank you :)

**Comment by smnandre** [comment]
What is the type of the "list" object in your example ? 

The `filter` accepts argument that are either `array` or `Traversable`.

If the argument is an array, it returns an `array`.
Otherwise it must be a `Traversable`, and the filter returns a ... `Traversable`.

[/src/Extension/CoreExtension.php#L1673](https://github.com/twigphp/Twig/blob/ab071efe3b2d5caf2c662c9d018d9eacc76058d9/src/Extension/CoreExtension.php#L1673)
```php
    public static function filter(Environment $env, $array, $arrow)
    {
        // ... 

        if (\is_array($array)) {
            return array_filter($array, $arrow, \ARRAY_FILTER_USE_BOTH);
        }

        // the IteratorIterator wrapping is needed as some internal PHP classes are \Traversable but do not implement \Iterator
        return new \CallbackFilterIterator(new \IteratorIterator($array), $arrow);
    }
```

So you can iterate over the result to get the values, as shown in the [documentation](https://twig.symfony.com/doc/3.x/filters/filter.html) 

```twig
{% for k, v in sizes|filter(x => x > 0) -%}
    {% if k == 0 %}
         {#  If not filtered, v is your expected `filteredList[0]` #}
    {% endif
{% endfor %}
```

You can also use a filter that will call `iterator_to_array` for you, like `slice`


But if what you need is the "first" filtered item still present (so maybe with another key than "0")...
.. then the `first` filter will be your solution

```twig
{% set filteredList =  sizes|filter(x => x > 0)|slice -%}

{{ dump(filteredList|first) }}
```

So back to the first question: what is the type of your "list" object ?  Depending on it, one of these methods could be better than another.

**Comment by JE4GLE** [comment]
Thank you for your answer. I'm using Doctrine to load a [SonataMedia](https://github.com/sonata-project/SonataMediaBundle) Gallery and then get the [galleryItems](https://github.com/sonata-project/SonataMediaBundle/blob/37113934a2f429531714b5d0a999c4686c57173e/src/Model/Media.php#L78).

Currently, I'm using a workaround:

```twig
    {% set filteredIterable = gallery.galleryItems|filter(item => item.enabled) %}
    {# TODO: Workaround for https://github.com/twigphp/Twig/issues/4104 #}
    {% set filteredList = [] %}
    {% for item in filteredIterable %}
        {% set filteredList = filteredList|merge([item]) %}
    {% endfor %}
    {# END OF WORKAOUND #}
    {{ filteredList[0] }}
```

**Comment by stof** [comment]
`array_filter` preserves the keys during filtering. So you have no guarantee that an index 0 exists after filtering even if it exists before.
As said by @smnandre, if you want to get the first item of the array, you can use the `|first` filter (btw, this might still be `null` in case the filtering removes everything, and your workaround still tries to access a non-existent index 0 in that case)
