### ISSUE TITLE
ranged for loop

### ISSUE THREAD

**Issue by ghost** [twigphp/Twig#4145]
i wanted to make a loop like

{% for i 1..pdf_count %}

even if pdf_count=0

so i written
{% for i in range(1, pdf_count, +1) %}

but the step is -1 instead of +1

in other langages, the behavior is not entering the loop

NOT IN TWIG !

of course i can do before the loop
if pdf_count > 0
to resolve my pb

but the pb remains for the behavior in twig

thanks

**Comment by smnandre** [comment]
This is probably not something i'd recommand, but... if you _had to_ do it like you want, you can leverage [slice](https://twig.symfony.com/doc/3.x/filters/slice.html) to limit the number the results.

(working there as you start with 1)

```twig
{% for i in (1..pdf_count)[:pdf_count] %}
```

```
# pdf_count = 0, you get 0 items
(1..0): 1 0    
(1..0)[:0]:     

(1..1): 1      
(1..1)[:1]: 1     
  
(1..2): 1 2    
(1..2)[:2]: 1 2    

...
```
  
---

I'm answering you because i found the "challenge" fun (also because it _could_ help someone else one day).

But with the tone of your message... i really hesitated. 

> in other langages, the behavior is not entering the loop

You are posting an issue regarding Twig, this is irelevant.

> NOT IN TWIG !

In every langage i can think of, `for i in [1, 0]` will loop twice. 

What seems to confuse you here is the range function, described (with no caps locks) in:
* the [Twig documentation](https://twig.symfony.com/doc/3.x/functions/range.html)
* the [PHP documentation](https://www.php.net/manual/en/function.range.php)

PS: 

> but the pb remains for the behavior in twig

A _feature_ does not become a _problem_ only because it does not work like _you_ expect

**Comment by fabpot** [comment]
I'm not sure I get the issue. Behind the scenes, the `..` operator uses the PHP `range`operator`.

I've just tried the following:

```
{% for i in 1..0 %}
    {{ i }}
{% endfor %}
```

And I get `1` then `0` as you would expect.

Am I missing something?

**Comment by smnandre** [comment]
@fabpot when pdf_count = 0, @EmmanuelTuloup expected the generated range to be empty.

So the idea was to write `if pdf_count > 0 ? range(1..pdf_count) : []` as a one-liner

**Comment by fabpot** [comment]
Closing here as the behavior is the same as PHP (as we are just reusing the `range()` PHP function):

```php
<?php

foreach (range(1, 0) as $i) {
    print $i."\n";
}
```
