### ISSUE TITLE
Unable to update to Twig > 3.11 when running PHP 7.4

### ISSUE THREAD

**Issue by mpanitz** [twigphp/Twig#4297]
Hi there,

I received package conflicts during composer update in a project that is running Twig 3.8 using PHP 7.4 with `roave/security-advisories` as a dev dependency. I saw that a security vulnerabilty regarding the sandbox mode was fixed and is contained in Twig 3.14.

I am currently not able to update to a non vulnerable Twig 3 version though, since the minimum PHP requirement was raised to 8.0 in Twig 3.12. Of course, moving the project away from PHP 7.4 would be the ideal scenario, but I would consider raising the PHP minimum requirement to 8.0 in a minor version as a BC break in itself. 

Since the security issue was fixed in a patch level release for Twig 2 and Twig 1 as well, I wanted to kindly ask if it would be possible to release the fix in a 3.11.1 release as well?

**Comment by stof** [comment]
Bumping the min PHP version in a minor version is fine in the PHP ecosystem thanks to Composer taking those PHP requirements into account during the dependency resolution, so a `composer update` for a project using semver constraints will *not* install incompatible packages.
The main reason why bumping the minimum node version is a BC break for the npm ecosystem is because npm (or other package managers using the same ecosystem) doesn't take the supported node version into account when selecting the version (it only reports a warning or error later if the selected version is incompatible).

@fabpot as the security patch has been backported to the unmaintained 1.x branch, maybe it makes sense to also backport it to 3.11

**Comment by fabpot** [comment]
I've just released 3.11.1 with the fix.

**Comment by mpanitz** [comment]
Thanks a lot for releasing so quickly. The release is still marked as vulnerable on packagist. I'm not familiar with the process, so I'm just curious if it will take a while to register as non-vulnerable?

**Comment by stof** [comment]
GitHub has a weird behavior: it has both repository-level advisories and a global database.
Creating a repository advisory adds it automatically in the global database, but updating it does not get synchronized automatically to the global database AFAICT. I submitted an update of the global database in https://github.com/github/advisory-database/pull/4780
