### ISSUE TITLE
the "\" character is ignored in Twig v3 but will not be in v4

### ISSUE THREAD

**Issue by ianmclaughlin** [twigphp/Twig#4343]
This deprecation message isn't actually true? 

For Twig 3.14
```
<br>double_slash: {{ date | date('Ymd\\THis') }}
<br>single_slash: {{ date | date('Ymd\THis') }}
```
results in 
double_slash: 20240926T103021
single_slash: 20240926BST103021

How do I fix the deprecation?

**Comment by stof** [comment]
are you sure your reported results are not mixed up ?

In Twig 3.14, `\T` is parsed as being `T` (i.e. it considers the `\` as being part of an escape sequence `\T` even though `T` does not need any escaping)

**Comment by ianmclaughlin** [comment]
feel free to run the code yourself...

I suspect the deprecation message is incorrectly showing for `\\` cases when it should only show for `\`cases

**Comment by stof** [comment]
This is the output I get when running this (adding a case `no_slash`:
```
<br>double_slash: 20240926T103031\n
<br>single_slash: 20240926UTC103031\n
<br>no_slash:     20240926UTC103031
```

As you can see, the `single_slash` and `no_slash` cases produce the same output in Twig 3.x. they format the date using `YmdTHis` as format (where `T` will show the timezone name, which is `UTC` in my case).

and I get a single deprecation being reported.

@fabpot something is still wrong with that deprecation. It says `User Deprecated: Since twig/twig 3.12: Character "T" at position 5 should not be escaped; the "\" character is ignored in Twig v3 but will not be in v4. Please remove the extra "\" character.`. However, this `position 5` seems to be the position inside the string literal, not the position inside the template, making it totally useless to identify where the deprecation actually comes from.

**Comment by ianmclaughlin** [comment]
The example I provided showed a difference between double-slash case and a single slash case, and yours does too.

The deprecation is shown for the double-slash case, but when I change the code to take out a slash the deprecation is not shown. This made me think the deprecation was fixed, when I had instead altered the result.

**Comment by ruudk** [comment]
I'll try to tweak the deprecation message, so that it's more clear.

**Comment by stof** [comment]
@ianmclaughlin of course it does in 3.x. That's precisely why we have a deprecation warning (in 4.0, the single_slash case will be changed so that `\T` is parsed as a `\` followed by a `T` instead as `\T` is not an actual escape sequence).

The deprecation is triggered for the single_slash case, not for the double_slash case

**Comment by ruudk** [comment]
Created a PR to improve a few things:
- https://github.com/twigphp/Twig/pull/4344
