### ISSUE TITLE
guard tag fallback, "not" or filter_exists functions 

### ISSUE THREAD

**Issue by tacman** [twigphp/Twig#4388]
I love the new guard tag.  Is there a way to check the _results_ of a guard check, so there can be a fallback?

```twig
{% guard function dump %}
   {{ dump(obj) }}
{% else %}
   <pre>{{ obj|json_encode }}</pre>
{% endguard %}
```

OR 

```twig

{% guard filter country_name %}
    {{ countryCode|country_name }}
{% endguard %}

{% not guard filter country_name %}
    {{ countryCode }}
{% endguard %}
```

or perhaps some underlying function

```twig
{% if filter_exists('country_name') %}
...
```

I could see this being particular useful for bundles.  

I know the guard tag just got added to 3.x, I'm quite enthusiastic about using it!  #4304

**Comment by fabpot** [comment]
```twig
{% not guard filter country_name %}
    {{ countryCode }}
{% endguard %}
```

is equivalent to:

```twig
{% guard filter country_name %}
{% else %}
    {{ countryCode }}
{% endguard %}
```

The other examples of the ``guard`` tag you mention are already working, right?

**Comment by stof** [comment]
> or perhaps some underlying function

this suggested underlying used in a `{% if %}` won't help much, because the usage of the filter inside the body of the `{% if %}` tag will still not be able to use the filter without trigger a *compile-time* error, as Twig filters and functions are validated at compile time.
That's exactly why the new feature is a new tag instead, which resolves the condition during the *parsing* of the template, to avoid reporting errors about the usage of an unknown filter inside the guarded block if it will be discarded by the guard block.

**Comment by tacman** [comment]
DOH.  else works as expected.  Thanks!
