### ISSUE TITLE
loop.last does not work with for ... if syntax

### ISSUE THREAD

**Issue by greg0ire** [twigphp/Twig#687]
I have a problem with this file : https://github.com/KnpLabs/KnpDisqusBundle/blob/master/Resources/views/js.html.twig , which I reproduced more simply, like this:

```
{% for test in 0..3 if true %}
   {{loop.last}}
{% endfor %}
```

This raises the following error :

> Item "last" for "Array" does not exist

**Comment by vpa24** [comment]
It worked for me to find **last item for List(text) type loop in Drupal 8 Twig**
```
{% for key, item in content.field_chas_front_panel_leds if key|first != '#' %}
	{% if loop.index == node.field_chas_front_panel_leds.getvalue|length %}
		{{item['#markup'] }}
	{% else %}
		{{item['#markup']  ~ ', '}}
	{% endif %}
{% endfor %}
```

**Comment by stof** [comment]
this won't work, as `node.field_chas_front_panel_leds.getvalue|length` will count all items, while `loop.index` will be incremented only when the filter matches (which is why `loop.last` cannot work either)

**Comment by joelstein** [comment]
For Drupal, just use the [Twig Tweak](https://www.drupal.org/docs/8/modules/twig-tweak/cheat-sheet-8x-2x) module's "children" filter, like so:

```
{% for item in content.field_name | children(true) %}
  {# loop.length, loop.revindex, loop.revindex0, and loop.last are now available #}
{% endfor %}
```

**Comment by fabpot** [comment]
With the newest versions of Twig, that's not an issue anymore.

**Comment by Tchekda** [comment]
> With the newest versions of Twig, that's not an issue anymore.

Hi, as of today with version 2.11.3 of twig, the error `The "loop.last" variable is not defined when looping with a condition.` is still there.
I'm not sure if you were talking about that...

**Comment by fabpot** [comment]
@Tchekda Can you give us a small reproducer?

**Comment by Tchekda** [comment]
Hi @fabpot , thank you so much for answering that fast.
I know that this code is definitively wrong and bad but that shows clearly the error (in my case `future_tournaments` are not defined yet when this error appears) : 
```
{% for tournament in future_tournaments if future_tournaments is defined %}
     {% for day in tournament.date %}
             {{ day.day }} {{ day.month }} {{ (loop.last == false and tournament.date|length > 1 ? 'et') }}
     {% endfor %}
     ({{ tournament.category }}){{ (loop.last == false and future_tournaments|length > 1 ?',') }}
{% else %}
     XXX
{% endfor %}
```
So i'm my project i removed `if future_tournaments is defined` that is useless because if twig sees that the varaiable is not defined, it goes to the `{% else %}` statement

**Comment by fabpot** [comment]
You example is using an `if` condition, so the limitation still applies. You need to convert your code to use the new `filter` filter. In your example, the filter does not really make sense, so you need to put the condition outside the `for` tag.

**Comment by Tchekda** [comment]
> You example is using an `if` condition, so the limitation still applies. You need to convert your code to use the new `filter` filter. In your example, the filter does not really make sense, so you need to put the condition outside the `for` tag.

Oh, ok so i didn't understood well your answer, i thought you were talking about the `if` statement. So you're right about the filter, it does not throw any error. 
Thank you for answering me, do you have a link that explains better the filter system for loops, because the [documentation](https://twig.symfony.com/doc/2.x/tags/for.html#adding-a-condition) is still showing an `if` statement?

**Comment by fabpot** [comment]
@Tchekda See https://twig.symfony.com/doc/2.x/filters/filter.html

**Comment by Tchekda** [comment]
End of the issue for me, thank you so much for helping me solving it.
